### ISSUE TITLE
tribler opens too many files by default

### ISSUE THREAD

**Issue by themusicgod1** [Tribler/tribler#3014] opened 2017-06-23 12:21 UTC
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

next / 7.0 / bc8991f

##### Operating system and version: #####

ubuntu 17.04 zesty

##### Expected behavior: #####

running tribler does not negatively impact operation of rest of system

##### Actual behavior: #####

Some default to ubuntu 17.04 user level file descriptor limit is exhausted.

##### Steps to reproduce the behavior: #####

1) run tribler

2) let tribler run overnight, with trustchain ("multichain" in next) enabled with/without torrents 

3) try to run another application that requires some free file descriptors to function properly, like eog.
application fails complaining "too many open files".  Closing tribler frees up the fds and eog works fine afterwards.

ulimit :
open files                      (-n) 1024

themusicgod1@eva1:~$ lsof | grep -i 'python2.7' | wc -l
10358

While it might very well be that stock ubuntu 17.04 is living a little close to the edge of how many files can reasonably expected to run applications like tribler, at the same time tribler should run in environments where the settings are set low without causing interference with other programs.

##### Relevant log file output: #####

n/a

**Comment by qstokkink** [comment] 2017-06-23 14:16
May be related to #2966?

**Comment by devos50** [comment] 2017-06-24 08:51
@themusicgod1 could you give the full output of the `lsof | grep -i 'python2.7' | wc -l` command so we can see whether we are leaking file descriptors? I recently fixed a bug where we didn't close a socket correctly. Maybe we forgot something.

**Comment by qstokkink** [comment] 2017-08-25 08:41
I am unable to reproduce this on Ubuntu 16.10, the file descriptor count is stable no matter how long I wait or how many times I lock the OS. I'll try setting up a Ubuntu 17 VM to test this.

I also developed a most ungodly one-liner to print python's open fds:
```bash
for i in `ps -ef | awk '$8=="python2.7" {print "/proc/"$2"/fd"}'`; do echo "$i:"; ls -l $i | grep ^l | grep -o "[0-9]\+ ->.*"; done
```

**Comment by qstokkink** [comment] 2017-08-26 09:37
I just set up a Ubuntu 17.04 VM and I can confirm this: the amount of open sockets keeps growing (on 16.10 this doesn't go above +- 40 and 75 open fds):

```
quinten@quinten-VirtualBox:~$ for i in `ps -ef | awk '$8=="python2.7" {print "/proc/"$2"/fd"}'`; do echo "$i:"; ls -l $i | grep ^l | grep -o "[0-9]\+ ->.*"; done
/proc/19432/fd:
0 -> /dev/pts/0
1 -> /dev/pts/0
10 -> anon_inode:[eventfd]
100 -> socket:[48543]
101 -> socket:[49422]
102 -> socket:[49453]
103 -> socket:[49455]
104 -> socket:[49457]
105 -> socket:[49459]
106 -> socket:[47710]
107 -> socket:[47711]
108 -> socket:[47712]
109 -> socket:[47713]
11 -> socket:[47611]
110 -> socket:[47714]
111 -> socket:[47715]
112 -> socket:[47716]
113 -> socket:[47717]
114 -> socket:[47718]
115 -> socket:[47719]
116 -> socket:[47720]
117 -> socket:[47721]
118 -> socket:[47722]
119 -> socket:[49479]
12 -> anon_inode:[eventfd]
120 -> socket:[49481]
121 -> socket:[49483]
122 -> socket:[46579]
123 -> socket:[46580]
124 -> socket:[46581]
125 -> socket:[49488]
126 -> socket:[48604]
127 -> socket:[48889]
128 -> socket:[48890]
129 -> socket:[48891]
13 -> anon_inode:[eventfd]
130 -> socket:[48892]
131 -> socket:[48893]
132 -> socket:[48895]
133 -> socket:[48896]
134 -> socket:[48897]
135 -> socket:[48898]
136 -> socket:[48899]
137 -> socket:[48903]
138 -> socket:[48904]
139 -> socket:[48920]
14 -> socket:[47613]
140 -> socket:[48921]
141 -> socket:[48922]
142 -> socket:[48924]
143 -> socket:[48925]
144 -> socket:[48926]
145 -> socket:[48927]
146 -> socket:[48928]
147 -> socket:[48930]
148 -> socket:[48931]
149 -> socket:[48932]
15 -> anon_inode:[eventfd]
150 -> socket:[48933]
151 -> socket:[48934]
152 -> socket:[48936]
153 -> socket:[48937]
154 -> socket:[48938]
155 -> socket:[48939]
156 -> socket:[48940]
157 -> socket:[48942]
158 -> socket:[48943]
159 -> socket:[48944]
16 -> anon_inode:[eventfd]
160 -> socket:[48945]
161 -> socket:[48946]
162 -> socket:[48948]
163 -> socket:[48949]
164 -> socket:[48951]
165 -> socket:[48953]
166 -> socket:[48955]
167 -> socket:[48957]
168 -> socket:[48958]
169 -> socket:[48960]
17 -> anon_inode:inotify
170 -> socket:[48961]
171 -> socket:[48963]
172 -> socket:[48966]
173 -> socket:[48968]
174 -> socket:[48970]
175 -> socket:[46620]
176 -> socket:[46621]
177 -> socket:[49667]
178 -> socket:[49668]
179 -> socket:[49673]
18 -> socket:[49246]
180 -> socket:[49674]
181 -> socket:[49675]
19 -> socket:[47615]
2 -> /dev/pts/0
20 -> socket:[47618]
21 -> anon_inode:[eventfd]
22 -> socket:[49247]
23 -> socket:[49253]
24 -> socket:[49255]
25 -> /usr/share/icons/ubuntu-mono-dark/icon-theme.cache
26 -> /usr/share/icons/Humanity-Dark/icon-theme.cache
27 -> /usr/share/icons/Humanity/icon-theme.cache
28 -> pipe:[47624]
29 -> pipe:[47624]
3 -> socket:[47607]
30 -> anon_inode:[eventfd]
31 -> socket:[47627]
32 -> anon_inode:[eventfd]
33 -> socket:[49297]
34 -> /run/user/1000/qt-trayicon-T19432.png
35 -> socket:[49299]
36 -> anon_inode:[eventfd]
37 -> /usr/share/mime/mime.cache
38 -> anon_inode:[eventfd]
39 -> socket:[46501]
4 -> anon_inode:[eventfd]
40 -> anon_inode:[eventfd]
41 -> socket:[47630]
42 -> anon_inode:[eventfd]
43 -> anon_inode:[eventfd]
44 -> socket:[46503]
45 -> socket:[47654]
46 -> anon_inode:[eventfd]
47 -> socket:[49356]
48 -> socket:[49360]
49 -> socket:[47655]
5 -> /dev/urandom
50 -> socket:[47656]
51 -> socket:[47657]
52 -> socket:[47658]
53 -> socket:[47659]
54 -> socket:[47660]
55 -> socket:[47661]
56 -> socket:[47662]
57 -> socket:[47663]
58 -> socket:[47664]
59 -> socket:[47665]
6 -> pipe:[47605]
60 -> socket:[47666]
61 -> socket:[47667]
62 -> socket:[47668]
63 -> socket:[47669]
64 -> socket:[47670]
65 -> socket:[47671]
66 -> socket:[47673]
67 -> socket:[47675]
68 -> socket:[49392]
69 -> socket:[49393]
7 -> pipe:[47605]
70 -> anon_inode:[eventfd]
71 -> socket:[47696]
72 -> socket:[49394]
73 -> socket:[47700]
74 -> socket:[47688]
75 -> socket:[47679]
76 -> anon_inode:[eventfd]
77 -> socket:[46563]
78 -> socket:[47680]
79 -> socket:[47681]
8 -> anon_inode:[eventfd]
80 -> socket:[47683]
81 -> socket:[47685]
82 -> socket:[47686]
83 -> socket:[47687]
84 -> socket:[47689]
85 -> socket:[47691]
86 -> socket:[47693]
87 -> socket:[48528]
88 -> socket:[48529]
89 -> socket:[48530]
9 -> socket:[47610]
90 -> socket:[48531]
91 -> socket:[48532]
92 -> socket:[48534]
93 -> socket:[48535]
94 -> socket:[48536]
95 -> socket:[48537]
96 -> socket:[48538]
97 -> socket:[48540]
98 -> socket:[48541]
99 -> socket:[48542]
/proc/19453/fd:
0 -> /dev/pts/0
1 -> /dev/pts/0
10 -> anon_inode:[eventfd]
11 -> socket:[47611]
12 -> anon_inode:[eventfd]
13 -> anon_inode:[eventfd]
14 -> socket:[47613]
15 -> anon_inode:[eventfd]
16 -> anon_inode:[eventfd]
17 -> anon_inode:inotify
18 -> socket:[49246]
19 -> socket:[47615]
2 -> /dev/pts/0
20 -> socket:[47618]
21 -> anon_inode:[eventfd]
22 -> socket:[49247]
23 -> socket:[49253]
24 -> socket:[49255]
25 -> /usr/share/icons/ubuntu-mono-dark/icon-theme.cache
26 -> /usr/share/icons/Humanity-Dark/icon-theme.cache
27 -> /usr/share/icons/Humanity/icon-theme.cache
28 -> pipe:[47624]
29 -> pipe:[47624]
3 -> socket:[47607]
30 -> anon_inode:[eventfd]
31 -> socket:[47627]
32 -> anon_inode:[eventfd]
33 -> socket:[49297]
34 -> /run/user/1000/qt-trayicon-T19432.png
35 -> socket:[49299]
36 -> anon_inode:[eventfd]
37 -> /usr/share/mime/mime.cache
38 -> anon_inode:[eventfd]
39 -> socket:[46472]
4 -> anon_inode:[eventfd]
40 -> /dev/null
41 -> pipe:[49310]
42 -> pipe:[49310]
43 -> socket:[49328]
44 -> /home/quinten/.Tribler/sqlite/tribler.sdb
45 -> /home/quinten/.Tribler/sqlite/tribler.sdb-wal
46 -> /home/quinten/.Tribler/sqlite/tribler.sdb-shm
47 -> /home/quinten/.Tribler/collected_torrents/LOG
48 -> /home/quinten/.Tribler/collected_torrents/LOCK
49 -> /home/quinten/.Tribler/collected_torrents/000005.log
5 -> /dev/urandom
50 -> /home/quinten/.Tribler/collected_torrents/MANIFEST-000004
51 -> /home/quinten/.Tribler/collected_metadata/LOG
52 -> /home/quinten/.Tribler/collected_metadata/LOCK
53 -> /home/quinten/.Tribler/collected_metadata/000003.log
54 -> /home/quinten/.Tribler/collected_metadata/MANIFEST-000002
55 -> socket:[49329]
56 -> /home/quinten/.Tribler/sqlite/dispersy.db
57 -> /home/quinten/.Tribler/sqlite/dispersy.db-wal
58 -> socket:[49336]
59 -> socket:[46558]
6 -> pipe:[47605]
60 -> socket:[46566]
61 -> socket:[46564]
64 -> /dev/urandom
68 -> /home/quinten/.Tribler/sqlite/multichain.db
69 -> /home/quinten/.Tribler/sqlite/multichain.db-wal
7 -> pipe:[47605]
70 -> socket:[49338]
71 -> socket:[49339]
72 -> socket:[49340]
73 -> socket:[49341]
74 -> socket:[49342]
75 -> /home/quinten/.Tribler/pymdht.log
76 -> socket:[49343]
77 -> anon_inode:[eventfd]
78 -> anon_inode:[eventpoll]
79 -> anon_inode:[timerfd]
8 -> anon_inode:[eventfd]
80 -> /dev/urandom
81 -> socket:[47640]
82 -> socket:[47641]
83 -> socket:[47642]
84 -> socket:[47644]
86 -> socket:[47647]
87 -> socket:[47648]
88 -> socket:[47649]
89 -> socket:[47650]
9 -> socket:[47610]
90 -> socket:[47651]
91 -> socket:[49344]
92 -> socket:[49346]
93 -> socket:[49359]
94 -> socket:[49350]
95 -> socket:[49357]
```

**Comment by qstokkink** [comment] 2017-08-29 13:29
@devos50 Do you have any experience with finding the actual socket for a QNetworkAccessManager/QNetworkRequest/QNetworkReply? I have been Googling for a few hours now and I still don't even remotely know where to look.

**Comment by devos50** [comment] 2017-08-29 15:01
@qstokkink nope, I've never dived that much in the http framework provided by Qt :(

**Comment by qstokkink** [comment] 2017-09-07 15:16
Just updated to latest `next` can still reproduce in a couple of minutes over 400 socket fds open on GUI process. Here is the debug panel dump:
![1](https://user-images.githubusercontent.com/3630389/30170754-44ceb790-93f0-11e7-8c2e-0dd2a957ea55.png)
![2](https://user-images.githubusercontent.com/3630389/30170755-44e4cc2e-93f0-11e7-86c0-9983350ed889.png)
![3](https://user-images.githubusercontent.com/3630389/30170757-44ed3454-93f0-11e7-93d6-e25a347c4802.png)
![4](https://user-images.githubusercontent.com/3630389/30170761-450d1fee-93f0-11e7-800e-bf619b07e354.png)
![5](https://user-images.githubusercontent.com/3630389/30170756-44e716a0-93f0-11e7-92c5-1ba70daaaabb.png)
![6](https://user-images.githubusercontent.com/3630389/30170759-45058842-93f0-11e7-9062-9e449f948abc.png)
![7](https://user-images.githubusercontent.com/3630389/30170758-4501d8aa-93f0-11e7-84d7-883c508f9739.png)
![8](https://user-images.githubusercontent.com/3630389/30170760-450b5b96-93f0-11e7-98ba-a1baa253c9f4.png)
![9](https://user-images.githubusercontent.com/3630389/30170762-458c2c58-93f0-11e7-91d3-a84c9b929afd.png)

**Comment by qstokkink** [comment] 2017-09-08 07:08
Weird! If I modify `TriblerGUI/widgets/downloadspage.py` [line 141](https://github.com/Tribler/tribler/blob/devel/TriblerGUI/widgets/downloadspage.py#L141), like:

```python
self.schedule_downloads_timer()
return
if QSystemTrayIcon.isSystemTrayAvailable():
    self.window().tray_icon.setToolTip(
        "Down: %s, Up: %s" % (format_speed(total_download), format_speed(total_upload)))
```
There is no socket leak.

```python
if QSystemTrayIcon.isSystemTrayAvailable():
    self.window().tray_icon.setToolTip(
        "Down: %s, Up: %s" % (format_speed(total_download), format_speed(total_upload)))
self.schedule_downloads_timer()
return
```
Will leak sockets though.

How in the world is the system tray connected to open sockets?!

**Comment by devos50** [comment] 2017-09-08 07:24
Seriously...

The issue you linked is not our specific issue I think since they indicate it was fixed in Ubuntu 16.04/16.10 and for us, it's broken on a newer version.

As a workaround we might disable this logic on Ubuntu 17.04 (+?). It is possible to detect the Ubuntu version (see https://stackoverflow.com/questions/19694536/how-do-i-detect-the-ubuntu-version). What do you think about this?

**Comment by qstokkink** [comment] 2017-09-08 07:32
@devos50 Oh sorry, I should have linked to the fix they made for that issue instead:

> # Proposed Fix
>The proposed fix is identical to what was uploaded to Yakkety as version   0.3.0+16.10.20160628.1-0ubuntu1. The fix is using unique connections for all AppMenuPlatformSystemTrayIcon instances.

I guess we could wrap `isSystemTrayAvailable()` and have it return `true` for Ubuntu 17+? Although this might be very dangerous long term.

**Comment by devos50** [comment] 2017-09-08 07:47
@qstokkink it is, that's why I put question mark before the + :).

For now, I think it's fine if we just detect 17.04. When 17.10 is released, this issue will hopefully be fixed and if not, we can adjust our code accordingly (17.10 will be released October 19 this year: http://www.omgubuntu.co.uk/2017/04/ubuntu-17-10-release-date).

**Comment by qstokkink** [comment] 2017-09-08 07:51
@devos50 I agree, that would be the best use of our time. The alternative would be to wrap X11 using ctypes and checking if the system tray is available (a lot of work and error prone 🤢).

**Comment by devos50** [comment] 2017-09-08 08:01
Indeed, that would be very error-prone. This is probably the easiest solution.

**Comment by qstokkink** [comment] 2017-09-08 08:04
@devos50 are you O.K. with sacrificing one socket to check `isSystemTrayAvailable()` once when the `TriblerWindow` is created (so we at least have some idea what is going on with the tray for Ubuntu 17.04)?

**Closed** 2017-09-08 09:02 UTC
Labels: bug

**Comment by qstokkink** [comment] 2017-09-10 08:31
Here's a minimal example:

```python
import os

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QSystemTrayIcon

class TestApp(QtWidgets.QApplication):
        
    def on_started(self):
        for i in range(500):
            QSystemTrayIcon.isSystemTrayAvailable()
        
        self.exit(0)
    
    def exec_(self):
        timer = QtCore.QTimer()
        timer.setSingleShot(True)
        timer.timeout.connect(self.on_started)
        timer.start(500)
        
        super(TestApp, self).exec_()

TestApp([]).exec_()

print len(os.listdir("/proc/%d/fd" % os.getpid()))
```

On Ubuntu 16.10:
``17``

On Ubuntu 17.04:
``516``
