### ISSUE TITLE
Current approach of configuring state directory doesn't work well

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#3125] opened 2017-09-29 12:23 UTC
Current approach of configuring state directory doesn't work when you have already got a .Tribler directory in the default location.

The current way for select state directory and all kinds of keys, are first look at the default location to see if there is a ./Tribler , if not, check the location we configured. That means if the ./Tribler folder is there, it does 0 matter what state directory location we configured.

This is quite annoying if the user is trying to run multiple Tribler instance or having multiple dispersy ID.

**Comment by qstokkink** [comment] 2017-09-29 13:19
1. I could not reproduce any interference of the main `.Tribler` settings and those used in the tests.
2. Every Tribler/Dispersy node will need its own state directory: otherwise you would be sharing databases and private keys, which would make no sense.
3. Usually you would use Gumby to work with multiple nodes. You can use the unit tests for this however, but you will need to set up a state dir for each node you create. You can find an example of this here: https://github.com/Tribler/tribler/blob/devel/Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py#L71 .

If you have an example to disprove (1.) please reply with the minimal example. As I see no reason to support multiparty asynchronous access to the same state directory, I will close this issue.

**Comment by EinNarr** [comment] 2017-09-29 13:35
I don't mean "multiple asynchronous access to the same state directory". I meant "to different directory".
If someone, of any reason, need to have multiple state_dir on the same device, any of them could not be placed at the default location. Or it will be the only accessible state_dir whatever you configure the location of state_dir.

**Comment by qstokkink** [comment] 2017-09-29 13:45
@EinNarr I see, you want to support multiple users within the same device context. I guess this makes sense when tying channels to user identities.

**Comment by synctext** [comment] 2017-09-29 13:59
> If someone, of any reason, need to have multiple state_dir on the same device

That is something to support only for 2018 and beyond. For internal thesis testing purposes I guess it's easy to keep locations apart.

**Comment by EinNarr** [comment] 2017-09-29 14:09
@synctext True. It took me some time to debug several days ago, and fixed by hard code the location.

**Comment by ichorid** [comment] 2020-07-17 16:51
Solved by using `TSTATEDIR` environment variable.

**Closed by ichorid** 2020-07-17 16:51 UTC
Labels: enhancement, long-term
