### ISSUE TITLE
missing rpm package

### ISSUE THREAD

**Issue by damnms** [Tribler/tribler#5820] opened 2020-12-07 18:29 UTC
its more a feature request than a bug report...
would it be possible to provide a .rpm instead of only .deb?
centos/redhat/fedora/etc. use .rpm and they are also widely used

**Comment by damnms** [comment] 2020-12-07 18:35
or even better, provide flatpak/snapd packages
https://www.reddit.com/r/tribler/comments/jxxqw3/hello_from_fedora/

**Comment by devos50** [comment] 2020-12-08 10:25
Thank you for your suggestion! This would be very nice to have indeed and something that we have been discussing for a while now. We are working on a snap package but that requires more work to make sure it is stable.

Since this issue is mostly a duplicate of #4938, I will close this issue.

**Closed by devos50** 2020-12-08 10:25 UTC

**Comment by Kashcheyeu** [comment] 2021-01-24 11:12
In my opinion, it is better to use some middle ground in the form of a special service for compiling applications and building packages — https://copr.fedorainfracloud.org/.
