### ISSUE TITLE
Wrong version, hencee not merge 7.1 to 7.5 db, but deleted 7.5

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#5488] opened 2020-07-17 16:35 UTC
##### Tribler version/branch+revision: #####
7.5
##### Operating system and version: #####
WIndows 10 2004
##### Steps to reproduce the behavior: #####
On the jenkins Github of today's date a 7.1 version was submitted instead of 7.5.
I did not notice, so this version scratched all my 7.5 database, ratio and token balance.
I guess it was a stupid mistake at your end, but I should have watched more carefully myself.
I hope you pay more attention and adjust the code and check whether a 7.5 database and info exists and do a merge instead of a delete, build and convert 7.1 to 7.5

**Comment by devos50** [comment] 2020-07-17 16:49
> On the jenkins Github of today's date a 7.1 version was submitted instead of 7.5.

This is most likely a build that was made from my local branch, since I was testing out #5484. Even though it might look this was a 7.1 build, it actually contains the code on the `release-7.5` branch (and therefore of version 7.5.2).

The builds that we make [in our Jenkins job](https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Win64/) are not guaranteed to be stable and might contain highly experimental code that can possibly result in unexpected behaviour. Installing these versions is therefore on your own risk. We guarantee to publish stable or experimental versions [on our GitHub release page](https://github.com/tribler/tribler/releases).

That said, I think you can still recover you old database, since we have state directory versioning now. @ichorid can you help with this recovery process?

**Comment by ichorid** [comment] 2020-07-17 17:11
7.5+ use versioned state dir. It will never overwrite or delete anything. Your stuff should be safe in `.Tribler/7.5` directory. Run the release 7.5.1 version and see what happens. It should look into that dir.
Though, I don't know what could happen to the state directory system if someone changes the version forcefully to less then 7.5 in the current codebase.

**Comment by devos50** [comment] 2020-07-18 07:36
Closing this issue as this is most likely resolved by restoring a backup. Please re-open if there are any errors during this recovery process.

**Closed by devos50** 2020-07-18 07:36 UTC
Labels: question

**Comment by synctext** [comment] 2020-07-24 09:29
@Nubro01 Thank you for posting this!
As one of our most loyal users over the past decade+ you can see we're still struggling with code stability. We are in much better shape then Tribler Lab has ever been. It continuous to be difficult to produce quality software. We might even do automatic reverts of code commits if stability is compromised...
Coming 12 months the is a ban on all significant changes. Only small commits are allowed and relentless small steps forward. After 12 months we'll re-evaluate and question everything again.
