### ISSUE TITLE
WIndows build 17017 tribler error

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3159] opened 2017-10-17 10:19 UTC
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Oct 13th version
##### Tribler version/branch+revision: #####
RC3
##### Operating system and version: #####
Windows 10 X64 build 17017
##### Steps to reproduce the behavior: #####
Error comes up, buit tribler continues seeding
##### Expected behavior: #####
No error message
##### Actual behavior: #####
Error pops up
##### Relevant log file output: #####
An error occurred during the request:

{"error": {"message": "", "code": "UnicodeDecodeError", "handled": false, "trace": ["  File \"lib\\site-packages\\twisted\\web\\server.py\", line 184, in process\n", "  File \"lib\\site-packages\\twisted\\web\\server.py\", line 235, in render\n", "  File \"lib\\site-packages\\twisted\\web\\resource.py\", line 250, in render\n", "  File \"Tribler\\Core\\Modules\\restapi\\downloads_endpoint.py\", line 225, in render_GET\n", "  File \"Tribler\\Core\\Utilities\\json_util.py\", line 96, in dumps\n"]}}

**Comment by Nubro01** [comment] 2017-10-17 10:20
second time.

An error occurred during the request:

{"error": {"message": "", "code": "UnicodeDecodeError", "handled": false, "trace": ["  File \"lib\\site-packages\\twisted\\web\\server.py\", line 184, in process\n", "  File \"lib\\site-packages\\twisted\\web\\server.py\", line 235, in render\n", "  File \"lib\\site-packages\\twisted\\web\\resource.py\", line 250, in render\n", "  File \"Tribler\\Core\\Modules\\restapi\\downloads_endpoint.py\", line 225, in render_GET\n", "  File \"Tribler\\Core\\Utilities\\json_util.py\", line 96, in dumps\n"]}}

I am able to close the POPUP MESSAGE AND CONTINUE.

**Comment by Nubro01** [comment] 2017-10-17 11:04
No I upgraded to Windows 10 insider build 17017 and tested tribler with previous version. Got the error and tried Tribler build from oct 13th and also got the error. Was only seeding the Three Torrents that I supplied before._

**Comment by qstokkink** [comment] 2017-10-17 11:07
@Nubro01 thanks for the info! Now we finally have a place to start debugging this.

**Comment by qstokkink** [comment] 2017-11-08 07:58
I've been trying for the past three weeks to get this to trigger, but it just doesn't seem to fail. If anyone can reproduce this issue with the latest build ([Windows x64 build here](https://jenkins.tribler.org/job/Build-Tribler_Win64_next/)) please post it.

**Comment by devos50** [comment] 2017-11-09 09:13
This is actually a duplicate of #3059. We continue the discussion on the linked issue.

**Closed by devos50** 2017-11-09 09:13 UTC
Labels: bug, needs feedback
