### ISSUE TITLE
Tribler blocking for 30 seconds on startup

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5665] opened 2020-10-21 08:54 UTC
Tribler blocks for almost 30 seconds on startup. Here are the logs
```
[PID:17315] 2020-10-21 10:37:50,945 - INFO - IPv8CommunityLoader(412) - Finished loading communities!
[PID:17300] 2020-10-21 10:37:50,988 - INFO - TriblerGUI(134) - Will connect to events endpoint
[PID:17315] 2020-10-21 10:37:51,012 - INFO - Socks5Connection(97) - Client has sent METHOD REQUEST
[PID:17315] 2020-10-21 10:37:51,016 - INFO - Socks5Connection(179) - Accepting UDP ASSOCIATE request to 127.0.0.1:46859 (BIND addr 0.0.0.0:0)
[PID:17315] 2020-10-21 10:38:19,650 - INFO - TorrentChecker(133) - Selected 10 new torrents to check on tracker: http://<some tracker>/announce.php
[PID:17315] 2020-10-21 10:38:19,774 - INFO - TrustChainCommunity(462) - Requesting crawl of node b'<some hex id>' (blocks 9 to 9) with id 30378
[PID:17315] 2020-10-21 10:38:19,776 - INFO - TrustChainCommunity(462) - Requesting crawl of node b'<some hex id>' (blocks 9 to 9) with id 17487
```

Time between accepting UDP associate request and torrent checking is almost always 30 seconds.

Test machine: Ubuntu 20.04
Branch: Devel

**Comment by qstokkink** [comment] 2020-10-21 08:58
Could you `Ctrl+C` if you detect this again, to see what code it is stuck in?

**Comment by xoriole** [comment] 2020-10-21 11:20
Sure, will do that when it occurs next time.

For comparison, here are the logs for normal non-blocking execution
```
[PID:21867] 2020-10-21 13:17:32,088 - INFO - IPv8CommunityLoader(412) - Finished loading communities!
[PID:21867] 2020-10-21 13:17:32,153 - INFO - Socks5Connection(97) - Client has sent METHOD REQUEST
[PID:21867] 2020-10-21 13:17:32,156 - INFO - Socks5Connection(179) - Accepting UDP ASSOCIATE request to 127.0.0.1:53471 (BIND addr 0.0.0.0:0)
[PID:21867] 2020-10-21 13:17:33,012 - INFO - TriblerTunnelCommunity(252) - Creating a new circuit of length 1 (type: DATA)
[PID:21867] 2020-10-21 13:17:33,012 - INFO - TriblerTunnelCommunity(277) - First hop is required exit
[PID:21867] 2020-10-21 13:17:33,012 - INFO - TriblerTunnelCommunity(310) - Adding first hop <some ip address>:35035 to circuit 911995810
[PID:21867] 2020-10-21 13:17:33,614 - INFO - TrustChainCommunity(462) - Requesting crawl of node b'<some hex id>' (blocks 8 to 8) with id 23938
[PID:21867] 2020-10-21 13:17:33,620 - INFO - TrustChainCommunity(462) - Requesting crawl of node b'<some hex id>' (blocks 4 to 4) with id 32507
```

**Comment by ichorid** [comment] 2020-10-22 09:47
Duplicate of #5602

**Closed** 2020-10-22 09:47 UTC
Labels: bug, performance
