### ISSUE TITLE
Distribute using Flatpak

### ISSUE THREAD

**Issue by Eonfge** [Tribler/tribler#4938] opened 2019-11-06 20:21 UTC
# Intro
Flatpak is a framework for distributing desktop applications on Linux. It has been created by developers who have a long history of working on the Linux desktop, and is run as an independent open source project.

It allows you to package all required libraries into one file, which can also share dependencies using a versioned runtime. It offers sandboxing, atomic updates, and more state of the art technology. It also seamlessly integrates with any number of software centers and repositories, so that users stay up-to-date at all time. All of these things are essential for an application like Tribler, which has security responsibilities to its users.

[Introduction: Reasons to use Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak)

# Why not Snap?
I noticed that you already support Snap (#4240), and it's true that Snap shares many technical ideas behind Flatpak. But there is one fundamental reason why I would propose switching from packaging system:

**You are building a decentralized communication platform... tied to a centralized, close sourced, store front.**

Snap is made by Canonical, and one of the most fundamental design decisions in their ecosystem, is that there is only one store: Canonical's. This is nice for them as they can provide all kinds of benefits on Ubuntu, but it also carries a heavy risk: A government request to remove an app, would instantly cut out any method of distribution. This is becoming a more serious risk, as software companies like Apple, Google and Microsoft are now routinely removing applications for political motives. If Canonical must choose between Tribler or their Chinese marketshare... then Tribler is out.

As such, tools like [OnionShare](https://github.com/micahflee/onionshare/issues/910) and [Tor Browser Downloader](https://flathub.org/apps/details/com.github.micahflee.torbrowser-launcher) have opted to use flatpak instead. It guarantees that in the event of a power struggle, they can easily host their own repository without conflicting financial and moral interests.

I've previously aided in packaging applications for Flatpak, so I might be able to help if I got time. Until the, I wish to propose this change to you for future Linux distributions.

**Comment by xoriole** [comment] 2019-11-07 10:32
In an attempt to build a platform and dependency independent package for Tribler, we opted for snap earlier but we find Flatpak equally interesting with its own set of benefits. For us, the priority at the moment is to make a stable 7.4.0 release then we can look into a Flatpak build but we would gladly welcome any contributions toward creating a nice Flatpak package anytime for Tribler :+1:

**Comment by mehlon** [comment] 2020-03-17 13:23
There's also [Nix](http://nixos.org/nix) and [Guix](http://guix.gnu.org) which are functional package and configuration managers and build systems focusing on reproducible builds, you can install them on top of any existing distribution. 
Guix has previously been used solely as a build system for reproducibly building Bitcoin https://github.com/bitcoin/bitcoin/pull/15277
There's already a Nix package in the 'unstable' channel which you can install with `nix-env -iA nixpkgs.tribler`

**Comment by LongJohn-Silver** [comment] 2020-10-02 16:33
Commenting to continue to support the idea, since Trible reached version 7.4.0 some time ago. Also, although I think Nix and Guix are good, too, flatpak is much more ubiquitous as of now.

**Comment by damnms** [comment] 2020-11-16 14:05
running fedora, i have no tribler because only a .deb is provided - thats bad :(

**Comment by LongJohn-Silver** [comment] 2020-11-16 16:41
It would be nice to have a reply from the maintainers.

**Comment by mariusa** [comment] 2021-02-27 10:21
+1 for AppImage, to be able to run this on Fedora too

**Comment by bam80** [comment] 2021-02-27 11:52
> For us, the priority at the moment is to make a stable 7.4.0 release then we can look into a Flatpak build

@xoriole Has anything changed since then?

**Comment by overflw** [comment] 2021-04-04 22:31
I created a [flatpak](https://github.com/overflw/org.Tribler.tribler) and could try to submit it to flathub. What do you think about it? Do you have any objections?

**Comment by Eonfge** [comment] 2021-04-05 07:09
Hey @overflw 

I'm no official maintainer at Flathub, but I can help you prepare for it.

### Submission process
- First, you'll have to fork the flathub/flathub repository and you must make a new branched called `org.tribler.Tribler` from the new-pr tag. This all sounds a bit weird but Flathub uses Github Actions to trigger builds so some workarounds are required. See the other submission requests here: https://github.com/flathub/flathub/pulls
- Second, you must explain to the maintainers why you don't compile the package from source. It might be unreasonably complex, but you'll have to mention so in advance because. Some other open source applications, like GIMP or ET Legacy, don't compile from source because of some upstream troubles, but they had to explain so.

### File details
- line 49, you don't need  the post-install actions. There are special key-words in the spec: `rename-desktop-file` and `rename-icon`. This means that the renames on line 23 are also not necessary. I would recommend using the build-in methods instead so that it's easier to update once Triblr adopts the [AppStream Standard](https://www.freedesktop.org/software/appstream/docs/). 


### Example 
My latest manifest, so you can see some of these things in action:
https://github.com/flathub/com.etlegacy.ETLegacy/blob/master/com.etlegacy.ETLegacy.yaml

In it, I don't compile from source, I bundle 32bit libraries because of backwards compatibility, and I rename the icon.

**Comment by overflw** [comment] 2021-04-05 10:20
Hey @Eonfge (: Thanks for reaching out! 

I tried to use the `rename-desktop-file` key-word but couldn't make it work for my case unfortunately. But at least `rename-appdata-file` is now used. I'll follow the submission procedure described by you and also [here](https://github.com/flathub/flathub/wiki/App-Submission) by the flathub floks.
Thanks again for the examples and the hints!

Let's see what they say.

**Comment by overflw** [comment] 2021-04-06 09:47
Would somebody from tribler be interested to co-maintain their app on Flathub?

**Comment by synctext** [comment] 2021-04-06 17:07
Yes, great contribution!
At the moment we're still focussed on expanding our user base, privacy, and features.

**Comment by overflw** [comment] 2021-04-06 17:26
Cool! I think the flathub distribution could be very helpful to expand your user base. So I would propose you @synctext as co-maintainer for the flathub repo?

**Comment by LongJohn-Silver** [comment] 2021-04-07 02:01
@overflw I agree, a lot of people would start using it if it is on Flathub plus more peoplr would use it if it is easier for them to install.

**Comment by overflw** [comment] 2021-04-07 09:15
Using the flatpak, I don't have access to video-streaming, is this normally included in the .deb?
And the Trust Graph only seems to work when the application has full home directory access, limiting it to `.Tribler` doesn't seem to be enough, can somebody explain or provide a pointer why?

**Comment by synctext** [comment] 2021-04-07 10:30
@xoriole can help as the official Tribler lab member with @overflw for co-maintaining this flathub repo. Big worry from our side is the active campaign to get malware and crypto mining into various software packages. Great to have more options for users to install Tribler. :+1:

**Comment by overflw** [comment] 2021-04-07 11:52
Thanks for contacting @xoriole - great to have him on board. (Hi there!)

Concerning your worries, it's always good to be vigilant - the flatpak build process is quite transparent and really doesn't do much apart from transferring your .deb into the flatpak file structure.

**Comment by overflw** [comment] 2021-04-07 22:17
I'm having trouble to make triblers streaming capabilities work, apart from that the flatpak does its job. Do you have a pointer what I could be missing? Even on a clean ubuntu20.10 with vlc present, installing tribler via the deb won't give me the streaming options in the gui.
If there is no fix, I would call it a day and propose the flatpak in its current state.

**Comment by qstokkink** [comment] 2021-04-08 06:10
@overflw There is no fix, the feature was removed in https://github.com/Tribler/tribler/pull/5549

**Comment by overflw** [comment] 2021-04-08 14:34
https://github.com/flathub/flathub/pull/2236#discussion_r609462023
Is there any movement to adopt [AppStream](https://www.freedesktop.org/software/appstream/docs/) metadata for Tribler?

**Comment by qstokkink** [comment] 2021-04-08 14:52
If I understand the linked comment correctly, support for AppStream is a single xml file. @overflw is that correct?

In that case, we could simply follow the `snap` folder structure ([`Tribler/build/debian/snap/`](https://github.com/Tribler/tribler/tree/main/build/debian/snap)) and put this file in `Tribler/build/debian/flatpak/` or `Tribler/build/debian/flathub/`. @xoriole any objections/suggestions?

**Comment by xoriole** [comment] 2021-04-08 15:24
@overflw Thank you for your contribution. Greatly appreciated 👍 
@qstokkink No objections. I agree  `Tribler/build/debian/flatpak` is the right place. Basically the PR content and any related files can go to that directory.

**Comment by overflw** [comment] 2021-04-08 15:46
> If I understand the linked comment correctly, support for AppStream is a single xml file. @overflw is that correct?

That's how I understand it too. Would be usefull to have the [metainfo.xml](https://github.com/overflw/flathub/blob/org.tribler.Tribler/org.tribler.Tribler.metainfo.xml) also in the deb - making for a nicer integration for software centers like gnome-software ect.

**Comment by bam80** [comment] 2021-04-08 15:58
> the flatpak build process is quite transparent and really doesn't do much apart from transferring your .deb into the flatpak file structure

Is it right way to go? Can't we build it from scratch in flatpak-builder instead?

**Comment by Eonfge** [comment] 2021-04-08 18:52
> > the flatpak build process is quite transparent and really doesn't do much apart from transferring your .deb into the flatpak file structure
> 
> Is it right way to go? Can't we build it from scratch in flatpak-builder instead?

It's preferred to build from source, but it's not a hard requirement. I maintain packages who are build from source, and a few who are not.

As for the metainfo.xml, the icons and everything else called `org.tribler.Tribler`: They are all part of the App Stream standard that is generally respected by all Linux distributions. GNOME Software and KDE Discover both use it for their metadata, application details and age restrictions. If Tribler were to adopt he appstream standard, which means that the existing .desktop, then that would benefit all Linux distributions.

**Comment by qstokkink** [comment] 2021-04-09 07:23
@overflw do you want to shoulder the responsibility of turning this into a pull request on our repo?

**Comment by overflw** [comment] 2021-04-09 15:21
> @overflw do you want to shoulder the responsibility of turning this into a pull request on our repo?

I can look into it, but not before the end of next week unfortunately.

**Comment by hraisins** [comment] 2021-04-29 09:59
https://github.com/overflw/flathub/pull/1

**Comment by overflw** [comment] 2021-05-10 11:57
At least the deb based version is on flathub now :)
https://flathub.org/apps/details/org.tribler.Tribler

**Comment by Dmole** [comment] 2021-06-12 00:08
On Fedora Tribler from FlatHub will run but won't show torrents in the open dialog and will ignore the watch folder.

**Comment by qstokkink** [comment] 2024-09-19 13:14
Considering Tribler is published to flathub, I guess this issue is now resolved.

**Closed by qstokkink** 2024-09-19 13:14 UTC
Labels: type: enhancement, component: platforms and packaging
