### ISSUE TITLE
Sub channels do not show up in search results

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5298] opened 2020-04-22 09:22 UTC
Steps to reproduce: create a new (root) channel and in that root channel, create a sub channel and rename it to X. Now, when searching for X, it does not show up in the search results. I am sure the channel is committed.

Is this expected?

**Comment by ichorid** [comment] 2020-05-14 07:41
latest 7.5 release branch, can't reproduce this. Sub-channels are perfectly searchable, so closing this one.

**Closed by ichorid** 2020-05-14 07:41 UTC
Labels: enhancement
