### ISSUE TITLE
Channel sync progress bars aren't updated without restart

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#7289] opened 2023-02-10 02:49 UTC
**Describe the bug**

**To Reproduce**
1.Subscribe to a channel with a lot of entries.
2. Wait for some time
3. Restart tribler.
**Expected behavior**
Channel sync progress bars are updated without need for restart.
**Screenshots**
![image](https://user-images.githubusercontent.com/8822292/217987779-276cfd17-cc74-4224-8dd8-5a87e3e15def.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tribler's version [e.g. 7.12.1

**Additional context**

**Comment by ichorid** [comment] 2023-02-11 18:38
Confirmed in 7.12.1, can't reproduce in current `main`. RC for 7.13 is around the corner, so it should be fixed there

**Closed by ichorid** 2023-02-11 18:38 UTC
Labels: type: bug
