### ISSUE TITLE
'NoneType' object has no attribute 'address'

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4822] opened 2019-09-08 17:52 UTC
Saw this one in the error reporter:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'address'
lib\threading.py:801:__bootstrap_inner
lib\threading.py:754:run
lib\site-packages\twisted\_threads\_threadworker.py:46:work
lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
lib\site-packages\twisted\python\threadpool.py:250:inContext
lib\site-packages\twisted\python\threadpool.py:266:<lambda>
lib\site-packages\twisted\python\context.py:122:callWithContext
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:573:sesscb_states_callback
Tribler\community\triblertunnel\community.py:501:monitor_downloads
Tribler\community\triblertunnel\community.py:531:create_introduction_point
ipv8\messaging\anonymization\hidden_services.py:479:create_introduction_point
ipv8\messaging\anonymization\hidden_services.py:171:create_circuit_for_infohash
ipv8\messaging\anonymization\community.py:315:create_circuit
]
```

**Comment by qstokkink** [comment] 2019-09-09 08:22
Seems to be a duplicate of #4644. What version of Tribler is this?

**Comment by egbertbouman** [comment] 2019-09-11 23:09
Looks like a threading issue. I'll fix this in IPv8.

**Closed** 2019-09-18 17:21 UTC
Labels: bug
