### ISSUE TITLE
AllChannels V2.0

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#705] opened 2014-07-24 11:10 UTC
ToDo:
- New community identifier
- Public key inclusion enabled
- Cancel message enabled
- Disable (recursive)-Undo capability 

Crawl and re-insert all votes and channels. ~~Perhaps move from a pre-fix towards a post-fix. To facilitate improved scalability through decay.~~ See remarks below by Niels

We now do 94672 outgoing messages per hour (a few per second). 
![tribler_6 4pre_allchannel_94672_outgoing_packets_per_hour](https://cloud.githubusercontent.com/assets/325224/5366339/450df1e4-7ff3-11e4-991b-218a91392472.png)

**Comment by devos50** [comment] 2016-03-18 11:28
@whirm maybe move this milestone to V6.6+?

**Comment by whirm** [comment] 2016-03-18 11:31
@devos50 I guess,

@synctext ?

**Comment by qstokkink** [comment] 2018-07-25 14:39
Duplicate of #3615 .

**Comment by ichorid** [comment] 2019-02-23 17:03
Duplicate of #3615

**Closed by ichorid** 2019-02-23 17:03 UTC
Labels: AllChannel 2.0, duplicate, enhancement
