### ISSUE TITLE
Tribler downloads reducing to zero after few hours

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3946] opened 2018-10-08 09:06 UTC
In Mac, it is observed that the download speed on some torrents gradually decreases over time and reduces to zero bytes/second. It could be an issue with how we are using libtorrent but we need to do a thorough debugging to fix this.

**Comment by devos50** [comment] 2018-10-08 09:40
Duplicate of #3379

**Closed by devos50** 2018-10-08 09:40 UTC
Labels: bug
