### ISSUE TITLE
Tribler should always check both unwanted and usual file location when initializing and download

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2605] opened 2016-10-30 19:18 UTC
##### Tribler version/branch+revision:

Merged 2a582f51e471d4eacff2bf4f991141e50a0747f2 and fcb17a806e3d6f47447987a8e4c7d115164404e8, qt-gui branch
##### Operating system and version:

Linux Debian
##### Steps to reproduce the behavior:
1. Make some Tribler download
2. Include/exclude files
3. Tribler moves file to and fro between `.unwanted` and usual file name
4. Something crashes.
5. Decision to include or exclude a file in a download and actual placement of the file are out of sync.
##### Expected behavior:

When initializing a torrent or doing "Force recheck", Tribler looks for both possible locations (included or excluded) of the file and makes them sync (changing includedness to match filename or moving the file to match includedness)
##### Actual behavior:

Failing to find the file in expected location, Tribler downloads everything again (like if the file is missing).

**Comment by devos50** [comment] 2017-01-04 11:39
I've tried to reproduce the reported behaviour, however, in my latest PR #2691 this is working for me (I've forced a crash after including/excluding a download). Can you also verify this please?

**Comment by vi** [comment] 2017-01-04 11:44
Was the decision to include or exclude file (stored in a database?) and file placement out of sync?

**Comment by devos50** [comment] 2017-01-04 11:47
Actually, the file placement worked correctly, however, prioritising of the files by the download engine did not work correctly due to a bug in an if-statement.

**Comment by vi** [comment] 2017-01-04 11:52
I'll check what happens if one manually moves file to/from `.unwanted` while Tribler is stopped, in #2691 version.

**Comment by vi** [comment] 2017-01-04 13:13
After switching from devel to #2691 (b97f36e310db0f3206148f673e47e54d8b36f5f1) it is doing global recheck. Is it intended?

**Comment by devos50** [comment] 2017-01-04 13:14
Only if your downloads do not have resume data associated (check the files in `tribler state dir/dlcheckpoints`).

**Comment by vi** [comment] 2017-01-04 13:17
There are files there. But they are all fresh (rechecking is not completed).

Can Tribler sometimes intentionally remove them (e.g. thinking they are corrupted or outdated)?

**Comment by vi** [comment] 2017-01-04 14:31
Determined both filenames (wanted and unwanted), stopped Tribler, moved file from wanted to unwanted, started Tribler.

It rechecks this and 5 more downloads for some reason. It was clean shutdown and no commit change. dlcheckpoints seem to be unreliable in general.

**Comment by vi** [comment] 2017-01-04 14:43
Result: it re-downloads. And re-checks.

Restored file back - again 100%.

Also previously downloaded due to #2566 unwanted files seem to be unavailable (0%) and beging getting downloaded if I include them.

**Comment by vi** [comment] 2017-01-04 14:55
Also "force recheck" seems to ignore unwanted files.

**Comment by devos50** [comment] 2017-01-11 15:59
Including/excluding files is working without problems for me, even when Tribler crashes after changing the selection. The global recheck is a different problem and we already have an issue for it.

Also, I don't think we should support manual movement to and from the `.unwanted` directory.

I will close this issue since the original problem described in the first post is solved in my opinion. Please reopen this issue if it's still not working and I will try again.

**Closed by devos50** 2017-01-11 15:59 UTC
Labels: bug

**Comment by vi** [comment] 2017-01-11 18:36
Another use case for handling `.unwanted` more carefully:

1. User starts Tribler. Downloads drive and Tribler profile drive are separate;
2. User gets some download ready. The download is 100%-downloaded, but there are excluded files (which, although excluded, are actually also downloaded and are available for seeding).
3. System crash. No home directory anymore. Tribler profile lost. No database. But TriblerDownloads survived due to being in another filesystem.
4. User starts Tribler, it creates new profile with the same TriblerDownloads dir
5. User adds the same download (in order to seed it or just manage included/excluded files)
6. Tribler sees content in TriblerDownloads for the newly added download.

Expected:

Tribler also looks into `.unwanted` and either moves them all to wanted or automatically assigned includedness status based on filesystem metadata;

Actual:

Content being re-downloaded despite of already being present in TriblerDownloads (inside `.unwanted`).
