### ISSUE TITLE
sqlite3.OperationalError: unrecognized token

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4786] opened 2019-09-02 05:12 UTC
Version: 7.3.0
Platform: Windows-2008ServerR2-6.1.7601-SP1
Uptime:27.0910000801
Report: [26589](http://reporter.tribler.org/stacktrace/26589)

```python
Aggregate stacktrace (# of reports: 3) More details
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'613...30"
lib\threading.py:801:__bootstrap_inner
lib\threading.py:754:run
lib\site-packages\twisted\_threads\_threadworker.py:46:work
lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
lib\site-packages\twisted\python\threadpool.py:250:inContext
lib\site-packages\twisted\python\threadpool.py:266:<lambda>
lib\site-packages\twisted\python\context.py:122:callWithContext
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:547:sesscb_states_callback
ipv8\database.py:56:wrapper
ipv8\database.py:333:executescript
]
```

**Comment by devos50** [comment] 2019-09-04 10:26
Maybe invoking sqlite from the thread pool is causing issues? I saw another similar error report today.

**Comment by egbertbouman** [comment] 2019-09-14 14:02
I think this might be due to libtorrent not having finished flushing the disk cache. If this happens we will likely end up with an incomplete SQL statement at the end of the bootstrap file, and we get an error similar to this.

**Comment by devos50** [comment] 2019-09-14 17:51
Duplicate of #4757, let's continue the discussion on that issue 👍

**Closed by devos50** 2019-09-14 17:51 UTC
Labels: bug
