### ISSUE TITLE
Mac 8.0.1 freezes (unusable) 

### ISSUE THREAD

**Issue by ballo** [Tribler/tribler#8208] opened 2024-10-13 02:58 UTC
The app freezes so there is no crash. I got as far as adding one torrent before it halted. 

The app appears to be an Intel only binary. I have an M2 Max.

**Comment by qstokkink** [comment] 2024-10-13 07:02
Thanks for the report! The M-series _should_ be backward compatible with Intel binaries. However, I need more information to debug this for you. Could you provide us with debug information by running the `tribler` binary inside of your `.app`?

Running in debug mode should be a matter of opening a terminal and `cd`-ing into the Tribler `.app`. Inside, there should be a `MacOS` directory with a `tribler` executable. Running that `./tribler` in your terminal should start printing debug output.

Ideally, just before crashing, there should be some text that describes a common error `Traceback (most recent call last): ... etc`.

**Comment by synctext** [comment] 2024-10-15 10:12
@ballo Thank you for your report!  We're currently completely blind to where the new 8.0.0 series fails or works. Apologies the new Tribler didn't work for you. Something we need to fix.

@qstokkink there are 3 Mac laptops in the office I believe. Also operational M3 laptops in your office. Can we get regular M2 and/or M3 testing done please?

**Comment by qstokkink** [comment] 2024-10-15 11:53
@synctext I once-in-a-while request experimental Tribler versions to be run on our PhD's laptops, sure. However, I don't think we can do any **automated regular** testing on the work laptops of students, forcing them to keep their laptops online and hooking in a background process that pops the tests into the foreground periodically. Realistically, we would need dedicated hardware for that.

**Comment by qstokkink** [comment] 2024-10-16 13:48
We cannot reproduce this on "our" M2. We will need more information.

**Comment by synctext** [comment] 2024-10-24 07:14
@devos50 has also experienced freezes on Intel Mac (informally reported) :cry: 
So the good news, this is easier to reproduce...

**Comment by qstokkink** [comment] 2024-10-28 08:22
It would be great if someone, who can reproduce this, could terminate the Tribler process during a freeze and post a resulting `Traceback` log.

I know Mac has a tendency to block on `socket.*()` calls and that this is highly dependent on individual network setups. However, this is (a) just pure speculation and (b) who knows how many hundreds of secret `socket` library invocations exist in our dependencies. If we get a traceback that points to the particular blocking call, we have a fighting chance of fixing this. However, until then, we can't resolve this issue.

**Comment by qstokkink** [comment] 2024-10-31 13:48
We actually managed to reproduce the freezes and 150% CPU usage on our Intel Mac on Tribler 8.0.2.

We also found, for our setup at least, that #8231 seems to fix this. In the upcoming Tribler 8.0.3 this should be fixed.

**Closed by qstokkink** 2024-10-31 13:48 UTC
Labels: type: bug
