### ISSUE TITLE
Market module keeps crashing

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#3096] opened 2017-09-14 14:34 UTC
My Tribler client keeps crashing today, reporting the same error.

Traceback (most recent call last):
  File "/home/bohao/tribler/TriblerGUI/event_request_manager.py", line 123, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bohao/tribler/TriblerGUI/core_manager.py", line 105, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1199, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1208, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 801, in runUntilCurrent
    f(*a, **kw)
  File "/home/bohao/tribler/Tribler/dispersy/endpoint.py", line 253, in dispersythread_data_came_in
    u"standalone_ep")
  File "/home/bohao/tribler/Tribler/dispersy/dispersy.py", line 979, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp, source)
  File "/home/bohao/tribler/Tribler/dispersy/community.py", line 2028, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/home/bohao/tribler/Tribler/dispersy/community.py", line 2085, in _on_batch_cache
    messages.append(conversion.decode_message(candidate, packet, source=source))
  File "/home/bohao/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/bohao/tribler/Tribler/dispersy/conversion.py", line 1251, in decode_message
    placeholder.offset, placeholder.payload = decode_functions.payload(placeholder, placeholder.offset, payload)
  File "/home/bohao/tribler/Tribler/community/market/conversion.py", line 180, in _decode_decline_match
    return self._decode_payload(placeholder, offset, data, [TraderId, MessageNumber, Timestamp, str, int])
  File "/home/bohao/tribler/Tribler/community/market/conversion.py", line 110, in _decode_payload
    args.append(payload[cur_ind])
exceptions.IndexError: tuple index out of range

I deleted the .tribler folder but it doesn't help.

**Comment by qstokkink** [comment] 2017-09-14 14:47
Duplicate of #3095, closing this issue.

**Closed by qstokkink** 2017-09-14 14:47 UTC
