### ISSUE TITLE
Backup All Torrent files

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#7283] opened 2023-01-21 12:22 UTC
We are able to export a single file to a torrent from our library, but an export all is not possible.
With testing 7.13 and going back to 7.12 I again lost a lot of files.
Would it be a big challenge to set a download location for Torrents and copy/add them to that location, so we have an automatic backup of all of our added torrent files?

**Comment by drew2a** [comment] 2023-01-23 08:17
@Nubro01 thank you for this request.

Do I understand you correctly, that you suggest the following:

1. A user adds a torrent file to Tribler and specifies the download location
2. Tribler adds the torrent file to this download location

If yes, how do you see the restoring process?

**Comment by Nubro01** [comment] 2023-01-23 09:23
At Options/settings we can specify the location of the files to download, an extra line for a location where to store the actual torrent (with new download location) data is what I mean. I geus you now store that information within the database and not in a special seperate location too.
When you loose the database, as I have already several times over the years, like last weeek when I went from 7.13 back to 7.12 then it would be handy to restore the database from that backup location. With add torrent from directory (already present) would do that. Saving torrents manually while searching the internet and adding them to Tribler, is also a way, but most Torrent names have meaningles names.

**Comment by qstokkink** [comment] 2024-10-14 12:25
If I understand this issue correctly, this is a duplicate of #5591. I'll close this issue to reduce duplication in our issue tracker. However, this functionality is on our radar for Tribler 8.1.

**Closed by qstokkink** 2024-10-14 12:25 UTC
Labels: type: enhancement
