### ISSUE TITLE
Update python version to `3.9`

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7869] opened 2024-01-30 07:41 UTC
To complete the task, we should:
- [x] Update all builders (@xoriole).
  - [x] macOS
  - [x] Linux
  - [x] Win64
  - [x] Win32
- [x] Update GitHub actions (@drew2a).
- [x] Update documentation (@drew2a).

Ref:
- #7867

**Comment by xoriole** [comment] 2024-01-30 14:47
I have opted to use `pyenv` for setting up the python environment and updated the Jenkins script to use the correct python using pyenv local setup. So far, macOS and Linux builders are updated and the build seems to work too. But, Windows installation seems a bit challenging.

**Comment by drew2a** [comment] 2024-01-31 05:26
For Windows, you might consider using Chocolatey as it may simplify things: [Python 3.9 on Chocolatey](https://community.chocolatey.org/packages/python39).

**Comment by xoriole** [comment] 2024-02-01 12:41
The reason why Python3.9 was not working on our builders is because Python3.9 is not supported on Win7. Therefore, the windows builders need to be upgraded. This will likely affect some users using Win7 still.

I'll upgrade the builders on Win10 machines.

Ref: https://bugs.python.org/issue41412

**Comment by xoriole** [comment] 2024-02-01 14:11
Priority for upgrading the builders is put on hold until the existing bugs are fixed.
I'm unassigning myself till it becomes a priority again.

**Comment by drew2a** [comment] 2024-02-01 14:36
@xoriole, "until the existing bugs are fixed" does sound a bit like "never"...

It seems like I should revert the changes I made to GitHub Actions because now it's possible that one of the developers will use a feature from Python `3.9`, which will pass all the tests in a PR as they operate with Python `3.9`. However, when we try to build the next release (for example, `7.14`), we might encounter these incompatibilities since the builders use Python `3.8`.

**Comment by drew2a** [comment] 2024-03-27 13:23
@xoriole the issue you mentioned is fixed:
 - https://github.com/python/cpython/issues/85584

**Comment by xoriole** [comment] 2024-05-24 09:55
Update on this ticket: 
Windows 64bit builder machine is upgraded to support Python3.9. This was used to build the TriblerExperimental release (win64) yesterday.

A few notes:
- The builder is on Win10. The build created on Win10 does not work on Win7 (tested and confirmed).
- The same build script that worked on Win7 did not work on Win10, requiring changes. Those changes on the build script are currently on TriblerExperimental and need to be imported back to Tribler main.

**Comment by qstokkink** [comment] 2024-08-12 08:07
TriblerExperimental is now Tribler main, resolving this issue.

**Closed by qstokkink** 2024-08-12 08:07 UTC
Labels: type: enhancement
