### ISSUE TITLE
SSL for Windows Dev Env

### ISSUE THREAD

**Issue by intel478** [Tribler/tribler#1759] opened 2015-12-01 16:29 UTC
Following the steps from https://github.com/Tribler/tribler/blob/devel/doc/Tribler%20development%20on%20Windows.md#running-tribler
```
E:\Dev\Tribler>python Tribler\Main\tribler.py
OPENSSL_Uplink(00007FFBFC362000,08): no OPENSSL_Applink
```
*Possible solution?* https://github.com/Tribler/tribler/issues/1671#issuecomment-143032132

**Comment by devos50** [comment] 2015-12-01 17:10
This was caused by an issue in `M2Crypto`. You should update your local git submodule pointer of `dispersy`. See https://github.com/Tribler/dispersy/pull/458 and https://github.com/Tribler/tribler/pull/1731 for more information about this issue.

**Comment by intel478** [comment] 2015-12-01 19:46
Done, but error remains.
```
Subproject commit 6d59deefcd047138174d8a2da1339f3a71f14d00
Subproject commit ab39486c5572c1e613ea5d8a5fcac9d61d56f802
```

**Comment by devos50** [comment] 2015-12-01 19:49
You also have the solution to issue #1731 merged in your project?

**Comment by intel478** [comment] 2015-12-02 21:34
Cherry picked cd544998eb6de40bfa554bb2e284d8ce890a6a8c

**Comment by whirm** [comment] 2015-12-03 10:46
Can this be closed?

**Closed** 2015-12-03 11:53 UTC
Labels: question
