### ISSUE TITLE
Trustchain daily transaction volume crawler and real-time visualisation 

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3318] opened 2017-12-27 15:48 UTC
Compare Trustchain / IPv8 overlay live network. (only needed once we have usage). great network health monitoring tool.

Create live crawler with key metric for scientific publication. Create a graph of past years volume of Bitcoin, Etereum and possibly IOTA. Add our discovered transactions, half blocks, unique seen nodes, and daily active nodes.

Include pictures like:
https://pbs.twimg.com/media/DADx-06XYAETHSc?format=jpg

**Comment by devos50** [comment] 2017-12-28 09:39
A Trustchain block explorer would also be very cool to have, something like https://blockexplorer.com and https://cardanoexplorer.com.

**Comment by qstokkink** [comment] 2018-01-03 08:51
Storing all of the chains of the entire network will come at a significant resource cost though, also CPU-wise. We will need a beefy server to handle this.

**Comment by devos50** [comment] 2018-03-22 14:56
Duplicate of #3508

**Closed by devos50** 2018-03-22 14:56 UTC
Labels: enhancement, infrastructure
