### ISSUE TITLE
Tribler breaks with: OSError: Unable to obtain adapter information.

### ISSUE THREAD

**Issue by nosuch17** [Tribler/tribler#2049] opened 2016-03-21 18:48 UTC
- [x ] I have read CONTRIBUTING.md

- [x ] I have tried with the latest pre-release version and I still can reproduce the issue.

Tribler version/branch+revision: 6.5.1

Operating system and version: windows 8.1 x64

Expected behavior: Download a file via magnet link or torrent file and clean exit.

Actual behavior: After adding a magnet link or torrent file all that happens is: "Building circuits" and port status unknown. At exit an error is created and a logfile is written.

Steps to reproduce the behavior: See above.

Relevant log file output: 
```
ERROR   1458515290.56        dispersy:214   failed to check network interfaces.
Traceback (most recent call last):
  File "Tribler\dispersy\dispersy.pyo", line 195, in _get_interface_addresses
OSError: Unable to obtain adapter information.
ERROR   1458515290.56        dispersy:238   Unable to find our public interface!
```

**Comment by lfdversluis** [comment] 2016-03-22 14:24
Thanks for the report, we will take a look at it. :+1:

**Comment by pimveldhuisen** [comment] 2016-04-04 16:19
I've taken a look at this and it seems the problem is in the netifaces library we use.
(https://pypi.python.org/pypi/netifaces)
The "Unable to obtain adapter information." error is generated by this library and seems to be a rather catch-all type error that does not provide a lot of info.
We recently added a catch for this exception (https://github.com/Tribler/dispersy/pull/449), but catching it obviously does not solve the problem, as this makes Tribler nonfunctional. 
The bug also seems to affect other users: http://forum.tribler.org/t/tribler-6-5-1-stuck-building-circuits-port-status-unknown/3439

**Comment by whirm** [comment] 2016-04-08 11:31
@nosuch17 Are you running anything network related that you think is worth mentioning? (firewall, antivirus, VPN...)

**Comment by nosuch17** [comment] 2016-04-10 12:25
No Firewall, Panda Free Antivirus, OpenVPN GUI installed a TAP Windows Adapter V9

**Comment by lfdversluis** [comment] 2016-04-10 12:31
That TAP Windows Adapter sounds interesting. Could you try disabling it and see if you still experience the error? It could be that the library has trouble finding such an adapter.

**Comment by whirm** [comment] 2016-04-11 10:00
@lfdversluis do you want to take care of this one?

**Comment by lfdversluis** [comment] 2016-04-11 10:19
@whirm @pimveldhuisen is looking into it. He also figured out it was netifaces.

**Comment by pimveldhuisen** [comment] 2016-04-11 12:28
It seems that the VPN is the source of the problem here. I can somewhat replicate the problem on my Windows machine with it a VPN, in the sense that anonymous torrents do get stuck on 'building circuits' , although I do not get a crash report.

I think fixing it will be non-trivial however, I reckon routing traffic through a VPN is a scenario that is not really considered in the tunnel community code. I will take a look though.

**Comment by whirm** [comment] 2016-04-11 12:40
@pimveldhuisen are you getting the netifaces error?

**Comment by nosuch17** [comment] 2016-04-11 18:46
OK, little update.
I disabled the TAP adapter - no change
I uninstalled OpenVPN so that the TAP is also gone - no change
i disabled every network adapter but the actual wifi - no change

**Comment by whirm** [comment] 2016-04-12 10:03
@nosuch17 Do you have any extra/manual network config? I couldn't break Tribler by installing OpenVPN, so I'll install Panda too

**Comment by whirm** [comment] 2016-04-12 12:29
@nosuch17 Panda completely kills Tribler for me: It will start, but the second I click a download, Tribler will stop responding. If I uninstall Panda,  it goes back to working fine without even having to reboot.

I'll try to see if the same happens with other antiviruses.

**Comment by whirm** [comment] 2016-04-12 12:46
@nosuch17 nod 32 works perfectly fine

**Comment by whirm** [comment] 2016-04-12 13:21
@nosuch17 avast also works fine. 

Can you uninstall Panda and see if Tribler works for you?

**Comment by whirm** [comment] 2016-04-12 14:51
@pimveldhuisen You go on with the netifaces error, I'll just wait for the feedback re. Panda but won't be doing any more work on the netifaces stuff.

**Comment by nosuch17** [comment] 2016-04-12 19:28
I uninstalled Panda, it didn't help.
I uninstalled Wireshark and winpcap and that didn't help also.
I have resetted winsock with no effect.
But now when i run tribler my whole windows is very sluggish, i am about to give up ...

**Comment by whirm** [comment] 2016-04-13 09:37
I've tested it on both windows 10 and 8.1 and I'm having no issues whatsoever.

Do you have any other windows 8.1 available to test?

Are you running a non-english version of windows?

**Comment by whirm** [comment] 2016-04-13 09:37
@pimveldhuisen all yours.

**Comment by nosuch17** [comment] 2016-04-13 21:22
i do not think i have any other 8.1 around (or friends)
Well, non-english version, i am located in germany and the windows gui is in english but keyboard is german, so ...

**Comment by pimveldhuisen** [comment] 2016-04-14 15:07
@nosuch17 I've tried running Tribler with VPN and or Wireshark/winpcap, but I can't seem to reproduce your error.

Could you copy the output of running "ipconfig /all" in cmd ?

**Comment by nosuch17** [comment] 2016-04-14 17:21
![untitled-1](https://cloud.githubusercontent.com/assets/17990409/14537115/ebb6af80-0275-11e6-9e73-da1eb59982c9.png)

**Comment by whirm** [comment] 2016-04-22 07:54
@pimveldhuisen we are pretty close to releaseing 6.5.2, and it looks like this will be the last issue left. Could you focus on fixing this so we can free `next` for 6.6?

**Comment by synctext** [comment] 2016-04-22 08:32
close to release.. good news. This looks like quite a specific bug or incompatibility. We could work on it further and not let it slow the bugfix release.

**Comment by pimveldhuisen** [comment] 2016-04-23 15:35
@whirm I would love to fix this but at the moment I wouldn't really now how to proceed, since we/I still can't reproduce the issue. However, if I understand Laurens correctly #2213 is supposed to fix this? (I haven't had a chance to talk to him about this)

**Comment by whirm** [comment] 2016-04-25 10:14
@pimveldhuisen nope, that will (hopefully) fix a different issue where netifaces was missing some DLLs.

**Comment by whirm** [comment] 2016-04-25 10:16
@pimveldhuisen I guess you tested that with a wifi-connected laptop, right? (in case netifaces has a hard time dealing with wifi devices for some reason) I only tried with with a desktop machine.

**Comment by whirm** [comment] 2016-04-25 10:17
If we haven't found a way to fix this before v6.5.2 release time, I'll move it to the v6.6 milestone as indicated by @synctext.

**Comment by whirm** [comment] 2016-04-26 11:44
Quick update: @pimveldhuisen thought of a fallback that should work when netifaces fails to obtain the necessary info. We will be providing a build here and on the forum thread to make sure it solves the issue and release 6.5.2 with it if it does.

**Comment by whirm** [comment] 2016-04-26 11:45
@pimveldhuisen this is the last issue pending for v6.5.2, so it would be great if you gave priority to it.

**Comment by whirm** [comment] 2016-04-28 13:24
@nosuch17 could you please test this build and tell us if it solves the issue for you?

https://jenkins.tribler.org/job/Build_Tribler_next/11/artifact/

Thanks!

**Comment by nosuch17** [comment] 2016-05-01 13:26
Unfortunatly it does not help.
Logfile attached. @
[tribler.exe.log.txt](https://github.com/Tribler/tribler/files/244118/tribler.exe.log.txt)

**Comment by whirm** [comment] 2016-05-02 12:45
Well, it does help, but we are hitting a different issue now.

Could you shut down Tribler, go to Tribler's install dir, then to `Tribler\dispersy\`, delete `conversion.pyo` and `payload.pyo` and unzip the attached archive there?

The next time you start Tribler you should get more info on the log file, please paste it so I can have a look.

Thanks!
[files.zip](https://github.com/Tribler/tribler/files/245040/files.zip)

**Comment by nosuch17** [comment] 2016-05-02 19:14
OK, here is the log:
[tribler.exe.log.txt](https://github.com/Tribler/tribler/files/245739/tribler.exe.log.txt)

**Comment by whirm** [comment] 2016-05-03 08:31
Perfect, thanks!

Could you delete `conversion.py`, `conversion.pyc`, `payload.py`, `payload.pyc` and unzip the contents of the updated link on the previous comment? (files2.zip)

**Comment by nosuch17** [comment] 2016-05-04 18:47
OK, since there are no *.pyc files i made the assumption *.pyo was meant and deleted them accordingly.
Again here's the log:
[tribler.exe.log.txt](https://github.com/Tribler/tribler/files/249380/tribler.exe.log.txt)

**Comment by whirm** [comment] 2016-05-10 11:20
@nosuch17 sorry for the delay, This version should hopefully work for you: 

https://jenkins.tribler.org/job/Build_Tribler_next/14/

Could you please give it a go?

**Comment by nosuch17** [comment] 2016-05-10 19:25
I am sorry to report that it still doesn't work for me.
[tribler.exe.log.txt](https://github.com/Tribler/tribler/files/257926/tribler.exe.log.txt)

**Comment by whirm** [comment] 2016-05-11 09:56
@nosuch17 amazing :D I'll set some stuff up and come back to you. ASAP, Could you connect to the IRC channel? (see the main README)

**Comment by nosuch17** [comment] 2016-05-11 19:43
I've parked my client there

**Comment by whirm** [comment] 2016-05-12 15:35
This build contains a bunch of debug info that should help me nail the issue:

https://jenkins.tribler.org/job/pers/job/Build_Tribler_6.5_builder_emilon/11/

Could you run Tribler for a bit and attach the log file again?

Thanks!

**Comment by nosuch17** [comment] 2016-05-12 20:32
Alright, this time it worked !
Tribler is downloading, however on exit it creates an error and here is the log:
[Tribler.exe.log.txt](https://github.com/Tribler/tribler/files/262203/Tribler.exe.log.txt)

**Comment by synctext** [comment] 2016-05-13 06:45
yet another error.. Many thanks again. This is highest priority for the Tribler team, as this is the last bugfix we need to take care of.

**Comment by whirm** [comment] 2016-05-13 07:08
@nosuch17 by error you mean it shows a popup saying there was an error right? That's because debugging info has been written to the log.

I'll clean up the fixes and release 6.5.2! 
Again, thank a lot!

**Comment by devos50** [comment] 2016-05-13 08:43
@nosuch17 Thanks for your help!

**Comment by whirm** [comment] 2016-05-13 10:13
Fixed in `next`

**Closed** 2016-05-13 10:13 UTC
Labels: bug, _Top Priority_

**Comment by nosuch17** [comment] 2016-05-13 16:04
no, i have to thank you guys, you made the program work for me ;)

@whirm yes about the popup.
