### ISSUE TITLE
v6.5.0-rc6 Can't find my own torrents using Search

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1716] opened 2015-11-09 11:23 UTC
Typically (i.e. in v6.4.3) as soon as I add a torrent using "Download an external torrent" feature, it immediately becomes searchable in global search.

In v6.5.0-rc6 hovewer I can't find my downloads beeing seeded no matter what keywords I do try.

**Comment by whirm** [comment] 2015-11-23 14:37
Seems to be working fine for me:
![2015-11-23-153100_3120x1920_scrot](https://cloud.githubusercontent.com/assets/529494/11339096/13e36d84-91f8-11e5-9b73-89f6d97ca04b.png)
![2015-11-23-153110_3120x1920_scrot](https://cloud.githubusercontent.com/assets/529494/11339097/13e3dc60-91f8-11e5-90b5-06bf7583fbb1.png)

**Comment by whirm** [comment] 2015-12-30 13:35
@vi Could you provide more info on how to reproduce this? 

Thanks!

**Comment by vi** [comment] 2015-12-30 13:42
What is the best way to reproduce this?

Create a torrent with unique-ish keywords myself and check if it shows up in search?

**Comment by whirm** [comment] 2015-12-30 14:38
I really don't know as it works fine for me :/

**Comment by whirm** [comment] 2015-12-30 14:39
Have you tried moving `.Tribler` away just in case?

**Comment by vi** [comment] 2015-12-30 16:38
I already have multiple `.Tribler` backups... Maybe can create another one...

How do I create entirely new torrent with Tribler?

**Comment by whirm** [comment] 2015-12-30 16:45
You need to create your own channel, and then the channel gui will be available and there's a button there to create torrents.

**Comment by vi** [comment] 2015-12-30 21:40
Created a torrent with Tribler's `README.md` file. It says `Please wait while Tribler is creating your .torrents. Please wait while Tribler is creating your .torrents.` with a stuck fake progress bar. UI is blocked now...

**Comment by vi** [comment] 2015-12-30 21:43
Second attempt: it no stuck UI, also no error messages or new torrents in my channel. Console message:

```
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Main/Dialogs/CreateTorrentDialog.py", line 248, in create_torrents
    create_torrent_file(self.selectedPaths, params, self._torrentCreated)
  File "/home/vi/home/tribler/tribler/Tribler/Core/Utilities/torrent_utils.py", line 35, in create_torrent_file
    torrent.set_comment(params['comment'])
ArgumentError: Python argument types in
    create_torrent.set_comment(create_torrent, unicode)
did not match C++ signature:
    set_comment(libtorrent::create_torrent {lvalue}, char const*)
```

**Comment by vi** [comment] 2015-12-30 21:48
Next attempt, without a command this time. Successfully created, appeared in my channel list (although only when I refreshed the view by navigated from/to). The torrent is named `Tribler test README dm581xmPqe.md` and is also visible in Downloads in state "Seeding 100.0%".

Searching for `dm581xmPqe` shows no results. Magnet link is `magnet:?xt=urn:btih:413ed7fbeba68743417fd72c4ecbcd503245d705`. Base-64-encoded torrent file:

```
ZDg6YW5ub3VuY2UzMTp1ZHA6Ly90cmFja2VyLmp1c3RzZWVkLml0OjEzMzcAMTM6YW5ub3VuY2Ut
bGlzdGxsMzE6dWRwOi8vdHJhY2tlci5qdXN0c2VlZC5pdDoxMzM3AGVsMzE6dWRwOi8vdHJhY2tl
ci5qdXN0c2VlZC5pdDoxMzM3AGVsMzE6dWRwOi8vdHJhY2tlci5qdXN0c2VlZC5pdDoxMzM3AGVs
MzE6dWRwOi8vdHJhY2tlci5qdXN0c2VlZC5pdDoxMzM3AGVsMzE6dWRwOi8vdHJhY2tlci5qdXN0
c2VlZC5pdDoxMzM3AGVsMzE6dWRwOi8vdHJhY2tlci5qdXN0c2VlZC5pdDoxMzM3AGVsMzE6dWRw
Oi8vdHJhY2tlci5qdXN0c2VlZC5pdDoxMzM3AGVsMzE6dWRwOi8vdHJhY2tlci5qdXN0c2VlZC5p
dDoxMzM3AGVsMzE6dWRwOi8vdHJhY2tlci5qdXN0c2VlZC5pdDoxMzM3AGVsMzE6dWRwOi8vdHJh
Y2tlci5qdXN0c2VlZC5pdDoxMzM3AGVsMzE6dWRwOi8vdHJhY2tlci5qdXN0c2VlZC5pdDoxMzM3
AGVlMTA6Y3JlYXRlZCBieTI2OlRyaWJsZXIgdmVyc2lvbjogNi40LjAtR0lUMTM6Y3JlYXRpb24g
ZGF0ZWkxNDUxNTExODQ4ZTQ6aW5mb2Q2Omxlbmd0aGk1OTg4ZTQ6bmFtZTMzOlRyaWJsZXIgdGVz
dCBSRUFETUUgZG01ODF4bVBxZS5tZDEyOnBpZWNlIGxlbmd0aGkxNjM4NGU2OnBpZWNlczIwOocD
GxAHL+SSvBfT4HSGC0YWuWaXNDpzaGExMjA6hwMbEAcv5JK8F9PgdIYLRha5ZpdlZQ==
```

**Comment by vi** [comment] 2016-05-12 00:56
Still reproducible in v6.5.1 and in devel (b60d3b126ddfcafc2a939c32ca6b9a97a962f561). Actually I'm not sure Tribler can actually create new torrents for new files: #2197.

**Comment by vi** [comment] 2016-05-12 01:14
The channel itself is discoverable in search although.

**Comment by devos50** [comment] 2016-11-22 18:20
@vi do you encounter this in the Tribler 7 alpha?

**Comment by devos50** [comment] 2017-01-12 13:36
I found a problem when files are being indexed. Before I fixed this, torrents added to your channel did not show up indeed but now they do. This will be fixed in a next PR.

**Closed** 2017-01-13 09:03 UTC
Labels: bug
