### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dasunsrule32** [Tribler/tribler#8145] opened 2024-09-08 21:10 UTC
**Attempting to launch Tribler from the cli or from the Gnome shortcut causes a segmentation fault**

Error:
```
Fatal Python error: Segmentation fault

Current thread 0x00007466b9413080 (most recent call first):
  File "tribler/gui/tribler_window.py", line 226 in __init__
  File "tribler/gui/start_gui.py", line 84 in run_gui
  File "run_tribler.py", line 121 in main
  File "run_tribler.py", line 125 in <module>
```

Sysinfo
```
python3 -V
Python 3.12.3

cat /etc/os-release            
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

**Comment by qstokkink** [comment] 2024-09-09 07:20
Sadly, Tribler does not support Python 3.12 yet. Even Python 3.11 is still an open issue: #7282. We only support Python 3.10 at this moment.

This situation is caused by one of our dependencies (namely `libtorrent`). The good news is that once this does get fixed, both Python 3.11 and Python 3.12 should be supported.

Until we get a fix, #7282 is a duplicate of this issue and (as we don't allow duplicate issues) I'll close this one. If you run Tribler with Python 3.10 and still get a segfault, please reopen this.

**Closed by qstokkink** 2024-09-09 07:20 UTC
