### ISSUE TITLE
Ratio increasing fast

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3256] opened 2017-11-23 12:00 UTC
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Tribler 7 Nov 22th version
##### Operating system and version: #####
Windows 10 Insider 17046
##### Steps to reproduce the behavior: #####
Seed a file not Anonymous
##### Expected behavior: #####
Ratio increasing with normal speed and amount
##### Actual behavior: #####
Started seeding 1 hour ago and ratio is already at 2697,0 it is a 3 gig file and upload is only with 62 Kb, so no way that is is correct. I do not mind but ......... ;-)

With Anonymous seeding ratio is still NOT increasing and changing from NonAnonymous to Anonymous  clears the Ratio!!!!

**Comment by devos50** [comment] 2018-03-22 14:52
We're unable to reproduce this issue, therefore I close this. That the ratio is cleared when changing the number of hops, is a known issue and we will look into that.

**Closed by devos50** 2018-03-22 14:52 UTC
Labels: bug
