### ISSUE TITLE
browsing for external torrents & download target always starts in /Documents

### ISSUE THREAD

**Issue by Cathryne** [Tribler/tribler#1769] opened 2015-12-05 10:36 UTC
Using the functions `Download external torrent | Browse` and `Browse for Directory` always jump the view to the Documents folder. If the last torrent was added from another folder, that is shows for just a split second. The same is true when selecting a custom download target folder.

IMHO, it would be more logical to either jump to whichever folder is set as the download location, or to the last folder from which a torrent was opened.

Using v6.4.3 on Mac OS X 10.11.1. Moving ~/.Tribler doesn't change anything, but I'm not sure which file the log is supposed to be. pymdht.log says three times: `CRITICAL minitwisted.pyo:100 - run2() run`. I have no software installed that I expect to interfere with the directory selection of any program.

**Comment by Dmole** [comment] 2015-12-06 12:31
try /private/var/log/system.log

**Comment by Cathryne** [comment] 2015-12-06 14:30
OK, so after starting Tribler, `system.log` contains:
```
Tribler[45663]: Traceback (most recent call last):
Tribler[45663]:   File "<string>", line 5, in <module>
Tribler[45663]: ImportError: No module named csv
Tribler[45663]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.1 instead of 10.11.1. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
	Call location:
Tribler[45663]: 0   CarbonCore                          0x91fe6f1d ___Gestalt_SystemVersion_block_invoke + 135
Tribler[45663]: 1   libdispatch.dylib                   0x914847e7 _dispatch_client_callout + 50
Tribler[45663]: 2   libdispatch.dylib                   0x914846c3 dispatch_once_f + 78
Tribler[45663]: 3   libdispatch.dylib                   0x91485f4d dispatch_once + 31
Tribler[45663]: 4   CarbonCore                          0x91f629e1 _Gestalt_SystemVersion + 1047
Tribler[45663]: 5   CarbonCore                          0x91f6218a Gestalt + 154
Tribler[45663]: 6   libwx_macud-2.8.0.8.0.dylib         0x065b714b _Z14UMAInitToolboxtb + 43
sharedfilelistd[356]: SecTaskLoadEntitlements failed error=22
Tribler[45663]: pymdht: utils.py py2exe: Frozen mode
Dec  6 15:24:43 --- last message repeated 1 time ---
Tribler[45663]: pymdht: utils.py py2exe: bootstrap_stable
Tribler[45663]: pymdht: utils.py py2exe: bootstrap_stable /Applications/Tribler.app/Contents/Resources/Tribler/Core/DecentralizedTracking/pymdht/core/bootstrap_stable
Tribler[45663]: pymdht: utils.py py2exe: Frozen mode
Dec  6 15:24:43 --- last message repeated 1 time ---
Tribler[45663]: pymdht: utils.py py2exe:
Tribler[45663]: pymdht: utils.py py2exe: bootstrap_unstable /Applications/Tribler.app/Contents/Resources/Tribler/Core/DecentralizedTracking/pymdht/core/bootstrap_unstable
Tribler[45663]: pymdht: use_cache ON!!
Tribler[45663]: CRITICAL 1449411883.31     minitwisted:100   run
Tribler[45663]: >>>len(self._unstable_ip_port) == 4842, num_addrs: 40
Tribler[45663]: GUI started
launchservicesd[83]: SecTaskLoadEntitlements failed error=22
Tribler[45663]: GUI ready
```
And adding two torrents (2nd one sees the folder jumping issue), the following log entries appear:

```
Tribler[45663]: GetDYLDEntryPointWithImage(/System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete,CacheDeleteCopyPurgeableSpaceWithInfo) failed.
iconservicesagent[383]: -[ISGenerateImageOp generateImageWithCompletion:] Failed to composit image for descriptor <ISBindingImageDescriptor: 0x7ffebbf0bce0>.
quicklookd[45613]: Error returned from iconservicesagent: (null)
```
The last 2 messages appear several more times.

**Comment by whirm** [comment] 2015-12-07 11:21
@Cathryne could you test [this pre-release build](https://jenkins.tribler.org/job/Publish_tribler_next/161/)? it contains fixes for the issue you are having.

Please make a backup of your .Tribler before running the new version as it will make backwards incompatible upgrades to it so you won't be able to use it with an older Tribler version.

**Comment by Dmole** [comment] 2015-12-07 15:36
That build has the same issue (opens last then jumps to documents, even though finder is set to downloads).
There is a setting "Finder Preferences > New Finder windows show" it should respect when not opening last.

**Comment by whirm** [comment] 2015-12-07 15:42
@Dmole The fixes are for the errors in the logs.

**Comment by whirm** [comment] 2015-12-30 13:31
@devos50 are you up for this one? I guess it should easy to reproduce.

**Comment by synctext** [comment] 2016-01-06 14:02
This issue will be fixed when we move to a superior config file approach. We have half finished code for this.

**Comment by devos50** [comment] 2016-03-18 11:00
@whirm this one is nice to have but not top priority we think.

**Comment by whirm** [comment] 2016-03-18 11:09
@devos50 take it as a reminder for the unified config and the new GUI

**Comment by whirm** [comment] 2016-03-18 11:09
I don't know why I added the duplicate tag?

**Comment by Dmole** [comment] 2016-03-18 12:16
maybe for the bugs unrelated to the issue?

**Comment by devos50** [comment] 2016-03-20 19:20
@Cathryne thank you for the report. I tried to reproduce the issue and in my case, the button `Browse ` also start in Documents. It appears to be a bug in wxPython 2.8 since when I'm running the version built with wxPython 3.0 (Tribler 6.6), the file dialog starts correctly in my specified download directory. We will release a first alpha of Tribler 6.6 soon.

**Comment by Cathryne** [comment] 2016-03-27 07:26
Cool, thanks for investigating :-) Looking forward to 6.6!

**Comment by devos50** [comment] 2016-04-21 09:51
@whirm I think we can close this issue?

**Closed** 2016-04-21 09:52 UTC
Labels: bug
