### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2745] opened 2017-01-22 20:27 UTC
##### Tribler version/branch+revision: #####

8eadecd94da2849b54e801bc90c61b93694989ff from pull request #2701

##### Operating system and version: #####

Linux

##### Expected behavior: #####

File descriptors and sockets are used only for currently active tasks.

##### Actual behavior: #####

File descriptors (sockets) accumulate until it pushes the limit. Can't connect from Tribler QT GUI because of no more sockets (`EMFILE` errors on core logs)

##### Steps to reproduce the behavior: #####

Leave Tribler core running for a couple of days/weeks unattended.

##### Relevant log file output: #####

After trying to Ctrl+C the core:

```
...
2017-01-22T23:20:46+0300 [-] (UDP Port 48926 Closed)
2017-01-22T23:20:46+0300 [-] Stopping protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f89978c3878>
2017-01-22T23:20:46+0300 [-] (UDP Port 47378 Closed)
2017-01-22T23:20:46+0300 [-] Stopping protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f899703a248>
2017-01-22T23:20:46+0300 [-] (UDP Port 47544 Closed)
2017-01-22T23:20:46+0300 [-] Stopping protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f899d040878>
2017-01-22T23:20:46+0300 [-] (UDP Port 40982 Closed)
2017-01-22T23:20:46+0300 [-] Stopping protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f899646a908>
2017-01-22T23:20:46+0300 [-] (UDP Port 45909 Closed)
2017-01-22T23:20:46+0300 [-] Stopping protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f899762bcf8>
2017-01-22T23:20:46+0300 [-] (UDP Port 55957 Closed)
2017-01-22T23:20:46+0300 [-] Stopping protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f8997118998>
2017-01-22T23:20:46+0300 [-] (UDP Port 40040 Closed)
2017-01-22T23:20:46+0300 [-] Stopping protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f8995f0cef0>
2017-01-22T23:20:46+0300 [-] (UDP Port 33785 Closed)
2017-01-22T23:20:46+0300 [-] Stopping protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f8995ec6290>
2017-01-22T23:20:46+0300 [-] (UDP Port 57827 Closed)
...
```

(long enough to get tired of waiting and pressing Ctrl+\ to just terminate it)

**Comment by devos50** [comment] 2017-01-22 20:31
Thank you for the report. It seems that the `UDP` connections are not closed correctly. I will investigate this tomorrow!

**Comment by synctext** [comment] 2017-01-22 21:01
excellent! also observed that Tribler has limited uptime.

**Comment by devos50** [comment] 2017-01-22 21:04
I think this is caused by the if-statement being too restrictive: https://github.com/Tribler/tribler/blob/devel/Tribler/Core/TorrentChecker/session.py#L371

**Comment by devos50** [comment] 2017-01-22 21:06
Also, I can create a small unit test tomorrow where I use a database full of UDP trackers, run the automatic tracker check and verify whether the file descriptors are correctly cleaned up. It might also be an idea to track the number of open file descriptors in Gumby and plot it after each experiment. This is in particular helpful for our Tribler idle run experiment.

**Comment by devos50** [comment] 2017-01-23 09:03
Ok, it turns out that we aren't closing the socket after we successfully received data from a UDP tracker and this is easily fixed. Expect this to be fixed soon in a PR.

**Comment by devos50** [comment] 2017-01-23 19:06
I've spent several hours today trying to reproduce this bug. I did this both on macOS and Debian, however, the UDP session is always cleared in my case. This was verified by a test with a few hundred udp trackers where I initiate a session every five seconds and print the amount of open file descriptors. This number was stable during the run.

@vi is this behaviour also observed when just running the `twistd` plugin headless (without doing anything) for a while? Could you verify this? Thanks!

Since I cannot reproduce it now and I have no idea how to do it, I will push this issue to a later release.

**Comment by vi** [comment] 2017-01-23 21:06
`twistd -n tribler` was running for about two weeks serving multiple downloads, I periodically started the GUI to see how is it going.

Before finally rebooting the system I decided to take a look at what happens in Tribler, but it failed because of this.

**Comment by vi** [comment] 2017-01-24 20:42
Now 374 fds, including 292 sockets.

A lot of sockets have the same destination:

```
# netstat --inet -nap | grep python | awk '{print $5}' | sort | uniq -c | sort -rn | head -n 5
    104 69.165.95.242:6544
     61 163.172.157.130:80
     35 94.23.183.33:6969
     24 0.0.0.0:*
      9 148.251.49.46:80
```

**Comment by vi** [comment] 2017-01-28 11:07
Now 390 fds, including 304 sockets.

**Comment by vi** [comment] 2017-02-02 02:54
Now 697 fds, including 604 sockets. There are a lot of CLOSE_WAIT sockets to some :80 ports on various IPs.

**Comment by vi** [comment] 2017-02-03 18:30
I attempted to start GUI, and it failed.

Now 1024 fds, including 933 sockets, including 358 CLOSE_WAIT ones. UDP destinations stats:

```
    335 163.172.157.35:1337
    104 69.165.95.242:6544
     61 163.172.157.130:80
     37 94.23.183.33:6969
     15 0.0.0.0:*
```

Tribler spamming `2017-02-03T21:29:59+0300 [twisted.web.server.Site] Could not accept new connection (EMFILE)` in a tight loop even though I already closed GUI.

**Comment by synctext** [comment] 2017-05-16 19:05
```
Now 1024 fds, including 933 sockets, including 358 CLOSE_WAIT ones. UDP destinations stats:
    335 163.172.157.35:1337
    104 69.165.95.242:6544
```

That is fascinating, those IPv4 addresses are from udp://opentrackr.org and (now dead) udp://open.nyaatorrents.info 

So we are leaking it seems ```CLOSE_WAIT``` from tracker checking.

**Comment by synctext** [comment] 2017-05-19 16:48
Warning to @devos50 and @qstokkink  with development machines that have 8+ GByte of memory I guess you don't have those after 3 days :
![tribler_7 0rc2_low_memory__may2017](https://cloud.githubusercontent.com/assets/325224/26258030/2adb3676-3cc3-11e7-9a60-2787ac9522d2.png)
Conclusion: good to have inferior hardware at home.

Upto RC2 it seems to slowly eating resources. 
```
$ ps -eLf |grep tribler
pouwelse  9754 11430  9754  7    9 May16 pts/21   05:21:40 /usr/bin/python2.7 run_tribler.py
pouwelse  9754 11430  9758  0    9 May16 pts/21   00:00:18 /usr/bin/python2.7 run_tribler.py
pouwelse  9754 11430  9759  0    9 May16 pts/21   00:00:00 /usr/bin/python2.7 run_tribler.py
pouwelse  9754 11430  9760  0    9 May16 pts/21   00:00:00 /usr/bin/python2.7 run_tribler.py
pouwelse  9754 11430  9761  0    9 May16 pts/21   00:00:00 /usr/bin/python2.7 run_tribler.py
pouwelse  9754 11430  9766  0    9 May16 pts/21   00:03:32 /usr/bin/python2.7 run_tribler.py
pouwelse  9754 11430  9769  0    9 May16 pts/21   00:00:00 /usr/bin/python2.7 run_tribler.py
pouwelse  9754 11430 27263  0    9 10:13 pts/21   00:00:01 /usr/bin/python2.7 run_tribler.py
pouwelse  9754 11430 27264  0    9 10:13 pts/21   00:00:50 /usr/bin/python2.7 run_tribler.py
pouwelse 30593 16399 30593  0    1 18:22 pts/22   00:00:00 grep --color=auto tribler
$ ps axms |grep tribler
 1000  9754 0000000000000000                -                -                - -    pts/21   328:13 /usr/bin/python2.7 run_tribler.py
 1000 30630 0000000000000000                -                -                - -    pts/22     0:00 grep --color=auto tribler
$ ps axms |grep -i tribler
 1000  9754 0000000000000000                -                -                - -    pts/21   328:14 /usr/bin/python2.7 run_tribler.py
 1000 30632 0000000000000000                -                -                - -    pts/22     0:00 grep --color=auto -i tribler
$ ps axms |grep -i python
    0  7025 0000000000000000                -                -                - -    ?          0:00 python3 /usr/lib/software-properties/software-properties-dbus
 1000  9754 0000000000000000                -                -                - -    pts/21   328:19 /usr/bin/python2.7 run_tribler.py
 1000  9773 0000000000000100                -                -                - -    pts/21   801:37 [python2.7] <defunct>
 1000 23030 0000000000000000                -                -                - -    ?          0:47 /usr/bin/python3 /usr/bin/update-manager --no-update --no-focus-on-map
 1000 27365 0000000000000000                -                -                - -    ?          0:06 /usr/bin/python3 /usr/bin/update-manager --no-update --no-focus-on-map
 1000 30634 0000000000000000                -                -                - -    pts/22     0:00 grep --color=auto -i python
```

**Comment by qstokkink** [comment] 2017-05-19 17:16
@devos50 Could you hook up [Python Object Graphs](https://mg.pov.lt/objgraph/#reference-counting-bugs) or some other memory profiler to your mega test?

**Comment by devos50** [comment] 2017-05-28 17:48
@vi @synctext I managed to reproduce and fix this issue on Ubuntu. It turned out that the UDP socket was not closed correctly if we receive any data from this tracker. This issue took me a while to find since there are very few UDP trackers who actually return results. I've verified whether it has been fixed by monitoring the output of the `netstat` command provided by @vi.

**Closed** 2017-05-31 09:41 UTC
Labels: bug
