### ISSUE TITLE
DiscoveryCommunity may cause dirty reactor

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#918] opened 2014-11-06 14:23 UTC
I got this backtrace:
```
test_as_server: ONEXIT Waiting for Session to shutdown, will wait for an additional 59 seconds
test_as_server: ONEXIT Waiting for Session to shutdown, will wait for an additional 58 seconds
test_as_server: Session is shutdown
test_as_server: ONEXIT Waiting for Session to shutdown, will wait for an additional 59 seconds
test_as_server: ONEXIT Waiting for Session to shutdown, will wait for an additional 58 seconds
test_as_server: Session is shutdown
test_as_server: Number of threads still running 9
test_as_server: Thread still running MainThread daemon False instance: <_MainThread(MainThread, started 140013309232960)>
test_as_server: Thread still running Thread-1 daemon True instance: <Thread(Thread-1, started daemon 140013032912640)>
test_as_server: Thread still running PoolThread-twisted.internet.reactor-5 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-5, started daemon 140012616103680)>
test_as_server: Thread still running PoolThread-twisted.internet.reactor-4 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-4, started daemon 140012624496384)>
test_as_server: Thread still running PoolThread-twisted.internet.reactor-7 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-7, started daemon 140012599318272)>
test_as_server: Thread still running PoolThread-twisted.internet.reactor-3 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-3, started daemon 140012632889088)>
test_as_server: Thread still running PoolThread-twisted.internet.reactor-2 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-2, started daemon 140012641281792)>
test_as_server: Thread still running PoolThread-twisted.internet.reactor-1 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-1, started daemon 140012993214208)>
test_as_server: Thread still running PoolThread-twisted.internet.reactor-6 daemon True instance: <Thread(PoolThread-twisted.internet.reactor-6, started daemon 140012607710976)>
The reactor was dirty:
>     <DelayedCall 0x7f5751eacd40 [288.833064795s] called=0 cancelled=0 LoopingCall<300>(DiscoveryCommunity.periodically_insert_trackers, *(), **{})()>
E
======================================================================
ERROR: test_remotedownload (Tribler.Test.test_remote_torrent_handler.TestRemoteTorrentHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Test/test_remote_torrent_handler.py", line 51, in tearDown
    super(TestRemoteTorrentHandler, self).tearDown()
  File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Test/test_as_server.py", line 173, in tearDown
    self.assertFalse(delayed_calls, "The reactor was dirty when tearing down the test")
AssertionError: The reactor was dirty when tearing down the test
-------------------- >> begin captured logging << --------------------
```

**Comment by whirm** [comment] 2015-01-13 17:35
The task is being registered properly, so I would say the community is not being unloaded correctly? unload_community() hasn't been called because it would kill all pending tasks.

**Comment by whirm** [comment] 2015-01-14 11:45
I've been running ```test_remote_torrent_handler``` in a loop for more than half an hour and it hasn't failed once. @LipuFei can you reproduce it in your machine?

**Comment by LipuFei** [comment] 2015-01-14 11:50
@whirm This issue has a very tiny chance to show up. I haven't seen it for months. Let's close it for the moment.

**Comment by lfdversluis** [comment] 2016-04-07 16:36
Triggering it 100% currently with `<DelayedCall 0x7efdd9497290 [288.222896099s] called=0 cancelled=0 LoopingCall<300>(DiscoveryCommunity.periodically_insert_trackers, *(), **{})()>` as the delayed call in the reactor. Dispersy is not shutting down properly when running tests.

**Comment by whirm** [comment] 2016-04-08 08:58
@lfdversluis please elaborate on how to trigger it 100% of the time

**Comment by lfdversluis** [comment] 2016-04-10 10:33
I have a test suite that extends `TestAsServer`. It has the following config:

```
 def setUpPreSession(self):
        super(TestLibtorrentDownloadImpl, self).setUpPreSession()
        self.config = SessionStartupConfig()
        self.config.set_state_dir(self.getStateDir())
        self.config.set_torrent_checking(False)
        self.config.set_multicast_local_peer_discovery(False)
        self.config.set_megacache(True)
        self.config.set_dispersy(True)
        self.config.set_mainline_dht(False)
        self.config.set_torrent_collecting(True)
        self.config.set_libtorrent(True)
        self.config.set_dht_torrent_collecting(False)
        self.config.set_videoplayer(False)
        self.config.set_torrent_collecting_dir(os.path.join(self.session_base_dir, 'torrent_collecting_dir'))
```

and this simple test is enough to  get the trace:

```
def test_get_magnet_link_none(self):
        tdef = TorrentDef()
        sourcefn = os.path.join(TESTS_API_DIR, 'video.avi')
        tdef.add_content(sourcefn)
        tdef.set_tracker("http://localhost/announce")
        tdef.finalize()

        torrentfn = os.path.join(self.session.get_state_dir(), "gen.torrent")
        tdef.save(torrentfn)

        impl = LibtorrentDownloadImpl(self.session, tdef)
        link = impl.get_magnet_link()
        self.assertEqual(None, link, "Magnet link was not none while it should be!")
```

**Comment by lfdversluis** [comment] 2016-04-10 13:06
It is also good to note that the builders do not experience this dirty reactor, but I am on my ubuntu 15.10

**Comment by whirm** [comment] 2016-04-11 10:40
Great! Do you want to take care of this one?

I first would make sure that we are waiting for Dispersy to stop completely before going further ahead on the shut down process (maybe we are doing a non-blocking call on a different thread or something is returning a deferred that we are ignoring?)

You could add a check right after calling the stop method on dispersy seeing if there's any of these "periodically_insert_trackers" methods scheduled.

**Comment by lfdversluis** [comment] 2016-04-11 10:59
@whirm I can give it a try. Never looked into dispersy though, so may take some time.

**Comment by whirm** [comment] 2016-04-11 11:52
@lfdversluis this is probably a mistake on the Tribler side (not waiting for dispersy to be done).

**Comment by devos50** [comment] 2016-04-14 13:54
I just got the error again on a test, when running `test_tunnelhelper.py`. After running it manually, I got the following error:

```
TestTunnelHelpers: ERROR: The reactor was dirty:
TestTunnelHelpers: ERROR: >     <DelayedCall 0x10c6e26c8 [49.5446739197s] called=0 cancelled=0 ThreadedResolver._cleanup(u'dispersy8.tribler.org', <Deferred at 0x10c6e2560>)>
TestTunnelHelpers: ERROR: >     <DelayedCall 0x10c6e22d8 [49.544273138s] called=0 cancelled=0 ThreadedResolver._cleanup(u'dispersy2.st.tudelft.nl', <Deferred at 0x10c6e2200>)>
TestTunnelHelpers: ERROR: >     <DelayedCall 0x10c6e2b00 [49.5443279743s] called=0 cancelled=0 ThreadedResolver._cleanup(u'dispersy4.tribler.org', <Deferred at 0x10c6e2a28>)>
```

**Comment by whirm** [comment] 2016-04-14 14:04
That's may be the bootstrap stuff not registering these to be aborted when shutting down dispersy?

**Comment by lfdversluis** [comment] 2016-04-26 12:48
Forgot to update from last week. When shutting down, the discover community reports it received the close call and the taskmanager cancels all pending tasks. Dispersy also reported shutdown in 0.04 seconds, yet still a delayed call. The weird part is that I cannot find where a 300 second delayed call is scheduled, moreover they are added using the TaskManager so either that contains a bug, or something is already scheduled for execution (there was a delayed call that scheduled a callLater for example, so two distinct delays)

**Comment by lfdversluis** [comment] 2016-04-26 12:58
Just ran it again, output:

```
Dispersy: DEBUG: Unloading <Tribler.dispersy.discovery.community.DiscoveryCommunity object at 0x7f8be7d5db10> (the reactor has 21 delayed calls scheduled)
RequestCache: DEBUG: Clearing <Tribler.dispersy.requestcache.RequestCache object at 0x7f8be707ae50> [0]
Dispersy: DEBUG: Unloaded  <Tribler.dispersy.discovery.community.DiscoveryCommunity object at 0x7f8be7d5db10> (the reactor has 16 delayed calls scheduled now)
```

```
Dispersy: DEBUG: Checking dispersy stop results
TriblerLaunchMany: INFO: lmc: Dispersy successfully shutdown in 0.02 seconds
```

And result:
`TestLibtorrentDownloadImpl: ERROR: >     <DelayedCall 0x7f8be70672d8 [298.150224924s] called=0 cancelled=0 LoopingCall<300>(DiscoveryCommunity.periodically_insert_trackers, *(), **{})()>`

**Comment by lfdversluis** [comment] 2016-04-28 08:58
Opened a PR on dispersy concerning this one.

**Comment by whirm** [comment] 2016-04-28 09:45
@lfdversluis better if you provide a link for future reference

**Comment by lfdversluis** [comment] 2016-04-28 10:19
@whirm I agree, but common it's dispersy there are at most 2 to 3 PRs open on it :D

**Comment by whirm** [comment] 2016-04-28 10:28
_future_ reference :)

**Comment by lfdversluis** [comment] 2016-05-07 15:51
@whirm The PR is ready on the dispersy side, can you review and if ok and merged close this once more?

**Comment by whirm** [comment] 2016-05-09 09:42
For future reference: https://github.com/Tribler/dispersy/pull/472

**Comment by lfdversluis** [comment] 2016-05-31 19:27
@whirm this one can be closed :)

**Closed** 2016-06-02 13:34 UTC
Labels: bug
