### ISSUE TITLE
Tunnel community - exceptions.AttributeError: 'Candidate' object has no attribute 'connection_type'

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3316] opened 2017-12-27 08:42 UTC
```python
Traceback (most recent call last):
File "TriblerGUI/event_request_manager.py", line 99, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "multiprocessing/process.py", line 114, in run

File "TriblerGUI/core_manager.py", line 65, in start_tribler_core

File "twisted/internet/base.py", line 1199, in run

File "twisted/internet/base.py", line 1208, in mainLoop

--- <exception caught here> ---
File "twisted/internet/base.py", line 801, in runUntilCurrent

File "Tribler/community/tunnel/hidden_community.py", line 257, in monitor_downloads

File "Tribler/community/tunnel/hidden_community.py", line 657, in create_introduction_point

File "Tribler/community/tunnel/tunnel_community.py", line 554, in create_circuit

File "Tribler/community/tunnel/tunnel_community.py", line 554, in <genexpr>

File "Tribler/community/tunnel/tunnel_community.py", line 333, in candidate_is_connectable

exceptions.AttributeError: 'Candidate' object has no attribute 'connection_type'
```

**Comment by devos50** [comment] 2017-12-27 08:44
Duplicate of #3220

**Closed by devos50** 2017-12-27 08:44 UTC
