### ISSUE TITLE
[7.10] socket.gaierror: [Errno 11001] getaddrinfo failed ("gaierror episode 6: phantom menace")

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6297] opened 2021-08-30 07:05 UTC
[ipv8\messaging\anonymization\tunnel.py:172](https://github.com/Tribler/py-ipv8/blob/85f7eeeefecf2d6a2d0370494112b7a2c2ddd9f2/ipv8/messaging/anonymization/tunnel.py#L172)

```python
    async def resolve(self, host):
        # Using asyncio's getaddrinfo since the aiodns resolver seems to have issues.
        # Returns [(family, type, proto, canonname, sockaddr)].
        infos = await get_event_loop().getaddrinfo(host, 0, family=socket.AF_INET)
        return infos[0][-1][0]
```

```
tribler_gui.utilities.CreationTraceback: , 
  File "src\run_tribler.py", line 213, in <module>, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 395, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\core_manager.py", line 97, in on_request_error, 
  File "src\tribler-gui\tribler_gui\core_manager.py", line 177, in start_tribler_core, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 398, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\utilities.py", line 395, in trackback_wrapper, 
  File "src\tribler-gui\tribler_gui\core_manager.py", line 87, in on_core_finished, 
RuntimeError: The Tribler core has unexpectedly finished with exit code 1 and status: 0!, 
[PID:9732] 2021-08-11 20:51:28,129 - ERROR <taskmanager:135> TunnelExitSocket.done_cb(): Task resulted in error: [Errno 11001] getaddrinfo failed, 
Traceback (most recent call last):, 
  File "ipv8\taskmanager.py", line 131, in done_cb, 
  File "ipv8\messaging\anonymization\tunnel.py", line 172, in resolve, 
  File "lib\asyncio\base_events.py", line 825, in getaddrinfo, 
  File "lib\concurrent\futures\thread.py", line 57, in run, 
  File "lib\socket.py", line 918, in getaddrinfo, 
socket.gaierror: [Errno 11001] getaddrinfo failed, 
(Timestamp: 1628765421105, traceback timestamp: 1628704288130)
```

**Comment by qstokkink** [comment] 2021-08-30 07:44
Interesting, this is supposed to be caught by [these lines](https://github.com/Tribler/py-ipv8/blob/85f7eeeefecf2d6a2d0370494112b7a2c2ddd9f2/ipv8/messaging/anonymization/tunnel.py#L163-L167):

```python
                task = ensure_future(self.resolve(destination[0]))
                # If this also fails, the TaskManager logs the packet.
                # The host probably really does not exist.
                self.register_anonymous_task("resolving_%r" % destination[0], task,
                                             ignore=(OSError, ValueError)).add_done_callback(on_ip_address)
```

[The `socket.gaierror` is a subclass of `OSError`](https://docs.python.org/3/library/socket.html#socket.gaierror) and should be ignored. Expected behavior is to have [a message logged and the stacktrace printed](https://github.com/Tribler/py-ipv8/blob/master/ipv8/taskmanager.py#L134-L135):

```python
                except ignore as e:
                    self._logger.error('Task resulted in error: %s\n%s', e, ''.join(traceback.format_exc()))
```

**Comment by qstokkink** [comment] 2021-08-30 08:02
The IPv8 behavior seems to be correct. The error is ignored and the traceback is logged as intended:

```
[PID:9732] 2021-08-11 20:51:28,129 - ERROR <taskmanager:135> TunnelExitSocket.done_cb(): Task resulted in error: [Errno 11001] getaddrinfo failed, 
Traceback (most recent call last):, 
  File "ipv8\taskmanager.py", line 131, in done_cb, 
  File "ipv8\messaging\anonymization\tunnel.py", line 172, in resolve, 
  File "lib\asyncio\base_events.py", line 825, in getaddrinfo, 
  File "lib\concurrent\futures\thread.py", line 57, in run, 
  File "lib\socket.py", line 918, in getaddrinfo, 
socket.gaierror: [Errno 11001] getaddrinfo failed
```

I'm guessing the error occurred because the core crashed for a different reason, causing the socket request to fail. As a result of the true failure, the socket failure was then the last thing communicated to the GUI. In turn, Tribler's traceback detection works like this:

https://github.com/Tribler/tribler/blob/3611ee21c9e3ef7cd3d6157ab5e92d690067ffa3/src/tribler-gui/tribler_gui/core_manager.py#L64-L66

The log statement includes the word "Traceback" and overwrites the true `self.core_traceback`. So when the true failure crashes Tribler, Tribler fetches the last log statement that included the word "Traceback" - the socket failure.

The Sentry report of #6298 provides further evidence: two more UI requests succeed after the `socket.gaierror`. If the core had really crashed due to this, the requests wouldn't succeed.

**Comment by qstokkink** [comment] 2021-08-30 08:09
I don't believe we can debug the true failure with the available information.

For the next Tribler version we should probably replace `if b'Traceback' in raw_output` with something that filters out log messages so we can see the true traceback.

**Comment by ichorid** [comment] 2021-08-30 11:13
Actually, related to my favourite bug #4880

**Comment by qstokkink** [comment] 2021-08-30 12:06
@ichorid that seems to be a full-on duplicate. It seems we reached the same conclusions a year ago. I'll close this issue in favor of the older one.

**Closed by qstokkink** 2021-08-30 12:06 UTC
Labels: type: bug
