### ISSUE TITLE
[Feature request] Separate server and client.

### ISSUE THREAD

**Issue by rb07** [Tribler/tribler#4189] opened 2019-02-01 01:03 UTC
This is a feature request.

##### Tribler version/branch+revision: #####
7.2.0
##### Operating system and version: #####
Linux (Debian 3.10.105)
##### Steps to reproduce the behavior: #####
Execute tribler.sh
##### Expected behavior: #####
Feature: run only server.

Let's say I want to have a seedbox running only the server, and a client somewhere else controlling that server.

It would be useful in addition of tribler.sh to have a tribler-server.sh (or tribler-daemon.sh) which sets the 2 environment variables, CORE_BASE_PATH, CORE_API_PORT, and then executes tribler.sh .

Similar for the client (tribler-client.sh), just don't run the server, and set the server's IP address, and port.

##### Actual behavior: #####
Runs both server and client.

**Comment by xoriole** [comment] 2019-02-01 08:35
@rb07 Thank you for the feature request. We had discussions about it in the past. Currently, it is possible to run the server only using Twisted plugin. However, documentation is lacking on how to do it. 

Our focus atm is on stabilizing the integrated client and improving the performance. We'll revisit this feature request at a later point.

**Comment by hbiyik** [comment] 2020-05-26 21:04
Related

https://github.com/Tribler/tribler/issues/5327

**Comment by drew2a** [comment] 2024-06-06 14:03
If I understand the original request correctly (I'm a bit confused with the terms "client" and "server"), the issue is a duplicate of:
- #5303

**Closed by drew2a** 2024-06-06 14:03 UTC
Labels: type: enhancement
