### ISSUE TITLE
file size search limiter render error

### ISSUE THREAD

**Issue by brandc** [Tribler/tribler#1560] opened 2015-07-13 22:56 UTC
I could not upload the window image, so I had to post it on imgur, sorry in advanced.

https://i.imgur.com/SgCa4kc.png

**Comment by whirm** [comment] 2015-07-14 12:00
Thanks for the report!

**Comment by devos50** [comment] 2016-03-18 11:19
@whirm should be fixed by the minimum window size setting.

**Comment by whirm** [comment] 2016-03-18 11:37
Do it :)

**Comment by devos50** [comment] 2016-03-26 10:35
I'm unable to reproduce this both on OS X and Ubuntu but I made three changes that contribute to a solution of this problem:
- There's now a minimum window width for Tribler
- Replaced the show grid button with an image
- Decreased the width of the dropdown menus

**Comment by whirm** [comment] 2016-03-29 16:30
Can anybody test this on windows to make sure it's fixed there too?

**Comment by devos50** [comment] 2016-04-01 20:41
@whirm I've tested this on Windows. At first, the show grid button was not visible but I've changed the code and now it's showing. I haven't seen strange overlapping behaviour on all three platforms.

**Comment by whirm** [comment] 2016-04-07 13:02
Great, thanks!

**Comment by whirm** [comment] 2016-04-07 13:03
@devos50 these changes are on #2047 I assume?

**Comment by devos50** [comment] 2016-04-07 13:16
@whirm yeah, I will add it to the fixed issue list :+1:

**Closed** 2016-04-11 10:44 UTC
Labels: bug
