### ISSUE TITLE
Lost complete Library and ratio after upgrade

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#5039] opened 2020-01-03 19:37 UTC
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
Of course!
##### Tribler version/branch+revision: #####
7.4.0. Noodle
##### Operating system and version: #####
Windows 10 inside 19041
##### Steps to reproduce the behavior: #####
Upgrade from 7.4.0. to noodle
##### Expected behavior: #####
Import previous Library
##### Actual behavior: #####
Library is empty

**Comment by Nubro01** [comment] 2020-01-03 19:41
Reinstalled previous version, exported Library one by one, because all in one is NOT possible!!!!
Installed Noodle version and imported folder with saved torrents, but because the different location was NOT SAVED, all wanted to download to Tribler download setting, which was not correct. Had to move all important torrents to their correct location, recheck and some got to 99.9% while they ALL WHERE 100%. In total a lot of work, just because you guys are making a mess of it!!!! Please test better in a way a normal user uses the system!

**Comment by ichorid** [comment] 2020-01-04 19:32
@devos50 , @xoriole , maybe we should use a separate config dir for experimental releases, so the primary one will remain untouched no matter what?

**Comment by devos50** [comment] 2020-01-04 20:33
Yeah I think we should start doing this. Although I wonder why the state dir got corrupted, since the experimental release is based on the `release-7.4.0` branch, with the Noodle community added. So I think this is an issue in 7.4.0?

**Comment by devos50** [comment] 2020-02-03 08:45
This is a duplicate of #5006, which I will upgrade to a high priority issue. Please continue the discussion in that issue. 👍

**Closed by devos50** 2020-02-03 08:45 UTC
Labels: bug
