### ISSUE TITLE
[FEATURE REQUEST] Sending Tribler to tray.

### ISSUE THREAD

**Issue by ghost** [Tribler/tribler#2536] opened 2016-09-05 21:53 UTC
The software is amazing as is. It'd be amazing to send Tribler to tray and not worry about accidentally closing the window.

**Comment by lfdversluis** [comment] 2016-09-11 09:18
@devos50 I recall you have this implemented in the new GUI?

**Comment by devos50** [comment] 2016-09-11 16:49
@lfdversluis at the moment when you press the close button in the new GUI, Tribler is closed completely. @ghost thanks for the suggestion, I will take a look at it!

**Comment by devos50** [comment] 2017-01-22 16:49
Duplicate of #1054.

**Closed by devos50** 2017-01-22 16:49 UTC
Labels: enhancement
