### ISSUE TITLE
A download in GUI fluctuates between "0%" and "Seeding".

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#7187] opened 2022-11-18 02:01 UTC
Sometimes a download in Triber 7.12.0 or 7.12.1 is shows alternately as if it were not really started ("Downloading", "0%") and the actual progress ("Downloading" with actual percentage or "Seeding" if it is finished). Pathenthesised number of seeds and peers also fluctuates between different nonzero numbers for broken and correct sets of download status data.

Both upload and download byte counters are small, but nonzero in the broken stats set. Both counters are also slowly rise over time, as if it is very slowly downloading the file second time. 

Individual counter for a file may stay "0%" even though whole download is being shown "100%".

Clicking around tabs showing download details also resulted in this:

> An error occurred during the request:
> index out of range
> [Close]

(`ERROR <tribler_request_manager:225> root.on_finished(): REST API error: {'error': 'index out of range'}`)

**Comment by drew2a** [comment] 2022-11-28 10:35
Could be related: https://github.com/Tribler/tribler/issues/5930

**Comment by drew2a** [comment] 2023-12-14 14:48
Could be a duplicate of 
- #5617

**Comment by qstokkink** [comment] 2024-08-12 08:21
This should be resolved in the new Tribler 8.0 web-based front end.

**Closed by qstokkink** 2024-08-12 08:21 UTC
Labels: type: bug
