### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3440] opened 2018-02-05 16:07 UTC
From reporter (Tribler 7.0.0)
> crash occured shortly after displaying first channels after first startup
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 99, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'socket.error'>: [Errno 16] Device or resource busy
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
/usr/lib/python2.7/threading.py:754:run
/usr/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work
/usr/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/lib/python2.7/site-packages/twisted/python/threadpool.py:250:inContext
/usr/lib/python2.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/lib/python2.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/lib/python2.7/site-packages/twisted/python/context.py:85:callWithContext
/usr/lib/python2.7/site-packages/twisted/internet/_resolver.py:124:get
]
```

**Comment by non-Jedi** [comment] 2018-05-02 22:17
Per conversation on https://github.com/NixOS/nixpkgs/pull/36065, it seems this bug was introduced some time between 7.0.0 rc3 and the 7.0.0 release. I was going to take a look and see if I could find anything, but there are quite a few commits there. Might want to control your rc process a little better.

**Comment by qstokkink** [comment] 2018-06-22 10:31
The error seems to be here:

https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/_resolver.py#L123

My best guess is that this is the line that would cause this:

https://github.com/Tribler/tribler/blob/a088d01b8bcadd5ff3ca4157e128d83f9fa6b2e9/Tribler/Core/TorrentChecker/session.py#L523

If this is the case, we would fix this by adding an `errback()` there.

**Comment by devos50** [comment] 2018-06-22 10:51
@non-Jedi thank you for your report. We are currently in the process of reproducing and fixing this bug within our environment. We will keep you updated!

**Comment by qstokkink** [comment] 2018-06-26 08:51
Can someone with NixOS send me the output of this script?

```python
import urllib2, socket, urlparse
from twisted.internet import defer, reactor, threads


def error(failure):
    print str(failure)


def run():
    urls = ["https://www.google.com/", "http://www.python.org/", "https://github.com/"]
    try:
        deferreds = []
        for url in (urls):
            deferreds.append(reactor.resolve(url))
            deferreds[-1].addErrback(error)
        threads.blockingCallFromThread(reactor, lambda: defer.DeferredList(deferreds))
        print "Finished Twisted resolution"
    except:
        import traceback
        traceback.print_exc()
        print "Twisted reactor.resolve failed"

    try:
        for url in (urls):
            socket.gethostbyname(urlparse.urlparse(urllib2.urlopen(url).geturl()).hostname)
        print "Finished socket resolution"
    except:
        import traceback
        traceback.print_exc()
        print "Socket gethostbyname failed"
        
    reactor.callFromThread(reactor.stop)

reactor.callInThread(run)
reactor.run()
```

**Comment by non-Jedi** [comment] 2018-06-26 12:00
@xvapx I'm not sure how to make a python environment with nix that looks like the one tribler sees. Maybe you have a better idea.

**Comment by xvapx** [comment] 2018-06-26 21:11
@non-Jedi Yes, nixos generates a wrapper for tribler which exports all the needed environment variables and paths, you can actually run ```cat $(which tribler)``` to see the entire environment in which tribler will run.

@qstokkink output: 
```
[Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: https://github.com/.
]
[Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: https://www.google.com/.
]
[Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: http://www.python.org/.
]
Finished Twisted resolution
Finished socket resolution
```
Is there any more test more I can do to help?

**Comment by qstokkink** [comment] 2018-06-27 07:59
@xvapx Thanks for testing: this apparently is not the issue making Tribler crash on Nix though.

One side-effect of testing this, is that we discovered that `reactor.resolve` is pretty bad at what it does.

**Comment by xvapx** [comment] 2018-06-27 08:10
@qstokkink No problem, I'm testing 7.1.0-exp2 to see if something has changed on nixos, I'll report back.

**Comment by xvapx** [comment] 2018-06-28 07:37
I'm working on it, having to fix some dependencies in nixpkgs.

**Comment by xvapx** [comment] 2018-06-28 09:54
@qstokkink @non-Jedi 
7.1.0-exp2 is no longer crasing in nixos, I'm testing that it actually works and will PR in nixpkgs.

**Comment by xvapx** [comment] 2018-06-28 09:57
crash log: 
```
Traceback (most recent call last):
  File "/home/xvapx/tmp/tribler/tmp/tribler/TriblerGUI/event_request_manager.py", line 127, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'socket.error'>: [Errno 16] Device or resource busy
/nix/store/d3aa78jf7pm9lk6ad67x4f21a068dxn6-python-2.7.15/lib/python2.7/threading.py:801:__bootstrap_inner
/nix/store/d3aa78jf7pm9lk6ad67x4f21a068dxn6-python-2.7.15/lib/python2.7/threading.py:754:run
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/python/threadpool.py:250:inContext
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/python/context.py:122:callWithContext
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/python/context.py:85:callWithContext
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/internet/_resolver.py:124:get
]
```

**Comment by qstokkink** [comment] 2018-06-28 10:18
It seems the error is with Twisted: https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/_resolver.py#L123 seems to only catch `gaierror` and not a `socket.error`.

If we fix this on our end, it would be a nasty patch.

**Comment by qstokkink** [comment] 2018-06-28 11:47
This should be fixed now. We'll keep you posted on the build completion.

**Comment by qstokkink** [comment] 2018-06-28 14:44
Actually, release candidate 3 should be out tomorrow evening.

**Comment by xvapx** [comment] 2018-06-28 19:33
Great, I'll test it ASAP, thanks a lot!

**Comment by xvapx** [comment] 2018-06-29 18:49
@qstokkink 
Sorry, bad news:
```
Traceback (most recent call last):
  File "/home/xvapx/tmp/tribler/tmp/tribler/TriblerGUI/event_request_manager.py", line 127, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'socket.error'>: [Errno 16] Device or resource busy
/nix/store/d3aa78jf7pm9lk6ad67x4f21a068dxn6-python-2.7.15/lib/python2.7/threading.py:801:__bootstrap_inner
/nix/store/d3aa78jf7pm9lk6ad67x4f21a068dxn6-python-2.7.15/lib/python2.7/threading.py:754:run
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/python/threadpool.py:250:inContext
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/python/context.py:122:callWithContext
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/python/context.py:85:callWithContext
/nix/store/hfq5vjpvsx9j38jc30fkg0r095m4lq3r-python2.7-Twisted-18.4.0/lib/python2.7/site-packages/twisted/internet/_resolver.py:124:get
]
```

I've sent the report, it's the same bug, version 7.1.0-exp3, on NixOS.

**Closed** 2018-07-03 13:32 UTC
Labels: bug

**Comment by xvapx** [comment] 2018-07-03 19:01
Great, thanks a lot!

**Comment by devos50** [comment] 2018-07-04 09:20
@xvapx could you try out this build? https://jenkins.tribler.org/job/Build_Tribler_next/297/

**Comment by xvapx** [comment] 2018-07-04 18:39
Yep, I'll try and report back

**Comment by xvapx** [comment] 2018-07-05 09:19
@devos50 It's been running for more than one hour now, without a single crash.

**Comment by viric** [comment] 2020-05-01 10:44
This crashes again in release-20.03. Same thing.

**Comment by viric** [comment] 2020-05-01 13:22
This doesn't happen in 7.5.0-rc5 so I guess it's all fine.
