### ISSUE TITLE
assert not self.is_pending_task_active(name), name

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1505] opened 2015-06-25 13:17 UTC
```
ERROR   1435232992.40 tunnel_community:911   TunnelCommunity: ignoring create for circuit 3051131972 from ('95.211.198.140', 7112) (too many relays 100)
ERROR   1435234229.56             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/APIImplementation/TwistedRawServer.py", line 23, in <lambda>
    reactor.callFromThread(lambda: self.register_task(task_name, self._reactor.callLater(delay, wrapper)))
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/taskmanager.py", line 36, in register_task
    assert not self.is_pending_task_active(name), name
exceptions.AssertionError: twisted_rawserver 265974

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/APIImplementation/TwistedRawServer.py", line 23, in <lambda>
    reactor.callFromThread(lambda: self.register_task(task_name, self._reactor.callLater(delay, wrapper)))
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/taskmanager.py", line 36, in register_task
    assert not self.is_pending_task_active(name), name
exceptions.AssertionError: twisted_rawserver 265974
ERROR   1435237244.49 tunnel_community:911   TunnelCommunity: ignoring create for circuit 3455341185 from ('145.94.62.234', 7759) (too many relays 100)
```

**Comment by whirm** [comment] 2015-06-29 13:47
duplicate of #1512

**Closed by whirm** 2015-06-29 13:47 UTC
Labels: bug
