### ISSUE TITLE
bencoded item count limit exceeded

### ISSUE THREAD

**Issue by pimlie** [Tribler/tribler#3037] opened 2017-07-09 15:28 UTC
- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
nothing to commit, working directory clean
$ git show
commit bc8991f2244bd2cf7bd30b5a9585747e9a9e43d5
Merge: fe5e6be 521a0af
Date:   Wed Jun 21 13:30:50 2017 +0200

##### Operating system and version: #####
Ubuntu 16.04

Could not find any issues yet with this message. I was adding a torrent and suddenly Tribler crashed with the following error. The torrent is from a private tracker which I cant share unfortunately, but it consists of a lot of small files (the torrent file is ~25MB in size).

```
Traceback (most recent call last):
  File "/opt/tribler/TriblerGUI/event_request_manager.py", line 99, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/tribler/TriblerGUI/core_manager.py", line 63, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 240, in schedule_create_engine
    self.pstate_for_restart, share_mode=share_mode)
  File "/opt/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 314, in network_create_engine_wrapper
    torrentinfo = lt.torrent_info(metainfo)
exceptions.RuntimeError: bencoded item count limit exceeded
```

**Comment by qstokkink** [comment] 2017-08-22 11:02
According to the libtorrent docs, the bencoded dict was too large to decode (ref http://www.rasterbar.com/products/libtorrent/manual.html#lazy-bdecode). Since this call is hidden in `torrent_info`, this might be a bit of a problematic fix.

**Comment by qstokkink** [comment] 2017-08-22 11:39
As it seems that the fix for this would be to write our own `bdecode` method (or switch torrent backend), we will postpone fixing this until after the 7.0 release.

**Comment by pimlie** [comment] 2017-08-22 11:47
It looks to me that this error is triggered by reaching `item_limit`? Wouldn't setting a larger `item_limit` solve the issue? Maybe configurable through a config file?

**Comment by qstokkink** [comment] 2017-08-22 12:35
@pimlie yes, but this is only available in the C++ backend: the Python binding to control this is no longer available. We would have to recompile libtorrent to expose this functionality (which is a fair bit of work and something we can't realistically support in the long run).

**Comment by pimlie** [comment] 2017-08-22 14:03
@qstokkink Ah right, sorry. Couldn't we just submit an upstream issue for this with libtorrent then? I would think if its possible in the C++ backend it should be possible in the Python binding, or is that too simple? ;)

**Comment by qstokkink** [comment] 2017-08-22 14:26
@pimlie Once again correct, but that would take months, if not years, to trickle down into the package managers of different platforms. Short term, we would still need a workaround for this.

**Comment by pimlie** [comment] 2017-08-22 20:55
@qstokkink unless you see more benefits from developing your own solution, I am not sure why you would go to all that trouble if this issue is the only reason for that. Probably that limit has been in libtorrent like forever and it seems nobody (also me) ever had problems with that limit before. So if I would need a specific lib version to be able to change that limit, I wouldnt regard that as a problem in this case. You just cant have it all ;)

That said, being dependent on package managers of different platforms is never a good solution. Probably one of the reasons why so many open source applications provide users with their own repositories (like ppa's for ubuntu). As an organisation it gives you full control and makes it easier to eg introduce new features also for (maybe) out-dated platforms. 
A dependency on official package managers will most probably slow-down development as time needs to be spent on workarounds for old lib versions instead of new features (or bug fixes! ;)

Probably for this exact reason is why eg Deluge already has a ppa which includes their own libtorrent binary: https://launchpad.net/~deluge-team/+archive/ubuntu/develop/+packages

**Comment by qstokkink** [comment] 2017-08-23 07:39
@pimlie having a torrent which Tribler cannot handle, but other platforms can, is a thorn in my side. This hurts my pride. Nevertheless, I have been urged to delay fixing this until after the 7.0 release.

But, yes, you are probably right. Considering the issues we had in the past, just like Deluge, it would probably be best to start maintaining our own libtorrent binary as well.

**Comment by qstokkink** [comment] 2018-07-26 09:09
I looked into this more. The only realistic option is to submit a PR to libtorrent to expose the bencoding limit.

**Comment by drew2a** [comment] 2022-08-17 14:39
Is this issue outdated?

In Tribler we use libtorrent version `1.2.15`:
https://github.com/Tribler/tribler/blob/932f51a17115c5e30bf57567188c105f7da40646/requirements-core.txt#L26

Also, I don't see this error in Sentry:

<img width="743" alt="image" src="https://user-images.githubusercontent.com/13798583/185165451-46d00584-2030-4ae1-a532-a778345a030e.png">

**Comment by qstokkink** [comment] 2022-08-17 15:02
This should still be an issue. Looking at [the libtorrent source code](https://github.com/arvidn/libtorrent/blob/550d3c7d9faeb3c59584b16fd0fc90a05e047ce5/include/libtorrent/bdecode.hpp#L472-L481), the default depth limit is `100` items and the token count is set to a max of `2000000`. A ~25MB torrent file, as described in OP, should still trigger this issue.

Perhaps we can make our own huge torrent file for testing?

**Comment by qstokkink** [comment] 2022-08-23 11:30
Reproduced using the following script:

```python
# pip install bencode.py

import bencodepy

FILE_COUNT = 1000000

output = bencodepy.encode({
        'nodes': [],
        'info':
        {
            'files':
            [
                {'length': 1, 'path': [f'{i}.txt']} for i in range(FILE_COUNT)
            ],
            'name': 'longtorrent',
            'piece length': 1,
            'pieces': b"\x01" * 20 * FILE_COUNT
        }
    })

with open("longtorrent.torrent", "wb") as f:
    f.write(output)
    f.flush()
```

I confirmed that a `FILE_COUNT` of up to 100k works but 1M breaks with the following messages:

![message](https://user-images.githubusercontent.com/3630389/186146872-ba204f4f-6fb6-4e70-a695-394f37aba839.png)

If you click "download" anyway, you get this:

![box](https://user-images.githubusercontent.com/3630389/186147001-aa3ea55f-5746-4d03-92bc-29d05fb06989.png)

**Comment by qstokkink** [comment] 2022-08-23 11:40
The following is maybe even more interesting: torrent of death 😃. Tribler crashes and auto-closes before you can submit a report:

```python
# pip install bencode.py

import bencodepy

PATH_DEPTH = 10000

output = bencodepy.encode({
        'nodes': [],
        'info':
        {
            'files':
            [
                {'length': 1, 'path': [f"{i}" for i in range(PATH_DEPTH)] + [f'file.txt']}
            ],
            'name': 'deeptorrent',
            'piece length': 1,
            'pieces': b"\x01" * 20
        }
    })

with open("deeptorrent.torrent", "wb") as f:
    f.write(output)
    f.flush()
```

Digging into the logs, this is causing it:
```
[PID:12868] 2022-08-23 13:37:35,455 - ERROR <error_handler:32> ErrorHandler.gui_error(): tribler.gui.utilities.CreationTraceback: 
  File "run_tribler.py", line 100, in <module>
  File "tribler\gui\start_gui.py", line 77, in run_gui
  File "tribler\gui\utilities.py", line 411, in trackback_wrapper
  File "tribler\gui\tribler_window.py", line 891, in on_add_torrent_browse_file
  File "tribler\gui\tribler_window.py", line 620, in process_uri_request
  File "tribler\gui\tribler_window.py", line 915, in start_download_from_uri
  File "tribler\gui\dialogs\startdownloaddialog.py", line 112, in __init__
  File "tribler\gui\dialogs\startdownloaddialog.py", line 148, in perform_files_request
  File "tribler\gui\tribler_request_manager.py", line 178, in __init__


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tribler\gui\utilities.py", line 414, in trackback_wrapper
  File "tribler\gui\utilities.py", line 411, in trackback_wrapper
  File "tribler\gui\dialogs\startdownloaddialog.py", line 198, in on_received_metainfo
  File "tribler\gui\widgets\torrentfiletreewidget.py", line 210, in fill_entries
  File "tribler\gui\widgets\torrentfiletreewidget.py", line 82, in fill_directory_sizes
  File "tribler\gui\widgets\torrentfiletreewidget.py", line 82, in fill_directory_sizes
  File "tribler\gui\widgets\torrentfiletreewidget.py", line 82, in fill_directory_sizes
  [Previous line repeated 983 more times]
  File "tribler\gui\widgets\torrentfiletreewidget.py", line 81, in fill_directory_sizes
  File "tribler\gui\widgets\torrentfiletreewidget.py", line 67, in children
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by drew2a** [comment] 2022-08-24 10:06
@qstokkink great investigation! I think now I can fix the issue (at least the torrent of local death).

**Closed** 2022-08-27 09:10 UTC
Labels: type: bug, status: reproduced
