### ISSUE TITLE
Gigachannel "inbox" or "pull requests"

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4831] opened 2019-09-10 12:06 UTC
_placeholder ticket_

Priority _after_ issue #1 is finished (anonimity, fast speed with tokens, content wealth).
Requirement: sizable active content sharing community and new social practices.

How do we remove spam and create a bias for high-quality metadata? Our primary reliance is on the [group selection theory](https://en.wikipedia.org/wiki/Group_selection). Thus, gigachannels compete for votes and obtain more prominence in the user interface. This is a [proven successful method](https://dl.acm.org/citation.cfm?id=1481457).

A single person is currently in charge of the channel. This limits growth we believe.  < rant >  However, we have not yet reached a clear limit to Gigachannels editorial process. It just got launched and is not yet used. This issue documents a possible next step, if and only if we see that the single-author model has reached some limit. The next form of crowd-sourcing is utilising known contributors and strangers. It is specifically selected to avoid ***any*** risks or catastrophic failure. Each Gigachannel has an inbox with suggested magnet link additions, renames, and deletions. Until we see spam or even DDoS attack we should avoid making any assumptions on their shape, magnitude or occurrence itself. All bets are off if Tribler becomes a method to distribute anti-government videos. Avoid being one of the 250+ [broken dream projects without any usability and usage](https://github.com/redecentralize/alternative-internet). For email it took years to evolve spam fighting and user involvement:
![image](https://user-images.githubusercontent.com/325224/64611861-b08af380-d3d2-11e9-956d-e45e1ac1b9da.png)

Sophisticated crowd-sourcing models like Wikipedia attempt to remove the responsible editor role. We are not yet ready for this, we first need 1+ million users and daily active editors.
<img src="https://user-images.githubusercontent.com/325224/64610925-94865280-d3d0-11e9-89db-0ef693e16dae.png" width="200">

**Comment by ichorid** [comment] 2019-09-10 18:22
Data can flow upstream by "stochastic push requests" system, which will prevent spam (almost) completely. Channel owner continuously walk subscribed peers and ask them if they have some changes prepared for his channel. If they do, the changes are pushed into the owner's database so the owner himself can review these later. The peers that produced more accepted changes are visited more often. This system naturally expands into hierarchies of arbitrary size. Basically, it copies the Kernel development system adding stochasticity to facilitate emergent self-organization.

**Comment by synctext** [comment] 2019-09-10 19:07
Good idea. Pull protocol with whitelisting, avoid push architecture.

**Comment by ichorid** [comment] 2021-09-28 13:40
duplicate of #6217

**Closed by ichorid** 2021-09-28 13:40 UTC
Labels: type: long-term, component: channels
