### ISSUE TITLE
Unable to add torrents by "running" the torrent file. 6.6.0-exp1 on windows 10

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2512] opened 2016-08-07 09:25 UTC
#### Please, fill all relevant items:
- [x] I have read CONTRIBUTING.md
- [x] I have tried with the latest pre-release version and I still can reproduce the issue. 
##### Tribler version/branch+revision:

Multichain test build 6.6.0-exp1
##### Operating system and version:

Windows 10 Home, August Update installed. Version 1607, OS build 14393.10.
##### Expected behavior:

Tribler is running. Running a torrent file and a pop-up window with torrent information, where to download, safe seeding, files in torrent should appear in Tribler. 
##### Actual behavior:

Window mentioning internal error, with the part below and system information. There's also a white box, which is just the same as the one appearing on start up and close down, instead of the window in previous versions of Tribler, so i'm guessing this is a problem with the Tribler process that is started when adding a torrent.  After closing the internal error window, the box remains until i get an "this program is not responding, do you want to close it" message. 

Adding a torrent file with finding the file using Tribler works just fine. 

Error message:

Tribler version: 6.6.0-exp1
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 151, in **init**
  File "Tribler\Core\Session.pyo", line 463, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 110, in register
  File "Tribler\Core\leveldbstore.pyo", line 84, in **init**
type: IO error: collected_torrents\MANIFEST-001701: Ugyldig referanse.

"Ugyldig referanse" means invalid reference(or something along thoseN lines), since you probably don't know Norwegian.
##### Steps to reproduce the behavior:

I use a program that downloads the torrents, but it happens when downloading a torrent and "running" the torrent file.
##### Relevant log file output:

Log file, with probably a lot of other errors too, but i don't know so much about them. 

https://mega.nz/#!FIQQCApL!hAM4kav0elLAN7W0WE-P_MSW2EFKKbWXUMWWAlv_F3I

**Comment by devos50** [comment] 2016-08-08 16:01
@Thomasedv thanks for reporting! It looks like your `leveldb` database is corrupt somehow but we should have a closer look to see what has caused it.

**Comment by whirm** [comment] 2016-08-09 08:33
What's probably happening is that Tribler is not on the statedir when opening the torrent store due to the different code path triggered when clicking on the torrent file instead of the .exe

**Comment by devos50** [comment] 2016-11-29 20:41
@thomasedv This should be fixed in the latest alpha release of Tribler 7, see https://jenkins.tribler.org/job/Build_Tribler_devel/181/. I've tested adding torrent files on Windows, both when Tribler is running and when Tribler is not running and in both situations, it seems to proceed like expected so I'm unable to reproduce this issue.

Can you please try again with the alpha build? If it happens again, please reopen this issue and we will take a closer look at it.

**Closed by devos50** 2016-11-29 20:41 UTC
Labels: bug

**Comment by Thomasedv** [comment] 2016-11-29 21:00
Ok, @devos50  I got another crash, but it's not the same one. Basically, it crashes when you attempt to add two or more torrents(local torrents, not tried magnet links yet) at once. It successfully gives the pop-up, and you add the first file by pressing download. Then, when you press the download button on the second torrent, it crashes. 

Here's the error: http://i.imgur.com/ZHpQBYG.png

Want me to create a new issue, since it's likely not the same? Did this on a fresh install, windows 10, and the linked build, using the x64 version. Tribler installed on a non-default location.

**Comment by devos50** [comment] 2016-11-29 21:02
@Thomasedv ah I think I understand what's going on here and it should be quite easy to fix. Yes, please create an issue for this and thanks for the fast testing! 👍

**Comment by Thomasedv** [comment] 2016-11-29 21:59
No problem @devos50 I've got one thing i want to ask about, when i launch Tribler. It says this: http://i.imgur.com/2nJMMOz.png 

Is it not worth mentioning or something you're aware of?
