### ISSUE TITLE
Strange token balance drain without much downloads active.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#5310] opened 2020-05-05 00:14 UTC
#### Tribler version/branch+revision: #####

ea923d8a6f55582da6523ad81e53d33d9cb74116 release-7.5

##### Operating system and version: #####

Linux, non-Dockerized

##### Steps to reproduce the behavior: #####

1. Run a Tribler profile with long history of usage though various version (including recent rollback to v7.3.2). Most of token balance just remains from what was earned about two-three years ago.
2. Update to release-7.5 branch from Git.
3. Start, wait, ensure Token Balance is OK.
4. Observe Token Balance slowly growing (maybe due to exit node being on) on the plots.
5. Not have any serious downloads or uploads active (just one mostly idling, very slow `bootstrap.block` download and the rest seeding that are rarely actually active). Channels are updating, but they are not _that_ big.

##### Expected behavior: #####

It keeps on going like this further.

##### Actual behavior: #####

Strange drastic Token balance drain, maybe even faster than network connection allows uploading or downloading.

![screenshot](https://user-images.githubusercontent.com/173219/81025204-8e247980-8e7e-11ea-8554-6e21fe37fd01.png)

**Comment by vi** [comment] 2020-05-05 00:44
Looks like it has petered out:

![screenshot](https://user-images.githubusercontent.com/173219/81026366-8ff03c00-8e82-11ea-99fd-ce1db72671e6.png)

Has the balance stabilized on just today's transit traffic?

**Comment by devos50** [comment] 2020-05-05 07:12
When leaving the Tribler instance without any (active) downloads, it could relay data. However, an increase in 'bytes given' should be accompanied with a (higher) increase in 'bytes taken'.

Now, we recently addressed a Python 3-related bug where payouts between Tribler 7.4 and 7.5 instances were not working correctly, due to a database error. I think that this behaviour is the result of an interaction between a 7.5 instance (you) and 7.4 instance, which is still not properly functioning. Particularly, it seems that the downloader (running 7.4) is not initiating the final payout. We should look into this.

The last screenshot indicates a glitch in the token balance graph, which is probably related to #5255. So far, we have only seen this weird behaviour on Linux.

**Comment by vi** [comment] 2020-05-05 11:06
> However, an increase in 'bytes given' should be accompanied with a (higher) increase in 'bytes taken'.

Do you mean the reverse?

> The last screenshot indicates a glitch in the token balance graph, which is probably related to #5255. So far, we have only seen this weird behaviour on Linux.

Display was locked and Tribler window minimized at that time. Maybe that's why there are no points on the graph?

> seems that the downloader (running 7.4) is not initiating the final payout.

Should it lead to the drain much faster than current total network load or just lead to non-increase of the balance where it should?

**Comment by vi** [comment] 2020-05-06 08:29
In the end, "Taken from community plot" reached some limit (maybe it was total amount of very old tokens) and stopped growing:

![screenshot](https://user-images.githubusercontent.com/173219/81154741-dfbb2a00-8f8c-11ea-9c19-2361ddfa4ccd.png)

**Comment by synctext** [comment] 2020-06-09 14:17
Thx @vi for helping us extensively. This token balance issue has been haunting us for a while.

For next release we will aim to fix this, do an upgrade, and add additional debug panel info. We will provide more details on your _community standing_ and split the various token income source and spending. For instance, relaying income, relaying spending, exit node spending, and end-to-end seeding income. 

FYI. Our historical designs and prototypes from April 2007 (pre-Bitcoin:-)
![tribler_e_4 0 0](https://user-images.githubusercontent.com/325224/84158585-55268880-aa6c-11ea-8e59-d3eef6067883.png)
![Tribler_4 1__video_credit_and_detailed_statistics](https://user-images.githubusercontent.com/325224/84158798-90c15280-aa6c-11ea-8792-c92bd054664b.png)
![4_0_0_ profile](https://user-images.githubusercontent.com/325224/84158781-8bfc9e80-aa6c-11ea-8830-e2ffea105714.png)

**Comment by lucy2812** [comment] 2021-11-21 02:14
Since I'm experiencing token drain while not downloading anything, I presume I'm taking away value from fellow Triblers, and it makes me feel bad.

Since I'm not adding value (relaying or being available) to Triblers, should I exit Tribler and not use it?

**Comment by devos50** [comment] 2021-11-21 09:03
@lucy2812 thank you for your report. We have listed potential reasons for a token balance decrease [in our FAQ]. When I'm using Tribler, I noticed that my balance tends to go up and down, and I'm currently slightly in the negative.

> Since I'm not adding value (relaying or being available) to Triblers, should I exit Tribler and not use it?

We appreciate it that you are using Tribler and there is certainly no need to stop using the software :). Keeping Tribler up and running _should_ eventually increase your balance since you have the possibility to help other users (anonymously) download their content. We are also considering different ways to present ones overall performance in the user interface (e.g., "you are in the top X%").

Please let us know if you have any other question!

**Comment by egbertbouman** [comment] 2023-12-12 15:04
It's probably OK to close it, assuming the problem is in the graph itself.

**Closed by egbertbouman** 2023-12-12 15:04 UTC
Labels: type: bug, component: token economy
