### ISSUE TITLE
Add "Download" button to the Channels interface

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4782] opened 2019-08-29 12:21 UTC
Tribler is not easy and intuitive. The underlying cause is that our user interface needs a user-evaluation and bit of polish. After a simple user test it was revealed that it is unclear how to download. Seeing search results and then selecting something does not reveal any instructions or clarity what to do next. We are missing a "***Download***" button. Double click does not work. The nicely looking floating download button is too subtle and difficult to find. Only experts find it.
![Screenshot from 2019-08-29 14-15-53](https://user-images.githubusercontent.com/325224/63939455-a0385780-ca67-11e9-961d-2af8e17a201c.png)

**Comment by ichorid** [comment] 2020-06-11 17:37
duplicate of #4947

**Closed** 2020-12-07 13:27 UTC
Labels: GUI, enhancement
