### ISSUE TITLE
[main] crash when starting with `[chant] enabled = False`

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#6262] opened 2021-08-18 10:48 UTC
Using this config (`http_port` and `key` removed):

```
[api]
    http_enabled = True
    http_port = <redacted>
    key = <redacted>
[chant]
enabled = False
```

Tribler crashes on startup with the following tracebacks:

```python
[PID:2276] 2021-08-18 12:45:28,131 - ERROR <base:161> LibtorrentComponent.start(): Exception in LibtorrentComponentImp.start(): KeyError:'/channels'
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/libtorrent.py", line 48, in run
    rest_manager.get_endpoint(endpoint).download_manager = download_manager
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/restapi/rest_manager.py", line 98, in get_endpoint
    return self.root_endpoint.endpoints['/' + name]
KeyError: '/channels'
[PID:2276] 2021-08-18 12:45:28,138 - ERROR <base:161> TorrentCheckerComponent.start(): Exception in TorrentCheckerComponentImp.start(): ComponentError:Component TorrentCheckerComponentImp has failed dependency LibtorrentComponentImp
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/torrent_checker.py", line 23, in run
    download_manager = (await self.use(LibtorrentComponent)).download_manager
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 187, in use
    raise ComponentError(f'Component {self.__class__.__name__} has failed dependency {dep.__class__.__name__}')
tribler_core.components.base.ComponentError: Component TorrentCheckerComponentImp has failed dependency LibtorrentComponentImp
[PID:2276] 2021-08-18 12:45:28,138 - ERROR <base:161> TunnelsComponent.start(): Exception in TunnelsComponentImp.start(): ComponentError:Component TunnelsComponentImp has failed dependency LibtorrentComponentImp
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/tunnels.py", line 29, in run
    download_manager = (await self.use(LibtorrentComponent)).download_manager
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 187, in use
    raise ComponentError(f'Component {self.__class__.__name__} has failed dependency {dep.__class__.__name__}')
tribler_core.components.base.ComponentError: Component TunnelsComponentImp has failed dependency LibtorrentComponentImp
[PID:2276] 2021-08-18 12:45:28,139 - ERROR <base:161> PopularityComponent.start(): Exception in PopularityComponentImp.start(): ComponentError:Component PopularityComponentImp has failed dependency TorrentCheckerComponentImp
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/popularity.py", line 23, in run
    torrent_checker = (await self.use(TorrentCheckerComponent)).torrent_checker
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 187, in use
    raise ComponentError(f'Component {self.__class__.__name__} has failed dependency {dep.__class__.__name__}')
tribler_core.components.base.ComponentError: Component PopularityComponentImp has failed dependency TorrentCheckerComponentImp
[PID:2276] 2021-08-18 12:45:28,140 - ERROR <base:161> ResourceMonitorComponent.start(): Exception in ResourceMonitorComponentImp.start(): ComponentError:Component ResourceMonitorComponentImp has failed dependency TunnelsComponentImp
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/resource_monitor.py", line 13, in run
    tunnel_community = (await self.use(TunnelsComponent)).community
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 187, in use
    raise ComponentError(f'Component {self.__class__.__name__} has failed dependency {dep.__class__.__name__}')
tribler_core.components.base.ComponentError: Component ResourceMonitorComponentImp has failed dependency TunnelsComponentImp
*** Exception in LibtorrentComponentImp.start(): KeyError:'/channels'


*** Exception in TorrentCheckerComponentImp.start(): ComponentError:Component TorrentCheckerComponentImp has failed dependency LibtorrentComponentImp


*** Exception in TunnelsComponentImp.start(): ComponentError:Component TunnelsComponentImp has failed dependency LibtorrentComponentImp


*** Exception in PopularityComponentImp.start(): ComponentError:Component PopularityComponentImp has failed dependency TorrentCheckerComponentImp


*** Exception in ResourceMonitorComponentImp.start(): ComponentError:Component ResourceMonitorComponentImp has failed dependency TunnelsComponentImp
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 66, in <module>
    start_tribler_core(base_path, api_port, api_key, root_state_dir, gui_test_mode=gui_test_mode)
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/start_core.py", line 120, in start_tribler_core
    loop.run_until_complete(core_session(config, components=list(components_gen(config))))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/start_core.py", line 38, in core_session
    await session.start()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 74, in start
    await gather(*coros, return_exceptions=not self.failfast)
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/libtorrent.py", line 48, in run
    rest_manager.get_endpoint(endpoint).download_manager = download_manager
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/restapi/rest_manager.py", line 98, in get_endpoint
    return self.root_endpoint.endpoints['/' + name]
KeyError: '/channels'
[PID:2230] 2021-08-18 12:45:28,573 - INFO - TriblerGUI(82) - Got Tribler core error: 2
[PID:2230] 2021-08-18 12:45:28,609 - ERROR <error_handler:37> ErrorHandler.gui_error(): tribler_gui.utilities.CreationTraceback: 
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 131, in <module>
    sys.exit(app.exec_())
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 97, in on_request_error
    self.start_tribler_core(core_args=core_args, core_env=core_env)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 177, in start_tribler_core
    connect(self.core_process.finished, self.on_core_finished)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 398, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 87, in on_core_finished
    raise RuntimeError(exception_msg)
RuntimeError: The Tribler core has unexpectedly finished with exit code 1 and status: 0!

Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 66, in <module>
    start_tribler_core(base_path, api_port, api_key, root_state_dir, gui_test_mode=gui_test_mode)
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/start_core.py", line 120, in start_tribler_core
    loop.run_until_complete(core_session(config, components=list(components_gen(config))))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/start_core.py", line 38, in core_session
    await session.start()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 74, in start
    await gather(*coros, return_exceptions=not self.failfast)
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/libtorrent.py", line 48, in run
    rest_manager.get_endpoint(endpoint).download_manager = download_manager
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/restapi/rest_manager.py", line 98, in get_endpoint
    return self.root_endpoint.endpoints['/' + name]
KeyError: '/channels'

(Timestamp: 1629283528610, traceback timestamp: 1629283528394)

[PID:2230] 2021-08-18 12:45:28,613 - INFO - SentryReporter(286) - Event from exception: The Tribler core has unexpectedly finished with exit code 1 and status: 0!

Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 66, in <module>
    start_tribler_core(base_path, api_port, api_key, root_state_dir, gui_test_mode=gui_test_mode)
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/start_core.py", line 120, in start_tribler_core
    loop.run_until_complete(core_session(config, components=list(components_gen(config))))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/start_core.py", line 38, in core_session
    await session.start()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 74, in start
    await gather(*coros, return_exceptions=not self.failfast)
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/base.py", line 158, in start
    await self.run()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/libtorrent.py", line 48, in run
    rest_manager.get_endpoint(endpoint).download_manager = download_manager
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/restapi/rest_manager.py", line 98, in get_endpoint
    return self.root_endpoint.endpoints['/' + name]
KeyError: '/channels'

(Timestamp: 1629283528610, traceback timestamp: 1629283528394)
```

**Comment by kozlovsky** [comment] 2021-08-20 14:00
Thank you for discovering this. The issue should be fixed by PR #6277.

Note that in the strict sense, this bug is not actually a regression bug caused by switching to a new component architecture. If you run the release branch 7.10 with the same option `[chant] enabled = False`, it will not work as well. It seems we don't test Tribler before with disabled modules. Now the component architecture should allow the Tribler code to be truly modularized.

PR #6277 fixes Tribler core initialization when some components are turned off. But the GUI is not fixed yet and should be fixed separately, as some REST endpoints will become unavailable with components turned off. I think fixing the GUI side belongs to a separate issue, as the current issue is focused on the bugs in the component architecture. It is hard to estimate how many changes should be made to the GUI to make it work reliably with different combinations of enabled components. But fixes of this type should be easier now.

**Closed** 2021-08-20 14:31 UTC
Labels: type: bug
