### ISSUE TITLE
Tribler do not show whether torrent contents including folder or just files

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2602] opened 2016-10-28 22:24 UTC
##### Tribler version/branch+revision:

6.5.2
##### Operating system and version:

Windows 10
##### Expected behavior:

When adding new torrent it would be good to know if torrent will create its folder and then inside files or if just files will be downloaded.
##### Actual behavior:

I cant see if it will create its folder. If yes, i can fail and result is: D:\Movies\Movie name\Movie name\movie.avi
When adding torrent for already downloaded data that are in folder named differently, it is a guessing game. I do not see which folder name (if any) torrent requires.
Would be nice to have clue and set own folder names or even be able to rename folders/files but still seed them under original names.

**Comment by slrslr** [comment] 2018-02-10 08:44
There is same feature request, i apologize for duplicity: #2738
I hope torrent file/folder structure can be shown by Tribler and files/folders renamed by user upon adding torrent and after it was added, including renaming on the HDD.

**Comment by ichorid** [comment] 2020-06-12 08:25
duplicate of #1396

**Closed by ichorid** 2020-06-12 08:25 UTC
Labels: enhancement
