### ISSUE TITLE
Notification for RC releases

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4766] opened 2019-08-23 14:40 UTC
We currently only notify the users whenever a new stable new release is out and RC releases go unnoticed to the majority of the users which is even to users already using an RC version if they miss out the forum announcement. As suggested by @ichorid, I think it is a good idea to let people know about RC releases (or even beta) if they are interested so every time there is an RC release they get a notification. 

For this we can:
- Check if the user is already using an older RC version, if yes, notify the user of the new release
- Check if the user has subscribed to get a notification on RC releases, if yes, notify the user. A simple subscription checkbox in the settings should do the job, put simply.

**Comment by ichorid** [comment] 2019-08-24 08:59
I think that notification subscription should be on by default for all versions of Tribler.

**Comment by synctext** [comment] 2019-08-24 09:49
Ai, good we did another RC.

**Comment by synctext** [comment] 2019-08-24 11:57
Normal people don't like Beta versions and dislike upgrading...

**Comment by ichorid** [comment] 2019-08-24 12:31
To make it clear:
 * stable release users should only get notifications about stable releases;
 * beta release users should only get notifications about beta releases.

> Normal people don't like Beta versions and dislike upgrading...
That is true. But Tribler is oriented towards more advanced users, who are concerned with their security. Security-concerned users know that timely updates are critical for maintaining security. Therefore, I would argue that stable->stable and beta->beta notifications are necessary.

**Comment by synctext** [comment] 2019-08-25 10:24
Now I get it. Good idea of splitting into Stable and RC notifications. Different people.

**Comment by devos50** [comment] 2019-09-04 09:45
We could use the fact that the Github API includes information on whether a release is a pre-release or not. Or we could parse the name of the release (which uses consistent formatting) and check whether a release is a beta/rc/stable release.

**Comment by devos50** [comment] 2020-04-01 14:37
Would be very nice to have but not feasible for the 7.5 release.

**Comment by ichorid** [comment] 2020-06-12 07:47
A similar idea was coined in previously: #2091

**Comment by qstokkink** [comment] 2024-08-12 09:26
Agreed with @ichorid, duplicate of #2091: please move the discussion there.

**Closed by qstokkink** 2024-08-12 09:26 UTC
Labels: type: enhancement, component: refactoring
