### ISSUE TITLE
Port the community crawler to IPv8

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5263] opened 2020-04-01 14:46 UTC
Currently, we have a peer crawler running which information is displayed [here](http://statistics.tribler.org). This crawler, however, still uses Python 2. It also seems that the crawler itself is unstable in a sense that the time between two data points varies much.

We should port this crawler and improve it, to get more accurate statistics of the number of online users in the network.

**Comment by qstokkink** [comment] 2020-04-01 14:47
Well we broke some edge cases for wire format with Dispersy. So we can't upgrade that any further without losing information.

**Comment by qstokkink** [comment] 2020-04-01 14:48
> the time between two data points varies much.

This is usually caused by REST requests that are too aggressive or a lack of disk space.

**Comment by triblerteam** [comment] 2020-04-02 13:57
> Well we broke some edge cases for wire format with Dispersy. 

Which Tribler releases are we no longer seeing in the DiscoveryCommunity if we move to Python3?

**Comment by qstokkink** [comment] 2020-04-02 14:14
> 
> 
> > Well we broke some edge cases for wire format with Dispersy.
> 
> Which Tribler releases are we no longer seeing in the DiscoveryCommunity if we move to Python3?

Everything up through `7.2`. For context, we can see from the RTTs of the trackers that even Dispersy is still being used in the wild: https://jenkins-ci.tribler.org/job/Test_BootstrapServers/15341/

**Comment by qstokkink** [comment] 2020-09-25 12:48
The crawler is dead, long live the crawler. I believe we just need to restart the service to resolve this issue now?

**Comment by xoriole** [comment] 2021-07-14 13:32
The crawler is dead. Closing the issue.

**Closed by xoriole** 2021-07-14 13:32 UTC
Labels: component: refactoring, type: bug, type: enhancement
