### ISSUE TITLE
Token balance suddenly jumped way up

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#5823] opened 2020-12-08 21:52 UTC
##### Tribler version/branch+revision: #####

v7.6.0-exp1

##### Operating system and version: #####

Linux, running in Docker

##### Steps to reproduce the behavior: #####

1. Start tribler, enable exit point, don't have any serious downloads, leave overnight
2. Observe token balance

##### Expected behavior: #####

Token balance grows steadily

##### Actual behavior: #####

Token balance grown to about 200-300GB overnight, but then, when I checked the next time (within an hour) it was 2.5TB, which seems to be unrealistic to obtain in such a short amount of time.

The plot is function is almost useless - I can't zoom it in properly (axes are always zoomed together) and I don't see anything like export to CSV.

**Comment by devos50** [comment] 2020-12-09 09:50
Thanks for reporting! We are aware of this problem and we have identified the root cause, also see https://github.com/Tribler/tribler/issues/5789#issuecomment-739980868. In 7.6.0, we have hidden the token balance as a temporary solution and we plan to show it again when the issue has been fixed, and when we have implemented a few other improvements.

Since this issue is a duplicate of #5789, I will close this one.

**Closed by devos50** 2020-12-09 09:50 UTC
