### ISSUE TITLE
exceptions.KeyError: 'e'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1889] opened 2016-01-21 14:37 UTC
On Ubuntu 15.10 when streaming a torrent the view fails to switch to the videoplayer. (only first time after fresh search and startup)

```
CRITICAL 1453386919.82         _legacy:154   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/Tribler/dispersy/endpoint.py", line 250, in dispersythread_data_came_in
    u"standalone_ep")
  File "/usr/lib/python2.7/dist-packages/Tribler/dispersy/dispersy.py", line 1462, in on_incoming_packets
    community.on_incoming_packets(list(iterator), cache, timestamp, source)
  File "/usr/lib/python2.7/dist-packages/Tribler/dispersy/community.py", line 2023, in on_incoming_packets
    self._on_batch_cache(meta, batch)
  File "/usr/lib/python2.7/dist-packages/Tribler/dispersy/community.py", line 2080, in _on_batch_cache
    messages.append(conversion.decode_message(candidate, packet, source=source))
  File "/usr/lib/python2.7/dist-packages/Tribler/dispersy/util.py", line 151, in wrapper
    return_value = func(*args, **kargs)
  File "/usr/lib/python2.7/dist-packages/Tribler/dispersy/conversion.py", line 1219, in decode_message
    placeholder.offset, placeholder.payload = decode_functions.payload(placeholder, placeholder.offset, payload)
  File "/usr/lib/python2.7/dist-packages/Tribler/community/search/conversion.py", line 126, in _decode_search_response
    offset, payload = decode(data, offset)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Utilities/encoding.py", line 334, in decode
    return _a_decode_mapping[stream[index]](stream, index + 1, int(stream[offset + 1:index]), _a_decode_mapping)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Utilities/encoding.py", line 251, in _a_decode_tuple
    offset, value = mapping[stream[index]](stream, index + 1, int(stream[offset:index]), mapping)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Utilities/encoding.py", line 217, in _a_decode_list
    offset, value = mapping[stream[index]](stream, index + 1, int(stream[offset:index]), mapping)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Utilities/encoding.py", line 251, in _a_decode_tuple
    offset, value = mapping[stream[index]](stream, index + 1, int(stream[offset:index]), mapping)
exceptions.KeyError: 'e'
```

**Comment by whirm** [comment] 2016-01-21 14:40
does it happen if you run from `next`instead of the .deb?

**Comment by synctext** [comment] 2016-01-21 16:55
git log | head
commit af1e903e7fd2ba84b59a976f4d99d56dc354e677
Author: Elric Milon <whirm@users.noreply.github.com>
Date:   Thu Jan 21 15:57:24 2016 +0100

    Merge pull request #1890 from whirm/install_dir_hack_for_ubuntu
    
    Install dir hack for ubuntu

**Comment by synctext** [comment] 2016-01-21 17:02
Sadly, still same. btw The /tmp/*log file is gone, a new directory in /tmp is empty.

git log |head
commit af1e903e7fd2ba84b59a976f4d99d56dc354e677
Merge: c31a011 893ca8b
Author: Elric Milon <whirm@users.noreply.github.com>
Date:   Thu Jan 21 15:57:24 2016 +0100

    Merge pull request #1890 from whirm/install_dir_hack_for_ubuntu
    
    Install dir hack for ubuntu

**Comment by whirm** [comment] 2016-01-22 08:04
This stacktrace doesn't look related to Tribler not switching to the video tab properly.

**Comment by whirm** [comment] 2016-01-22 08:09
Can you reproduce the stacktrace consistently? If so, can you provide step by step instructions on how to reproduce that? 
Apparently the search community is receiving a corrupt message.

**Comment by synctext** [comment] 2016-01-22 12:40
Consistent 100% reproducible on my 15.10 Ubuntu machine.
1. clean start tribler
2. search pioneer
3. click "stream"  on an entry not yet downloaded
4. it does not switch to video-player view.

Shoot, now Tribler even get's stuck with frozen screen with step 1-4. Never seen that in past months. No log entries in /tmp/

**Comment by whirm** [comment] 2016-01-22 13:39
@synctext I was talking about the KeyError exception, I just fixed the streaming bug.

**Comment by whirm** [comment] 2016-01-22 13:42
@synctext could you try this branch https://github.com/Tribler/tribler/pull/1892 and tell me if it fixes it for you too?

**Comment by synctext** [comment] 2016-01-22 14:15
Excellent. Fix seems to work, testing some more.

**Comment by synctext** [comment] 2016-01-22 14:15
Streaming fast after startup.
```
./tribler.sh 
[00007f061c00b918] avi demux error: no key frame set for track 0
[00007f061c00b918] avi demux error: no key frame set for track 1
[00007f061c00b918] avi demux error: no key frame set for track 0
[00007f061c00b918] avi demux error: no key frame set for track 1
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
[00007f05d80107d8] mpgatofixed32 audio converter error: libmad error: bad main_data_begin pointer
ERROR   1453471941.67     VideoServer:154   sent wrong amount, wanted 359953384 got 48856
[00007f05d80107d8] mpgatofixed32 audio converter error: libmad error: bad main_data_begin pointer
[mpeg4 @ 0x7f061c026d80] header damaged
[mpeg4 @ 0x7f061c026d80] header damaged
ERROR   1453471943.06     VideoServer:154   sent wrong amount, wanted 366716172 got 6811644
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 201, in <lambda>
    lm_network_engine_wrapper_created_callback, pstate, initialdlstatus)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 248, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 251, in add_torrent
    handle = ltsession.add_torrent(encode_atp(atp))
exceptions.RuntimeError: torrent already exists in session

CRITICAL 1453471944.31         _legacy:154   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 201, in <lambda>
    lm_network_engine_wrapper_created_callback, pstate, initialdlstatus)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 248, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 251, in add_torrent
    handle = ltsession.add_torrent(encode_atp(atp))
exceptions.RuntimeError: torrent already exists in session

```

**Comment by synctext** [comment] 2016-01-22 14:28
Hmm, Tribler does not like it when you're doing stuff quickly after startup.
Essential trick to reproduce: I'm searching results for "pioneer" already, even before the "pioneer" files I'm seeding are done initialising or done building circuits for anonymous seeding of them!

```
./tribler.sh
[00007f29c0001278] core stream error: cannot pre fill buffer
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoServer.py", line 43, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoServer.py", line 57, in __init__
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoServer.py", line 130, in do_GET
    stream, lock = self.videoplayer.get_vod_stream(downloadhash, wait=True)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoPlayer.py", line 119, in get_vod_stream
    self.vod_info[dl_hash]['stream'] = (VODFile(open(vod_filename, 'rb'), download), RLock())
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 43, in __init__
    self.startpiece = self._download.handle.get_torrent_info().map_file(self._download.get_vod_fileindex(), 0, 0)
AttributeError: 'NoneType' object has no attribute 'get_torrent_info'
```

**Comment by synctext** [comment] 2016-01-22 14:32
Error when clicking a "pioneer" file from sarch result which was already seeding (not easy to reproduce):
```
[00007f29c00014e8] core stream error: cannot pre fill buffer
[00007f29c0c0ba28] avi demux error: no key frame set for track 0
[00007f29c0c0ba28] avi demux error: no key frame set for track 1
[00007f29c0c0ba28] avi demux error: no key frame set for track 0
[00007f29c0c0ba28] avi demux error: no key frame set for track 1
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoServer.py", line 43, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoServer.py", line 57, in __init__
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoServer.py", line 130, in do_GET
    stream, lock = self.videoplayer.get_vod_stream(downloadhash, wait=True)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoPlayer.py", line 116, in get_vod_stream
    vod_filename = self.get_vod_filename(download)
  File "/usr/lib/python2.7/dist-packages/Tribler/Core/Video/VideoPlayer.py", line 150, in get_vod_filename
    return os.path.join(download.get_content_dest(), download.get_selected_files()[0])
IndexError: list index out of range
```

**Comment by whirm** [comment] 2016-01-22 14:40
All these are unrelated to this issue, please create separate issues so they can be dealt with individually otherwise it becomes a mess to follow up.

**Comment by synctext** [comment] 2016-01-22 14:46
True, I came across 3 unique error messages + a full-freeze.
Plus the issue of this ticket itself is not resolved in this commit. Bit it seems to occur less.
```
git log |head
commit ecee3d7020f56caba1b358f57ec3e1efff2694ed
Author: Elric Milon <whirm@gmx.com>
Date:   Fri Jan 22 14:38:43 2016 +0100

    Fix clicking on the 'stream' button before the .torrent has been fetched.
```

**Comment by synctext** [comment] 2016-01-22 14:48
Seems unrelated to fetching torrent, see the left-hand-side state of the videoplayer
![fetching_torrent](https://cloud.githubusercontent.com/assets/325224/12513699/7d8892cc-c11f-11e5-8498-473f1a0536cb.png)

**Comment by whirm** [comment] 2016-01-22 14:49
I wasn't trying to fix this ticket but the streaming window issue, the original traceback happened because the community got a search result message which is corrupted or not properly encoded.

**Comment by synctext** [comment] 2016-01-22 14:56
Yes, I saw the magical ```_decode_search_response``` hint you found. Never seen the original exceptions.KeyError: 'e' happening.

Streaming windows issue is still there in your branch, also when .torrent is there. See again the left-hand-side state of videoplayer.
![no_screen_switch_to_video_player](https://cloud.githubusercontent.com/assets/325224/12513870/6e0baf36-c120-11e5-9c30-b399d60302ec.png)

**Comment by whirm** [comment] 2016-01-22 15:03
Weird, it's working just fine here:
![2016-01-22-160200_1920x1080_scrot](https://cloud.githubusercontent.com/assets/529494/12514070/a7358c68-c121-11e5-9539-0026880a4eac.png)

**Comment by synctext** [comment] 2016-01-22 15:08
@whirm  Can you try a few times: start Tribler, quickly search pioneer, pre-position the mouse already, click stream button on an incoming search result entry. Then it freeses Tribler in seconds after startup.

Hmm, possibly this only works if you're seeding a dozen files and introduce init delay.

**Comment by whirm** [comment] 2016-01-22 15:18
Ok, I managed to reproduce it once, but you have to be super fast to pull it. 

I'd say it's because of this:

https://github.com/Tribler/tribler/blob/71377341ac2fc59b2c9f5efbda81e71115303622/Tribler/Core/Video/VLCWrapper.py#L48

I don't think that's a bug a normal user will trigger and it will probably not be easy at all to fix.

**Comment by synctext** [comment] 2016-01-22 15:35
There is a 2GByte megacache that might slow your init time, mughal: /home/tribler/Tribler_Megacache/Tribler_Megacaches_2016/

**Comment by whirm** [comment] 2016-01-25 09:50
Let's discuss this other bug in a separate issue.

Do you agree this (#1889 bug) to post 6.5? It appears to be a cosmetic issue, but I want to have a closer look at it.

**Comment by devos50** [comment] 2016-03-26 10:56
This issue should be fixed when the new GUI goes live since then vlc will not be part of the Tribler core anymore. So I'm not sure whether it is worth spending time to investigate this one.

**Comment by whirm** [comment] 2016-03-29 16:35
I agree.

Let's close it, nobody has complained about this and you really have to try to trigger it.

**Closed by whirm** 2016-03-29 16:35 UTC
Labels: bug
