### ISSUE TITLE
Tribler things the download is complete, but it is not.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2493] opened 2016-07-25 23:20 UTC
##### Tribler version/branch+revision:

e1629c19ffeec2d796802e8c3dd359d25a222984 devel
##### Operating system and version:

Linux Debian
##### Steps to reproduce the behavior:
- Add more files to partial download
- Watch the percentage
##### Expected behavior:
- Download looks completed when all files (including newly included) are actually downloaded.
##### Actual behavior:
- Inlcuding more files did not decrease the overall download percentage. After reaching "100%" it is not downloading more (although files are with holes) and is seeding instead.

It probably wasn't so on 63f49df.

"Force recheck"  does not help.

Workaround: roll back to 63f49df, force recheck, exclude those files again and re-include them.

**Comment by devos50** [comment] 2017-01-04 11:11
I'm unable to reproduce this in my latest PR #2691 where I fixed the include/exclude bug. @vi can you try to reproduce it in this PR?

**Comment by devos50** [comment] 2017-01-11 15:48
This was probably due to the issue with included files not working correctly. I suppose it has been fixed now and I haven't encountered it recently.

**Closed by devos50** 2017-01-11 15:48 UTC
Labels: bug
