### ISSUE TITLE
Removing an anonymous download, then re-download gives error

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1612] opened 2015-08-26 15:49 UTC
start an anonymous download, start streaming, remove only the torrent from download (not the data).
Add same magnet link again, start streaming same file. error.
```
./tribler.sh 
[0x7f5ad8003aa8] main stream error: cannot pre fill buffer
[0x7f5ad8003dd8] main stream error: cannot pre fill buffer
ERROR   1440603974.59             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 200, in <lambda>
    lm_network_engine_wrapper_created_callback, pstate, initialdlstatus)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 247, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 239, in add_torrent
    handle = ltsession.add_torrent(encode_atp(atp))
exceptions.RuntimeError: torrent already exists in session

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 200, in <lambda>
    lm_network_engine_wrapper_created_callback, pstate, initialdlstatus)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 247, in network_create_engine_wrapper
    self.handle = self.ltmgr.add_torrent(self, atp)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 239, in add_torrent
    handle = ltsession.add_torrent(encode_atp(atp))
exceptions.RuntimeError: torrent already exists in session
```

**Comment by whirm** [comment] 2015-09-11 15:07
I can't reproduce it.
@synctext can you?

**Comment by whirm** [comment] 2015-10-29 17:22
Note to future me: #1684 has info on how to reproduce this one.

**Comment by whirm** [comment] 2016-01-04 08:28
@synctext I've repeated the steps described a bunch of times and I can't reproduce it anymore  on `next` (many fixes have been merged since you opened this issue), closing it but it would be nice if you could check on your side and reopen the issue if it's not fixed.

**Closed by whirm** 2016-01-04 08:28 UTC
Labels: bug

**Comment by synctext** [comment] 2016-01-04 08:46
OK, getting ready for a release slowly..
