### ISSUE TITLE
Tribler 7.0.0-alpha1-47-gaa92b5f crashes on attempting to add two or more torrents at the same time.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2666] opened 2016-11-29 21:10 UTC
System:
Windows 10 computer
Tribler_7.0.0-alpha1-47-gaa92b5f_x64
Fresh install of Tribler.

Error: http://i.imgur.com/ZHpQBYG.png

Steps to reproduce: 

Have tribler opened, "run" two torrents. Press download on the first torrent, as the window opens. Upon pressing download on the second torrent, Tribler crashes with the error above. 

Update: Same applies to magnet links, but they don't work. (Creating different issue) Cancelling the second download still crashes Tribler, with this error: http://i.imgur.com/FKoRaRH.png

**Comment by devos50** [comment] 2016-11-30 07:38
Thanks for the report!

Regarding the second issue, can you create a separate issue for that? It shouldn't be that hard to fix 👍

**Comment by Thomasedv** [comment] 2016-11-30 07:54
Done :) Changed this issue to only have relevant information.

**Comment by devos50** [comment] 2017-01-22 16:20
I've found the root cause of the error and I've refactored the mechanism to add a torrent file in the GUI. This will be fixed in the next alpha release.

**Closed** 2017-01-22 18:11 UTC
Labels: bug
