### ISSUE TITLE
Token balance decreasing

### ISSUE THREAD

**Issue by lucy2812** [Tribler/tribler#6164] opened 2021-06-15 20:37 UTC
#### Please, fill all relevant items: ####

- [X] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

v7.9.0

##### Expected behavior: #####

Token balance to increase over time when there's nothing to download.
The balance would increase because I'm contributing as a node relay to help others.

##### Actual behavior: #####

Token balance is decreasing, yet there are no downloads.
This has been happening for weeks, but my graph doesn't show that timeline because I restarted the application.

![HkHkp0tUFA](https://user-images.githubusercontent.com/85310065/122119994-680b3000-ce19-11eb-9ba0-7d1dad738da1.png)

##### Other: #####

There are no downloads that would reduce token balance.

![pOPLSGKrqr](https://user-images.githubusercontent.com/85310065/122119169-67be6500-ce18-11eb-8ccc-20a8c90acbb2.png)

![29p5N9KhOG](https://user-images.githubusercontent.com/85310065/122119770-19f62c80-ce19-11eb-9d96-61c5bfc0ab1c.png)

**Comment by ichorid** [comment] 2021-06-17 17:05
This might be the result of the "tokens black hole" problem that happens when someone with non-Tribler client downloads stuff that you seed anonymously. In that case, the downloader will not pay you, and you will still lose tokens because of the BitTorrent technical traffic, such as DHT, packet confirmation, etc.

We are slowly fixing the issues with token accounting, but there are still problems. Could you please try 7.10-RC1?

**Comment by User486375** [comment] 2021-06-18 16:15
@ichorid I have a similar issue to this and have only just started trying out tribler for the third time. When I leave tribler open to relay in non-exit mode, my given increases at the same amount as my taken from the community most of the time. I thought it may be my subscription to channels or the single torrent I had seeding (despite it not seeding at all during this period of time). So I disabled all channel subscriptions, stopped the single torrent and even set its anonymity to no anonymity, so it wouldn't have any circuits built even while disabled. Yet to no avail, my token balance stayed steadily in the negative. I also tried upgrading to 7.10.0-RC1 which made no difference. All in all, over the course of a few days my given has increased by 1900MBs and my taken increased by 1400MBs. Resulting in only a 500MB increase in token balance, which is unsustainable for continued use. All I can think of is my client identity still being new causing it to still be discovering new relays on the network, or my client still discovering torrents from a large channel despite having unsubscribing days ago.

**Comment by devos50** [comment] 2021-06-23 08:49
Thanks for reporting! There are several dynamics going on with our bandwidth token payouts. I have extended [the FAQ on the website](https://www.tribler.org/faq) with some explanation on how the token payouts work, and describe what could possibly cause a sudden decrease in token balance.

Since this issue is essentially a duplicate of #5310, please continue the discussion there (I would like to have a single issue for discussing token balances) 👍 .

**Closed by devos50** 2021-06-23 08:49 UTC
Labels: status: broken
