### ISSUE TITLE
Log spam regarding bootstrap download

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4893] opened 2019-10-13 13:34 UTC
When running Tribler (7.3.1-RC3) for the first time, I get the following log message spammed in my console:

```
ERROR   1570973414.49                 bootstrap:57   (Bootstrap)  Failed to get DHT response:No nodes found in the routing table
```

This line is spammed **11.443 times** in my console within seconds. After a while, it seems to do direct payouts but my balance does not decrease. Finally, it continuously prints the following line:

```
Bootstrap download not flushed yet, rescheduling
```

**Comment by ichorid** [comment] 2019-10-13 16:23
Reproduced this on Ubuntu. The problem seems to be that Tribler DHT is not ready to serve requests, but we still go through the whole list of peers. I would prefer a fix where the bootstrap process is only launched after DHT is ready. @egbertbouman ,  what would you say?

**Comment by xoriole** [comment] 2019-11-27 14:07
Fixed by https://github.com/Tribler/tribler/pull/4971

**Closed by xoriole** 2019-11-27 14:07 UTC
Labels: bug
