### ISSUE TITLE
Error when updating Tribler saying it contains virus or potentially unwanted software

### ISSUE THREAD

**Issue by KDAM71** [Tribler/tribler#7929] opened 2024-03-14 18:02 UTC
I tried to update Tribler through Winget and manually by downloading https://github.com/Tribler/tribler/releases/download/v7.13.3/Tribler_7.13.3_x64.exe. During installation I got an error window stating "Operation did not complete succesfully because the file contains a virus or potentially unwanted software"

I'm using windows 11 home 22H2, windows defender versions:
Windows Security Application Version: 1000.25992.0.9000
Windows Security Service Version: 1.0.2311.17002-0
Antimalware Client Version: 4.18.24020.7
Engine Version: 1.1.24020.9
Antivirus Version: 1.407.422.0
Antispyware Version: 1.407.422.0

![Screenshot 2024-03-14 171633](https://github.com/Tribler/tribler/assets/128472955/5f13099b-f9e3-4e46-aacb-3b553f785086)

**Comment by xoriole** [comment] 2024-03-15 09:51
@KDAM71 Thank you for your report. 

It is a false report caused by the packaging software we use (PyInstaller, also open source) for building the .exe file. 
@kozlovsky from Tribler Team has submitted a report to Windows regarding the false flagging and now waiting for their response.

**Comment by 7gxycn08** [comment] 2024-04-26 07:15
Why not Compile Tribler to c using Nuitka It should solve the false positives thrown by defender.

False positives ruin the reputation of the project.

**Comment by xoriole** [comment] 2024-04-29 08:17
@7gxycn08 Thank you for the suggestion. I'll explore building Tribler with Nuitka.

**Comment by qstokkink** [comment] 2024-08-19 11:43
This issue has high overlap with #5648, I'll close this issue and I want to direct discussion toward that issue.

**Closed by qstokkink** 2024-08-19 11:43 UTC
Labels: type: bug
