### ISSUE TITLE
Tribler 8 won't load in any browser

### ISSUE THREAD

**Issue by Lotechus** [Tribler/tribler#8279] opened 2024-11-28 18:26 UTC
Upgraded to Tribler 8, launches a completely blank browser window.  First, I don't want to run this in a browser, and secondly it doesn't see to be working properly.  I use other localhost/127 programs without issue, however tribler loads an empty window. 

Frustrating as the previous version isn't listed for download on the website.

**Comment by synctext** [comment] 2024-11-28 19:48
We will surely help to fix this!

https://github.com/tribler/tribler/releases
Are all prior releases.
Could you give us a bit more info on what OS and browser you are running? Plus please let us know the exact URL the browser is showing?
This sadly will be a wider issue if it fails for you. We liked the old GUI also more, but unfortunately Python QT GUI is very difficult. Everything should be faster and anonymous streaming looks possible now in the browser. That's our 8.1 release aim.

**Comment by InSimpleTermsJordan** [comment] 2024-11-28 20:00
Same issue here.
`http://127.0.0.1:65081/ui/#/downloads/all?key=<redacted because idk if this is supposed to be private>`
Windows 10 Home 22H2 build 19045.5131
Firefox Developer Edition 134.0b2 (64-bit)

**Comment by Lotechus** [comment] 2024-11-28 20:08
I've already downgraded from a backup, but thank you for the releases link.
Windows 10 Pro, tried in Firefox and Chrome.  Disabled my firewall temporarily to test.  Browsers and Windows up to date.  The URL is similar to the version "InSimpleTermsJordan" posted, starting with 127.0.0.1:65081/ui/# etc.
I use local webservers to test development sites, as well as local AI all which work either with localhost or 127.0.0.1 addresses.  They were not running at the time of testing Tribler.
Thanks!

**Comment by Lotechus** [comment] 2024-11-28 20:16
Also if this is running in a browser in future releases, could it look at PWA, so we can do something like this;
https://www.howtogeek.com/turn-websites-into-desktop-apps-on-windows-11/
to utilize Chrome or Edge to launch this in a separate window with their own icon.  :)

**Comment by egbertbouman** [comment] 2024-11-29 10:59
Is the window really empty, or is there some kind of error somewhere?
This could be an issue with the server itself, or a specific endpoint. To test this, could someone please try accessing `http://127.0.0.1:<yourport>/api/downloads?key=<yourkey>`, and let us know if there is any output.

**Comment by Lotechus** [comment] 2024-11-29 16:32
Was blank for me.

**Comment by davidgordiienko** [comment] 2024-11-29 18:18
For me after a while some program called xmessage opens up and it says "Database is locked" so I think there's some sort of error

**Comment by kotlinbuddy** [comment] 2024-12-05 16:09
Mozilla
Loading module from “http://127.0.0.1:64869/ui/assets/index.9ee516a5.js” was blocked because of a disallowed MIME type (“text/plain”).

Chrome
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec. http://127.0.0.1:64869/ui/assets/index.9ee516a5.js

**Comment by kotlinbuddy** [comment] 2024-12-05 16:22
Tried the latest build shared https://github.com/Tribler/tribler/actions/runs/12182098649, same issues as above.

**Comment by qstokkink** [comment] 2024-12-06 08:52
Thanks for testing! `blocked because of a disallowed MIME type (“text/plain”)` seems to be the core issue for you then (and not database locking). We were looking in the wrong place and now that we know where to look, we may be able to fix this.

**Comment by qstokkink** [comment] 2024-12-06 09:25
_[dev stuff]_ After reading up on this error, I think the following is going on:

- To serve page content we use Python's `mimetypes.guess_type`, here:

https://github.com/Tribler/tribler/blob/417ce08d2df839a5eab560a234b745f4e556ec14/src/tribler/core/restapi/webui_endpoint.py#L45-L46

- Inside the Python interpreter, this is implemented by [checking the Windows registry](https://github.com/python/cpython/blob/3.13/Lib/mimetypes.py#L32).

- I've seen various user reports online that the registry value `HKEY_CLASSES_ROOT\.js` `Content Type` was **not set to** `application/javascript`. In turn, this causes javascript files to not be served as javascript.

I think the fix for this _might_ be as easy as adding a custom check for `.js` postfixes to our own `webui_endpoint.py`.

**Comment by qstokkink** [comment] 2024-12-06 09:47
_[dev stuff]_ Reproduced! Steps:

 1. I set my registry value for `.js` to `text/plain`.
 2. I ran using `npm run build` (`npm run dev` works correctly - this does not reproduce the issue!).

**Closed** 2024-12-06 10:06 UTC
Labels: type: bug
