### ISSUE TITLE
Failed to execute script run_tribler

### ISSUE THREAD

**Issue by FPSUsername** [Tribler/tribler#3702] opened 2018-06-30 13:18 UTC
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.0.2 (x86 & x64) and 7.1.0 pre release (x64)

##### Operating system and version: #####
Windows 10 pro x64

##### Steps to reproduce the behavior: #####
Clean install of tribler, then start it for the first time

##### Expected behavior: #####
program starts (duh)

##### Actual behavior: #####
Failed to execute script run_tribler

![untitled](https://user-images.githubusercontent.com/10143926/42125501-9d0a0182-7c78-11e8-8098-070293a5ca77.png)

##### Other info: #####
I have python 2.7.15 and python 3.6.5 installed on my desktop in `D:\Users\USERNAME\AppData\Local\Programs\Python\PythonXX`

I installed the module `service_identity` using pip (python 2), no luck there.

**Comment by qstokkink** [comment] 2018-06-30 13:56
There seems to be something changing the character encoding in your environment.

As a workaround, could you try running tribler from `Windows Powershell`?

**Comment by devos50** [comment] 2018-06-30 14:03
Related SO post: https://stackoverflow.com/questions/35176270/python-2-7-lookuperror-unknown-encoding-cp65001

it might be caused by the console window that we enable for these experimental releases. One suggested fix for this could be to [bundle this package](https://github.com/Drekin/win-unicode-console).

**Comment by FPSUsername** [comment] 2018-06-30 14:41
@qstokkink I tried running it through powershell, I get the same error
@devos50 if I check pip or pip3 --version, it works fine.
For the console window, well, I get the same error in a nice warning/error window on the stable release, so it doesn't change the situation.

**Comment by qstokkink** [comment] 2018-07-01 08:54
I was able to reproduce and fix this.

```python
import codecs

def remapped_mbcs(_):
    mbcs_codec = codecs.lookup('mbcs')
    return codecs.CodecInfo(
        name='cp65001',
        encode=mbcs_codec.encode,
        decode=mbcs_codec.decode,
        incrementalencoder=mbcs_codec.incrementalencoder,
        incrementaldecoder=mbcs_codec.incrementaldecoder,
        streamreader=mbcs_codec.streamreader,
        streamwriter=mbcs_codec.streamwriter,
	)
codecs.register(remapped_mbcs) # Comment this out for the first run.

print u'\u0070'
```

```
>chcp 65001
Active code page: 65001

>python test.py
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    print u'\u0070'
LookupError: unknown encoding: cp65001

>python test.py
p
```

Now we need to figure out where to put this and how to recognize we are running on code page `65001` on the user system.

**Closed** 2018-07-03 13:08 UTC
Labels: bug
