### ISSUE TITLE
sqlite 3 OperationalError: unrecognized token

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4757] opened 2019-08-16 19:29 UTC
v7.3-RC2.
Happens every 2nd attempt to run Tribler both on Windows and on Linux at the end of the GUI bootup.

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'6134643462646F776E38693135383530303032313062746F74616C5F646F776E31314A3837323337323032313737326275703169303862746F746"
lib\threading.py:801:__bootstrap_inner
lib\threading.py:754:run
lib\site-packages\twisted\_threads\_threadworker.py:46:work
lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
lib\site-packages\twisted\python\threadpool.py:250:inContext
lib\site-packages\twisted\python\threadpool.py:266:<lambda>
lib\site-packages\twisted\python\context.py:122:callWithContext
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:546:sesscb_states_callback
ipv8\database.py:56:wrapper
ipv8\database.py:333:executescript
]
```

**Comment by ichorid** [comment] 2019-08-16 19:29
@qstokkink , please look at this.

**Comment by qstokkink** [comment] 2019-08-17 06:26
This happens when you feed a bad query to the database (see https://stackoverflow.com/a/11160750). Though the stacktrace is very limited, it seems to be something in Tribler listening to the event `self.session.notifier.notify(NTFY_TORRENT, NTFY_FINISHED, infohash, safename, is_hidden)`.

As I can't reproduce this, I'll unassign myself.

**Comment by grimadas** [comment] 2019-08-20 13:02
I couldn't reproduce it. Let me know if you see it again

**Comment by ichorid** [comment] 2019-09-14 14:02
It is still there. An it is the most frequent error in the reporter. It has three different forms:
17 traces:
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'6134643462646F776E316930"
lib\threading.py:801:__bootstrap_inner
lib\threading.py:754:run
lib\site-packages\twisted\_threads\_threadworker.py:46:work
lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
lib\site-packages\twisted\python\threadpool.py:250:inContext
lib\site-packages\twisted\python\threadpool.py:266:<lambda>
lib\site-packages\twisted\python\context.py:122:callWithContext
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:547:sesscb_states_callback
ipv8\database.py:56:wrapper
ipv8\database.py:333:executescript
]
```

2 traces:
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 114, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'4C69624E61434C504B3A6BBB8343434E52384379B62E4306A7BA4525A6C829535EACAE"
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
/usr/lib/python2.7/threading.py:754:run
/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py:46:work
/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:250:inContext
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/lib/python2.7/dist-packages/twisted/python/context.py:122:callWithContext
/usr/lib/python2.7/dist-packages/twisted/python/context.py:85:callWithContext
/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py:547:sesscb_states_callback
/usr/share/tribler/Tribler/pyipv8/ipv8/database.py:56:wrapper
/usr/share/tribler/Tribler/pyipv8/ipv8/database.py:333:executescript
]
```
Again 2 traces:
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'6134643462646F776E38693135383530303032313062746F74616C5F646F776E31314A3837323337323032313737326275703169303862746F746"
lib\threading.py:801:__bootstrap_inner
lib\threading.py:754:run
lib\site-packages\twisted\_threads\_threadworker.py:46:work
lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
lib\site-packages\twisted\python\threadpool.py:250:inContext
lib\site-packages\twisted\python\threadpool.py:266:<lambda>
lib\site-packages\twisted\python\context.py:122:callWithContext
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:547:sesscb_states_callback
ipv8\database.py:56:wrapper
ipv8\database.py:333:executescript
]
```

1 trace
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 114, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'4C69624E61434C504B3A"
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
/usr/lib/python2.7/threading.py:754:run
/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py:46:work
/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:250:inContext
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/lib/python2.7/dist-packages/twisted/python/context.py:122:callWithContext
/usr/lib/python2.7/dist-packages/twisted/python/context.py:85:callWithContext
/usr/share/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py:547:sesscb_states_callback
/usr/share/tribler/Tribler/pyipv8/ipv8/database.py:56:wrapper
/usr/share/tribler/Tribler/pyipv8/ipv8/database.py:333:executescript
]
```

Again 1 trace:
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'4C69624E61434C504B3A396F7167CF"
lib\threading.py:801:__bootstrap_inner
lib\threading.py:754:run
lib\site-packages\twisted\_threads\_threadworker.py:46:work
lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
lib\site-packages\twisted\python\threadpool.py:250:inContext
lib\site-packages\twisted\python\threadpool.py:266:<lambda>
lib\site-packages\twisted\python\context.py:122:callWithContext
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:547:sesscb_states_callback
ipv8\database.py:56:wrapper
ipv8\database.py:333:executescript
]
```

More traces:
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'4C69624E61434C504B3AF5452BAB21A484D3FBE601A9BAAD7D748C71218A17FAB37053C93FFC05E6A578606133916822B5652FBF8BE2"
lib\threading.py:801:__bootstrap_inner
lib\threading.py:754:run
lib\site-packages\twisted\_threads\_threadworker.py:46:work
lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
lib\site-packages\twisted\python\threadpool.py:250:inContext
lib\site-packages\twisted\python\threadpool.py:266:<lambda>
lib\site-packages\twisted\python\context.py:122:callWithContext
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:547:sesscb_states_callback
ipv8\database.py:56:wrapper
ipv8\database.py:333:executescript
]
```

```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: unrecognized token: "X'75952A1C887DBF74B1A30FB179D93EC6C58EA47D0A3BB928FCECF80D4D2CED"
lib\threading.py:801:__bootstrap_inner
lib\threading.py:754:run
lib\site-packages\twisted\_threads\_threadworker.py:46:work
lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
lib\site-packages\twisted\python\threadpool.py:250:inContext
lib\site-packages\twisted\python\threadpool.py:266:<lambda>
lib\site-packages\twisted\python\context.py:122:callWithContext
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:547:sesscb_states_callback
ipv8\database.py:56:wrapper
ipv8\database.py:333:executescript
]
```

**Comment by ichorid** [comment] 2019-09-14 14:04
If our reporter does not lie, and this thing still happens, it accounts for at least 20% of all reported traces. It should be assessed immediately with a hotfix release.

**Comment by devos50** [comment] 2019-09-14 14:45
Out of the 124 stack traces reported for 7.3.0, 25 are related to this unrecognized token error. They are both reported by Windows (32 and 64 bit) and Linux users. This error seems to happen in the `sesscb_states_callback` method, which is AFAIK, the only method in Tribler that is still invoked on the threadpool. This is also visible in the stack traces.

This method should, like all other methods, run on the reactor thread and this change is trivial to implement. I'm not sure why we haven't done this yet, probably because it was not raising any problem up to this point.

Preparing a hotfix release at this point might be a bit hard, since we upgraded the OS of our (builder) Mac machine. There are some pending issues with PyInstaller (addressed in #4837).

**Comment by synctext** [comment] 2019-09-14 18:03
Great work diving into this. Would more debug output be helpful perhaps..

**Comment by egbertbouman** [comment] 2019-09-18 17:23
Hopefully, this issue is fixed by https://github.com/Tribler/tribler/pull/4836. If it reoccurs, please re-open.

**Comment by xoriole** [comment] 2019-09-25 09:47
Re-opening the issue. Caused by the presence of multiple bootstrap state files in the state directory.

**Closed** 2019-09-26 13:55 UTC
Labels: _Top Priority_, blocker, bug
