### ISSUE TITLE
KeyError: u'similarity:11097'

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1524] opened 2015-07-02 10:43 UTC
```
ERROR   1435829993.94 torrent_checker:394   Failed to create session for tracker http://fake.net:6969/announce: Cannot resolve tracker URL.
ERROR   1435830294.51 torrent_checker:394   Failed to create session for tracker http://fake.net:6969/announce: Cannot resolve tracker URL.
ERROR   1435830427.70        dispersy:1724  exception during handle_callback for similarity-response
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/discovery/community.py", line 593, in on_similarity_response
    request = self._request_cache.pop(u"similarity", message.payload.identifier)
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/requestcache.py", line 197, in pop
    cache = self._identifiers.pop(identifier)
KeyError: u'similarity:11097'
ERROR   1435830427.80       community:2577  already seen this indentifier in this batch, previous candidate {192.168.30.21:7759 212.156.56.114:7759} this one {192.168.30.21:7759 212.156.56.114:7759}
ERROR   1435830428.13       community:2866  already seen this indentifier in this batch, previous candidate {174.1.159.162:7759} this one {174.1.159.162:7759}
```

**Comment by whirm** [comment] 2015-07-03 11:13
@synctext which branch are you running?  
```
request = self._request_cache.pop(u"similarity", message.payload.identifier)
```
Is a ```get``` in ```upstream/devel``` which won't raise a ```KeyError``` if the ID is not in the cache.

**Comment by synctext** [comment] 2015-07-03 12:16
Rob his PR 1510 branch.

**Comment by LipuFei** [comment] 2015-07-03 12:18
@rjruigrok Have you done a rebase in your branch #1510?

**Comment by rjruigrok** [comment] 2015-07-03 13:30
Did it this afternoon, around 13:00. 
When did you fix this keyerror @LipuFei?

**Comment by rjruigrok** [comment] 2015-07-03 13:30
Btw, my previous rebase against devel was from yesterday afternoon.

**Comment by LipuFei** [comment] 2015-07-03 13:31
@rjruigrok about 2 days ago #1521

**Comment by rjruigrok** [comment] 2015-07-03 13:38
Then @synctext likely should do a `git submodule update --init --recursive` :smile:

**Comment by whirm** [comment] 2015-07-07 15:44
@synctext can you still reproduce it with an up to date checkout of ```devel```?

**Comment by synctext** [comment] 2015-07-07 15:50
Running a clean checkout for 46minutes now, has not come up yet.. good.

**Comment by whirm** [comment] 2015-07-15 10:21
Ok, I'm closing this one then.

**Comment by synctext** [comment] 2016-06-18 19:20
ai, poped up again. Fresh Tribler source code sheckout. Running bleeding edge devel from cmdline on Ubuntu 14.04.

commit b72db1ace90bef7cc6504dcea8891e9c10eee3c6
```
INFO    1466277275.25       community:308   initializing:  MultiChainCommunity
INFO    1466277321.95       community:289   Crawler: Received crawl request from node eISvcD52+s8EV8h4++IP6wqbQIY=, from sequence number -1
INFO    1466277321.95       community:316   Crawler: No blocks
ERROR   1466277322.73        dispersy:1747  exception during handle_callback for similarity-response
Traceback (most recent call last):
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/dispersy.py", line 1742, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/discovery/community.py", line 603, in on_similarity_response
    request = self._request_cache.pop(u"similarity", message.payload.identifier)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/requestcache.py", line 197, in pop
    cache = self._identifiers.pop(identifier)
KeyError: u'similarity:56184'
ERROR   1466277323.47       community:2579  already seen this indentifier in this batch, previous candidate {10.0.0.14:8079 83.82.246.165:8079} this one {10.0.0.14:8079 83.82.246.165:8079}
ERROR   1466277323.47       community:2579  already seen this indentifier in this batch, previous candidate {10.0.0.14:8079 83.82.246.165:8079} this one {10.0.0.14:8079 83.82.246.165:8079}
```

**Comment by devos50** [comment] 2017-01-11 16:03
@qstokkink could it be that there are two distinct messages that are having the same identifier? In this case, when processing the second message, the identifier won't be in the request cache anymore since it has been removed by the processing of the first message. It's the only way I can think of to trigger this error.

**Comment by qstokkink** [comment] 2017-01-11 16:32
@devos50 They really shouldn't have the same identifier. The discovery community uses a [RandomNumberCache for its id generation](https://github.com/Tribler/dispersy/blob/devel/requestcache.py#L54) (see [SimilarityAttempt](https://github.com/Tribler/dispersy/blob/devel/discovery/community.py#L478)). This approach avoids duplicate ids (unless you have 1000 consecutive ids taken, which is VERY unlikely).

To be honest, I'm still trying to figure out how this strack trace is even being printed (i.e. what class is printing it) and why it starts at the `_update()` function. As far as I know, `_update()` should only be called through `store_update_forward()`. I was thinking more in the lines of a delayed packet being resumed and bypassing the check handler.

Is this issue even relevant anymore anyway?

**Comment by synctext** [comment] 2017-01-11 21:36
request cache.. Recall Niels explaining to me that the request-cache has 16 bit identifiers. Always a 1 in 65536 chance of a mixup. That it perhaps?

**Comment by qstokkink** [comment] 2017-01-12 08:42
@synctext Let me expand upon my previous answer: the RandomNumberCache will try generate locally unique ids: you have an _x_ in 65536 chance of generating a unique id each round and this is repeated up to 1000 times until a unique id is found (where _x_ is the amount of already used ids). If a unique id cannot be found a [RuntimeError](https://github.com/Tribler/dispersy/blob/devel/requestcache.py#L60) is thrown.

Even if a unique id could not be found, the error would be different (RuntimeError). Furthermore, the ids which are returned to you, are the unique ids you chose yourself. The ONLY way you could have a mixup is if someone delivers a message to you, which was not meant for you (then the chance of failure becomes larger).

**Comment by devos50** [comment] 2017-01-12 08:44
@qstokkink @synctext thanks for the feedback. I agree with @synctext that a collision might have happened here but I think it's a bit suspicious that it only happened on Johan's computer (I haven't seen this specific report in the crash backend so far) which makes me think that this might have been fixed already.

So I also think this issue might not be relevant anymore and I will close it until someone reports it again. In that case, we have a new, more up-to-date stack trace which hopefully makes it easier to debug.

**Comment by qstokkink** [comment] 2017-02-06 10:44
I got this error today on the latest build using Windows Proxmox: it's still a thing.

**Comment by egbertbouman** [comment] 2017-02-06 15:03
I've looked into the issue and I think I know what's happening here: When a similarity response arrives, DiscoveryCommunity.check_similarity_response checks whether the message id is known and DiscoveryCommunity.on_similarity_response processes the message. However, if in between these two calls the RequestCache removes the message (due to a timeout), you will get this error.

Similar problems will happen in other communities as well. I'll have a look at this one.

**Comment by egbertbouman** [comment] 2017-02-07 12:56
Nope, that wasn't it. @qstokkink Do you still have the Proxmox log?

**Comment by qstokkink** [comment] 2017-02-07 14:30
@egbertbouman I don't have the log anymore, it was exactly the same trace as the ones reported earlier in this thread though (in respect to the function names; the RequestCache key number and the line numbers of the functions in the trace were different).

**Closed** 2017-02-13 13:50 UTC
Labels: bug
