### ISSUE TITLE
[7.10] socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#6298] opened 2021-08-30 07:12 UTC
[ipv8/messaging/anonymization/tunnel.py:172](https://github.com/Tribler/py-ipv8/blob/85f7eeeefecf2d6a2d0370494112b7a2c2ddd9f2/ipv8/messaging/anonymization/tunnel.py#L172)

```python
    async def resolve(self, host):
        # Using asyncio's getaddrinfo since the aiodns resolver seems to have issues.
        # Returns [(family, type, proto, canonname, sockaddr)].
        infos = await get_event_loop().getaddrinfo(host, 0, family=socket.AF_INET)
        return infos[0][-1][0]
```

```
tribler_gui.utilities.CreationTraceback: , 
  File "run_tribler.py", line 213, in <module>, 
  File "tribler_gui/utilities.py", line 395, in trackback_wrapper, 
  File "tribler_gui/core_manager.py", line 97, in on_request_error, 
  File "tribler_gui/core_manager.py", line 177, in start_tribler_core, 
The above exception was the direct cause of the following exception:, 
Traceback (most recent call last):, 
  File "tribler_gui/utilities.py", line 398, in trackback_wrapper, 
  File "tribler_gui/utilities.py", line 395, in trackback_wrapper, 
  File "tribler_gui/core_manager.py", line 87, in on_core_finished, 
RuntimeError: The Tribler core has unexpectedly finished with exit code 9 and status: 1!, 
[PID:28822] 2021-08-15 01:32:56,147 - ERROR <taskmanager:135> TunnelExitSocket.done_cb(): Task resulted in error: [Errno -2] Name or service not known, 
Traceback (most recent call last):, 
  File "ipv8/taskmanager.py", line 131, in done_cb, 
  File "ipv8/messaging/anonymization/tunnel.py", line 172, in resolve, 
  File "asyncio/base_events.py", line 825, in getaddrinfo, 
  File "concurrent/futures/thread.py", line 57, in run, 
  File "socket.py", line 918, in getaddrinfo, 
socket.gaierror: [Errno -2] Name or service not known, 
(Timestamp: 1629011318063, traceback timestamp: 1628980376148)
```

**Comment by qstokkink** [comment] 2021-08-30 07:39
This is a duplicate of #6297 (I'll use that as the main issue), `socket.gaierror` is not caught.

**Closed** 2021-08-30 08:01 UTC
Labels: type: bug, type: duplicate

**Comment by qstokkink** [comment] 2021-08-30 12:11
Update: main issue is now #4880
