### ISSUE TITLE
Tribler won't start: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by COUPON4Vitamins** [Tribler/tribler#6899] opened 2022-05-14 18:07 UTC
The latest release of Tribler does not start up. When I click on the application launcher in Gnome, nothing happens.

When I try to start Tribler from terminal, I get an error message:

```
liam@ideacentre:~$ tribler
Starting Tribler...
/usr/share/tribler ~
Segmentation fault (core dumped)
```

```
liam@ideacentre:~$ screenfetch 
                          ./+o+-       liam@ideacentre
                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.15.0-27-generic
           .++ .:/++++++/-.+sss/`      Uptime: 2h 50m
         .:++o:  /++++++++/:--:/-      Packages: 1889
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.1.16
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 41.4
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru-blue-dark [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Yaru-blue
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 69G / 1.4T (6%)
           .o:`.syhhhhhhh/.oo++o`      CPU: Intel Core i5-7400 @ 4x 3.5GHz [39.0°C]
               /osyyyyyyo++ooo+++/     GPU: llvmpipe (LLVM 13.0.1, 256 bits)
                   ````` +oo+++o\:     RAM: 4025MiB / 7905MiB
                          `oo++.
```

**Comment by xoriole** [comment] 2022-05-14 19:57
Duplicate of https://github.com/Tribler/tribler/issues/6895

**Closed by xoriole** 2022-05-14 19:57 UTC
Labels: type: duplicate
