### ISSUE TITLE
Enhancement to rename files within the torrent payload.

### ISSUE THREAD

**Issue by snakyjake1** [Tribler/tribler#5653] opened 2020-10-16 23:57 UTC
I would like an enhancement to rename files within the torrent payload.

Why?  I like to remove the junk that other seeders add to the filename and conform to Kodi naming conventions.

##### Tribler version/branch+revision: #####
7.5.2

**Comment by synctext** [comment] 2020-10-17 06:36
interesting, would that be renaming the local files?
Or global files and alter the magnet link of the swarm? (requires global crowdsourcing, spam, and moderation stuff)

**Comment by ichorid** [comment] 2020-10-17 09:15
Possible duplicate of #3455 
Related to #4222

**Comment by snakyjake1** [comment] 2020-10-17 18:55
> 
> 
> interesting, would that be renaming the local files?
> Or global files and alter the magnet link of the swarm? (requires global crowdsourcing, spam, and moderation stuff)

Rename local files.
Main purpose is to follow naming standards for movie/tv scraping (Kodi) and cleaning up the name.

I do not wish to alter anything that would generate a new torrent hash, and divide the swarm health.

**Comment by ichorid** [comment] 2020-10-17 20:29
AFAIK, Libtorrent supports renaming files locally. We supported this feature through the GUI, but removed it during refactoring some time ago.

**Closed** 2021-03-30 10:42 UTC
Labels: component: GUI, needs feedback, type: enhancement
