### ISSUE TITLE
Tribler temporarily frozen with 100% single-core CPU load when I deleted a download

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2115] opened 2016-04-20 23:59 UTC
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

v6.5.1
##### Operating system and version:

Debian
##### Expected behavior:

Tribler continues running like usual after removing a download.
##### Actual behavior:

Tribler frozen for about a minute, CPU-bound in one thread. GUI was stuck.
##### Steps to reproduce the behavior:

Maybe find the ever-"Initializing" stuck download and relete it with data. Maybe delete download + data while data was already removed manually (I don't remember exactly).
##### Relevant log file output:

No related was printed to console, although Tribler constantly prints backtraces about NoneType or about dropped packets even during normal operation.

**Comment by devos50** [comment] 2017-01-03 09:47
@vi have you experienced this issue recently? I think it has something to do with the old wx GUI but I'm not sure about that.

**Comment by vi** [comment] 2017-01-03 13:40
It was reproduced only once on old GUI.

**Comment by devos50** [comment] 2017-01-09 15:03
Well, I haven't seen this one myself and I've removed many downloads already in the new GUI. I will close this one since it's hard to reproduce.

Please reopen this issue if anyone encounters it again.

**Closed by devos50** 2017-01-09 15:03 UTC
Labels: bug
