### ISSUE TITLE
Tribler stuck on building circuits.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3636] opened 2018-05-21 20:12 UTC
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler v7.1.0-exp2 
I did some quick testing and i believe the issue is introduce with exp1-142 or exp1-144. Tribler works on 140, and i tested 144 and did not work. Likely this buid with this change that did it: 
https://jenkins.tribler.org/job/Build-Tribler_Win64_next/209/changes

##### Operating system and version: #####
Windows 10

##### Steps to reproduce the behavior: #####
Start Tribler

##### Expected behavior: #####
Torrents will build circuits and start to work.

##### Actual behavior: #####
Fails to do so.

##### Relevant log file output: #####
To be updated. The log stands still for several seconds as whatever process is keeping it from going forward, then some lines about stuff and this one happens:

![image](https://user-images.githubusercontent.com/1584461/40327332-c55f4ff2-5d42-11e8-8640-9a3467093999.png)

This happened pretty early in logging:
![image](https://user-images.githubusercontent.com/1584461/40327269-89c89926-5d42-11e8-9a86-738f1f64d803.png)

Full info log, well all that is saved, since Tribler doesn't shut down properly, i used the force close option, which leaves only this behind, which does not include everything in the console obviously:
https://pastebin.com/vWYH6j0G

Also, those last lines go one for a lot longer, just that pastebin got a size limitation. The paste expires after 2 weeks, so i suggest taking a local copy in case you need it. 

Update: Tribler ran overnight, and crashed. Here's what i found in the core error logs: 

> ERROR   1526939028.58              rest_manager:53   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'execute'
> lib\site-packages\twisted\protocols\basic.py:571:dataReceived
> lib\site-packages\twisted\web\http.py:1964:lineReceived
> lib\site-packages\twisted\web\http.py:2059:allContentReceived
> lib\site-packages\twisted\web\http.py:869:requestReceived
> --- <exception caught here> ---
> lib\site-packages\twisted\web\server.py:184:process
> lib\site-packages\twisted\web\server.py:235:render
> lib\site-packages\twisted\web\resource.py:250:render
> Tribler\Core\Modules\restapi\trustchain_endpoint.py:87:render_GET
> Tribler\pyipv8\ipv8\util.py:14:helper
> Tribler\pyipv8\ipv8\util.py:26:blockingCallFromThread
> Tribler\community\triblerchain\community.py:44:get_statistics
> Tribler\pyipv8\ipv8\attestation\trustchain\database.py:80:get_latest
> Tribler\pyipv8\ipv8\attestation\trustchain\database.py:49:_get
> Tribler\pyipv8\ipv8\database.py:40:wrapper
> Tribler\pyipv8\ipv8\database.py:302:execute
> ]
> Traceback (most recent call last):
>   File "lib\site-packages\twisted\web\server.py", line 184, in process
>   File "lib\site-packages\twisted\web\server.py", line 235, in render
>   File "lib\site-packages\twisted\web\resource.py", line 250, in render
>   File "Tribler\Core\Modules\restapi\trustchain_endpoint.py", line 87, in render_GET
>   File "Tribler\pyipv8\ipv8\util.py", line 14, in helper
>   File "Tribler\pyipv8\ipv8\util.py", line 26, in blockingCallFromThread
>   File "Tribler\community\triblerchain\community.py", line 44, in get_statistics
>   File "Tribler\pyipv8\ipv8\attestation\trustchain\database.py", line 80, in get_latest
>   File "Tribler\pyipv8\ipv8\attestation\trustchain\database.py", line 49, in _get
>   File "Tribler\pyipv8\ipv8\database.py", line 40, in wrapper
>   File "Tribler\pyipv8\ipv8\database.py", line 302, in execute
> AttributeError: 'NoneType' object has no attribute 'execute'
>

**Comment by qstokkink** [comment] 2018-05-24 10:26
Thanks for figuring out which commit caused this. The commit in question is where we switched to a different UDP implementation (@ichorid).

**Comment by ichorid** [comment] 2018-05-24 11:46
@Thomasedv, thanks for the report! 
It would be very nice if you could reproduce the issue or provide the link to the torrent that triggers this.

**Comment by ichorid** [comment] 2018-05-24 11:49
For me, it looks like two distinct issues:
1. `AttributeError: 'NoneType' object has no attribute 'execute'` - database can't connect, and it does not handle this condition properly.
2. `torrent checker ... http tracker timeout` - this is an instance of #2681 (Tribler not supporting TCP connections).

**Comment by ichorid** [comment] 2018-05-24 11:53
@qstokkink, could you please comment on IPv8 database behavior?

**Comment by qstokkink** [comment] 2018-05-24 12:56
@ichorid certainly:

1. `AttributeError: 'NoneType' object has no attribute 'execute'` happens when database calls are scheduled by Twisted after shutdown. More on this here: https://github.com/Tribler/py-ipv8/issues/116 . This is more of a cosmetic bug than anything else.

2. The torrent checker bug does not have anything to do with the tunnels. This is done in the `TorrentChecker` class, which checks the liveness (read: contacts the trackers) of torrents we discovered in other people's channels. As most of the trackers are unreachable, you get a lot of these unreachable tracker errors.

**Comment by devos50** [comment] 2018-05-30 12:54
According to the pastebin log, it seems Tribler creates ~8 circuits for every anonymous downloads. So if a user has like 100 anonymous downloads running, it creates 800 circuits! This is obviously a bug and I think this is contributing to this issue.

**Comment by devos50** [comment] 2018-05-30 14:08
I've tried to figure this one out. I'm unable to reproduce it unfortunately. However, I might have an idea what's going on.

First, the `do_check` method is periodically scheduled to be called, every five seconds. It check whether the DHT is initialised yet (@egbertbouman do we still need this?) and whether we have the required amount of circuits ready. Immediately after starting a Tribler instance, this `do_check` is called, attempts to build a few circuits (by invoking `build_tunnels`) and most likely fails (since there are no exit nodes yet). Now, the `do_check` call is scheduled to be called again. Assume that we found a bunch of exit nodes now and circuit creation can proceed. The `build_tunnels` method is now called again and successfully builds tunnels. Also assume that there let's say 100 anonymous downloads active. I suspect that the `do_circuits` is called many times, with very short intervals, once for every running downloads. This can lead to the situation where a circuit is being built but not added yet to the `self.circuits` dictionary and in turn, is not counted for in the `do_circuits` method.

I think this can easily be fixed by not calling `do_circuits` in `build_tunnels` (`do_circuits` is already scheduled to be called periodically). However, this would lead to very slow unit tests since we want to build tunnels immediately. We can solve this by adding a flag to `build_tunnels`, something like `force`, which defaults to `True`. If this flag is `True`, `do_circuits` is called in the `build_tunnels` method. When calling the `build_tunnels` method from the `do_check` method, we pass `False`.

@qstokkink could you let me know whether you agree with this fix?

**Comment by qstokkink** [comment] 2018-05-30 14:32
@devos50 if that is the case, I think I would prefer inspection of `self.circuits` in the community and reason about the `CIRCUIT_TYPE_DATA` type circuits with a state of `CIRCUIT_STATE_EXTENDING`. We could then decide not to make new circuits if we are still waiting for circuits to be created.

This would keep the speed you wanted and avoid going over the circuit limit.

**Comment by devos50** [comment] 2018-05-30 14:46
@qstokkink that's not enough I think. The circuits are probably not added to `self.circuits` yet (if they were, `self.data_circuits` would return more circuits but it seems that is not happening.

**Comment by Thomasedv** [comment] 2018-05-30 15:41
Any way i could further help out on this?

**Comment by egbertbouman** [comment] 2018-06-06 12:18
I was just looking at this, and I think I know what's happening. Basically, if you have a few downloads that are waiting for the DHT/tunnels, you'll get several simultaneous calls to do_circuits. The problem is that the ```data_circuits``` property (called by do_circuits) only looks at the tunnels that have finished building (https://github.com/Tribler/py-ipv8/blob/master/ipv8/messaging/anonymization/community.py#L465), while it should also look at the ones that are still in progress. I'll create a PR for this.

**Closed** 2018-06-12 07:31 UTC
Labels: broken
