### ISSUE TITLE
ValueError: bytes must be in range(0, 256)

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5438] opened 2020-07-03 13:09 UTC
**7.5.1 Windows 10**

from Reporter

```python
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 112, in on_read_data
RuntimeError: bytes must be in range(0, 256)
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "lib\asyncio\selector_events.py", line 965, in _read_ready
File "src\tribler-core\tribler_core\modules\tunnel\socks5\udp_connection.py", line 51, in datagram_received
File "src\tribler-core\tribler_core\modules\tunnel\community\dispatcher.py", line 91, in on_socks5_udp_data
File "ipv8\messaging\anonymization\community.py", line 485, in send_data
File "ipv8\messaging\anonymization\community.py", line 471, in send_cell
File "ipv8\messaging\anonymization\payload.py", line 77, in to_bin
File "ipv8\messaging\anonymization\payload.py", line 32, in encode_address
File "ipv8\util.py", line 24, in cast_to_bin
ValueError: bytes must be in range(0, 256)

--CONTEXT--
{'message': 'Exception in callback _SelectorDatagramTransport._read_ready()', 'exception': ValueError('bytes must be in range(0, 256)'), 'handle': <Handle _SelectorDatagramTransport._read_ready()>}

```

**Comment by qstokkink** [comment] 2020-07-03 13:16
@egbertbouman do you want to fix this a second time?

**Comment by ichorid** [comment] 2020-07-03 13:29
It was reported today, so I guess it is still a problem.

**Comment by qstokkink** [comment] 2020-07-03 13:38
That is odd, the line numbers do not match up. `encode_address` spans lines 20-27. This is reporting an error on line 32.

**Comment by qstokkink** [comment] 2020-07-03 13:39
The last time `encode_address` was even present on line 32 was in October of last year.

**Comment by egbertbouman** [comment] 2020-07-03 13:42
This is a different issue. The original one was caused by `inet_aton` raising a `ValueError` if the IP had embedded null characters (fixed in https://github.com/Tribler/py-ipv8/commit/82c43ed17618e0bd031b44283380898602f35427).

This time it's failing [here](https://github.com/Tribler/py-ipv8/blob/master/ipv8/messaging/anonymization/payload.py#L32).

**Comment by qstokkink** [comment] 2020-07-03 13:47
Seems the dispatcher should catch the error (on this line https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/tunnel/community/dispatcher.py#L90) and return `False` in this case.

**Comment by egbertbouman** [comment] 2020-07-03 14:30
@qstokkink Your comments seem to be disappearing :wink:

**Comment by qstokkink** [comment] 2020-07-03 14:35
> @qstokkink Your comments seem to be disappearing 😉

What I had claimed before was factually untrue and therefore not contributing to this discussion. Therefore I removed 2 of my comments to keep this issue clean.

**Comment by egbertbouman** [comment] 2020-07-04 17:38
I guess we're dealing with a Unicode hostname. That would explain the mentioned stacktrace.

For example hostname JP納豆.例.jp:

```python
cast_to_bin('JP納豆.例.jp')
```

produces:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in cast_to_bin
ValueError: bytes must be in range(0, 256)
```

Since `decode_address` is already decoding using UTF-8, the obvious way to fix this would be to let `encode_address` encode using UTF-8. IDNA encoding is handled automatically at the exit nodes by Python.

**Comment by qstokkink** [comment] 2020-07-05 06:58
Even though applying utf-8 encoding will *probably* work *most of the time*, this is user input (and in the worst case even 3rd party input) and can be wrong or malicious. The call to `self.tunnel_community.send_data` should also be _treated as user input_ and be in a `try .. except` block. This is the second time this method caused a Tribler crash.

**Comment by qstokkink** [comment] 2020-07-05 07:31
On second thought: we shouldn't use `utf-8`. The correct way of handling non-ASCII characters in URLs is `idna`, we can implement this in IPv8:

```python
> 'JP納豆.例.jp'.encode("idna")
b'xn--jp-cd2fp15c.xn--fsq.jp'
```

You can verify in your browser that `xn--jp-cd2fp15c.xn--fsq.jp` is the same URL as `'JP納豆.例.jp'`.

Still, this should be accompanied by a PR to Tribler that wraps this call into a `try ... except`.

**Comment by qstokkink** [comment] 2020-07-05 07:42
I forked-off the IPv8 part of this issue into https://github.com/Tribler/py-ipv8/issues/803

**Comment by synctext** [comment] 2020-07-05 08:42
are there lexical analysis tools for discovery of all this stuff? There should be perhaps.

**Comment by qstokkink** [comment] 2020-07-05 09:35
> 
> 
> are there lexical analysis tools for discovery of all this stuff? There should be perhaps.

The Python-approved way of doing this would be to add `typing` to all parts of the code and using `NewType` (https://docs.python.org/3/library/typing.html#newtype) to specify specific subtypes. I.e. in this case the `str` would be a `URL` type. But even this would not actually prevent this error without writing a custom static analysis tool that knows how each of these specific subtypes needs to be serialized before being sent over the wire.

To fix this "properly" you would need an in-memory and on-the-wire format version of each object. Golang has something like this. But, even then, the detectability depends on how neurotically all programmers specify each subtype. The complicating factor is that in 99% of the cases this is wasted effort and programmers know this: nobody will go out of their way to make their subtype absolutely 100% foolproof (or in some cases the corner cases are not even known to the programmer). Typically this is considered over-engineering.

I believe high quality unit testing is the only way to sanely root out these kinds of errors.

**Comment by egbertbouman** [comment] 2020-07-05 10:16
@qstokkink In this case, encoding using UTF-8 should always work, because when `encode_address` is called we just decoded the hostname using UTF-8 in `__decode_address`. So no `try...except` is needed in `Dispatcher`. Of course, if `send_data` is called with incorrect parameters, it will fail. I would even argue that this is a good thing because now we're getting error reports of UTF-8 hostnames not working. For course, we need a unit test for this, which I'll add to IPv8.

IDNA encoding will be applied by Python when calling `transport.sendto` at the exit node.

**Comment by qstokkink** [comment] 2020-07-05 10:57
@egbertbouman your answer confused me greatly. `transport.sendto` is not used with the host name, the IP is resolved here based on the hostname:

https://github.com/Tribler/py-ipv8/blob/master/ipv8/messaging/anonymization/tunnel.py#L173-L177

I did confirm that, when fed a UTF-8 string, this method also internally applies IDNA (by feeding it `\x80`: `UnicodeError: encoding with 'idna' codec failed (UnicodeError: Invalid character '\x80')`). So, your conclusion is still correct: applying `encode()` in the `encode_address` will work.

Still, crashing on invalid hostnames is not something the dispatcher should do in my opinion. This is not an **unrecoverable error** that should halt execution of the entire application. The Dispatcher has a return code for valid connection establishment and that could be used. Whereas I agree we probably wouldn't notice this being written to the log, crashing the entire app is also a bit much. Ideally I'd like the middleground of "Oops something went wrong, please send us an error report", but we don't have that feature 😃

**Comment by egbertbouman** [comment] 2020-07-05 11:03
@qstokkink I didn't realize you were so easily confused, my apologies. if you just replace `transport.sendto` with `getaddrinfo` everything else I said still stands.

Crashing the app gives us error reports, and revealed this bug. If this didn't happen we would never know about this issue. Again, hostnames from the dispatcher are already decoded using UTF-8, re-encoding using UTF-8 should not fail.

**Comment by qstokkink** [comment] 2020-07-05 11:44
@egbertbouman apologies accepted, know that you wasted more than half an hour of my time sending me off looking for something that does not exist.

What I did not realize before (and took me even more time), is that `__decode_address` thows an `InvalidAddressException` when it encounters a UTF-8 conversion error in a `try ... except` and is logged:

https://github.com/Tribler/tribler/blob/5e58ee71cbb4bcd8f308700cdf524b0dcb899f42/src/tribler-core/tribler_core/modules/tunnel/socks5/conversion.py#L183-L190

What I was advocating for is actually already in the code. I guess I was fighting a battle I already won?

So, once IPv8 has support for UTF-8 encoded URLs all of my gripes with this issue are resolved.

**Comment by egbertbouman** [comment] 2020-07-05 11:55
@qstokkink You didn't waste your time, you just learned a little more Python. Also, I really appreciate you going through my comments with a fine-tooth comb.

Since you're basically saying that `send_data` doesn't need a `try..except` after all, it seems that we're in agreement. If what you take from this is that you won some sort of battle, that's fine by me.

**Comment by qstokkink** [comment] 2020-07-05 12:06
Well I definitely learned some more Tribler 😃 And, I always take what you say quite seriously and literally.

In conclusion: yes, it took me some time to verify, but I agree with you on all points.

Also, the "battle" is a figure of speech. What I meant to say, is that I wanted to add something that was already there. Therefore there was nothing to "win" code-wise. So, quite the contrary, I "lost" my time in a "battle" against myself.

**Comment by ichorid** [comment] 2020-07-08 11:21
Now that the dust have settled, is it fixed?

**Comment by egbertbouman** [comment] 2020-07-08 11:44
First we'll have to move the IPv8 pointer, and moving the pointer will also require some changes in Tribler. I'll make a PR for this.

**Closed** 2020-07-08 15:05 UTC
Labels: bug
