### ISSUE TITLE
Ratio not updating and not in Torrent details

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3145] opened 2017-10-08 11:38 UTC
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes
##### Tribler version/branch+revision: #####
Noticed in last few builds
##### Operating system and version: #####
Windows 10
##### Steps to reproduce the behavior: #####
Seeding for a while and although average file size is 8 gig, one would expect after two hours at least 1% ratio, or not?
##### Expected behavior: #####
Ratio percentage growing
##### Actual behavior: #####
Ratio stays on 0 all the time
##### Relevant log file output: #####
This is with annonimity seeding!?

**Comment by devos50** [comment] 2017-10-08 13:03
Anonymous seeding is only effective when there are also anonymous downloaders. I guess that there are no anonymous downloaders available for the specific torrent you're uploading which explains that the ratio is not going up.

To see whether this is the case, we should add a total downloaded/uploaded counter in the download details tab in the user interface but this is another issue.

@Nubro01 can you confirm that the ratio works correctly when uploading/download without anonymity?

**Comment by Nubro01** [comment] 2017-10-09 14:05
I installed the latest version from https://jenkins.tribler.org/job/Build_Tribler_next/ and installed and removed all three Torrents and added them one by one being none anonymous, but after 3 hours of seeding the ratio is still at 0,000 percent, where I would expect at least 0,001 percent at least, so I save to conclude that Ratio is not updating.
Version has been very stable up until now. Previously I had to restart every 10 minutes.

Regards

Ron

Van: Martijn de Vos [mailto:notifications@github.com]
Verzonden: zondag 8 oktober 2017 15:03
Aan: Tribler/tribler
CC: Ron Nuberg; Mention
Onderwerp: Re: [Tribler/tribler] Ratio not updating and not in Torrent details (#3145)


Anonymous seeding is only effective when there are also anonymous downloaders. I guess that there are no anonymous downloaders available for the specific torrent you're uploading which explains that the ratio is not going up.

To see whether this is the case, we should add a total downloaded/uploaded counter in the download details tab in the user interface but this is another issue.

@Nubro01<https://github.com/nubro01> can you confirm that the ratio works correctly when uploading/download without anonymity?

**Comment by Nubro01** [comment] 2017-10-12 18:55
Version of oct 12, gives a ratio just after 3 minutes. Thanks

**Comment by Nubro01** [comment] 2017-10-12 19:31
While downloading I was also uploading and Ratio went up.
After the download finished, Files where checked and seeding was anonymous and ratio was reset to 0.000, after  30 minutes seeding it still was on 0.000, so?????

**Comment by Nubro01** [comment] 2017-10-12 20:29
When download and seeding none anonymous, ratio is being updated!!!
Also when finished downloading seeding starts without checking!!! So ratio is not cleared and again when seeding it is updating!

**Comment by themusicgod1** [comment] 2017-11-02 14:23
Also seeing this on next / ea9f151fa / ubuntu artful 17.10.  Anonymous seeding is definitely happening without updating ratio on *most* of my torrents.  However one torrent(2 hops) has a ratio (0.078).

**Comment by qstokkink** [comment] 2017-11-08 07:39
I can confirm that the ratio gets reset when switching anon hops and rechecking.

I have also seen MultiChain blocks being created when seeding while the ratio remained 0: this *may* just be due to overhead messages and such, instead of seeding actual data. Further investigation is required.

**Comment by qstokkink** [comment] 2017-11-09 10:34
Since most of this issue has been fixed in #3197, I have moved the remaining part into a seperate issue #3199.

**Closed by qstokkink** 2017-11-09 10:34 UTC
Labels: needs feedback

**Comment by themusicgod1** [comment] 2018-01-12 23:30
I am running rc4 and all of my ratios are still at 0.0 even though I've seen seeding happen.

**Comment by devos50** [comment] 2018-01-13 10:19
@themusicgod1 could you post your absolute amount of uploaded/downloaded data for a specific download where you think the ratio shouldn't be 0.0? You can see these values when clicking on the torrent and by investigating the panel in the bottom part of the screen.

**Comment by themusicgod1** [comment] 2018-01-13 16:16
example
status: seeding
filesize 4.3 GB in N files
health 0 seeders 2 leachers
 (not givng infohash, sorry)
destination /mnt/disk/TRIBLER
Ratio: 0.000 up 2.7 GB, down 0.0 GB 
availability 0.00
