### ISSUE TITLE
ubuntu 18.04 LTS, ram filling up completely

### ISSUE THREAD

**Issue by paul-rf** [Tribler/tribler#5934] opened 2021-01-12 17:18 UTC
Hi,
I installed tribler 7.7.0 last friday (downloaded deb file, installation via Ubuntu sw centre) on a ubuntu 18.04 LTS PC as alternative to transmission. Every day I had to reboot the PC as it was completely stuck. Yesterday I started following RAM: after starting tribler I get 4 entries in the list (I have a couple of active torrents), of which 1 starts at ~100 MB RAM, and this continues to grow until the RAM (5 GB in my case) is completely filled up. This morning I stopped tribler, and restarted, but the same behaviour is still there. After installing 7.7.1 and starting today I still see RAM-usage increasing (from 150 M at 14:00 today, to 1.8 G at 18:00).

I am running remmina as remote terminal for the ubuntu 18.04 LTS PC, on a laptop running ubuntu 20.04 LTS, but I cannot imagine that that causes the problem.

Is this expected behaviour? What maximum RAM-usage do you expect from tribler?

I saw a similar problem (issue 2123, 22-4-2016), but I would expect this to be solved in the mean time.

Let me know if you need more information.

**Comment by Davem734** [comment] 2021-01-13 00:46
Can confirm. 
Problem started with v7.7.0 and still a problem with v7.7.1
Fills up 32Gb of memory after a few hours.
Ubuntu 18.04.5
Python 3.8.5

**Comment by Davem734** [comment] 2021-01-13 01:55
Tribler launches four processes. 
It is the second (based on PID order) of the four processes that has the memory issue...

**Comment by xoriole** [comment] 2021-01-13 04:54
@paul-rf @Davem734 Thank you for reporting and confirming. Currently, Tribler does not set an upper bound on memory usage, but we should cap that and fix the root cause of memory leak. Prioritizing the issue for the release.

**Comment by synctext** [comment] 2021-01-13 20:31
wow 32GBytes! That should be easy to locate, thnx!

**Comment by egbertbouman** [comment] 2021-01-14 00:04
When I go back before https://github.com/Tribler/tribler/commit/9d8f961cc0b66441363dd837ce351063d49b2c5b, the GUI process doesn't leak for me anymore. The leak seems to be related to the signal handlers.

**Comment by qstokkink** [comment] 2021-01-14 09:14
Inspected `gc`, this function is leaking:

https://github.com/Tribler/tribler/blob/b29e4a6739d57e887bc9a738584d1ee84d1669d2/src/tribler-gui/tribler_gui/utilities.py#L378

**Comment by ichorid** [comment] 2021-01-18 13:06
According to [this report](https://forum.tribler.org/t/tribler-7-7-1-bug-fix-release-is-out-today/6409/2?u=ichorid) from our forum, the user experiences a leak and a crash on the GUI side. The Core continues to run as normal. I guess it points us to the GUI leaking.

**Comment by Davem734** [comment] 2021-01-19 01:59
I noticed that the leak seems to stop (or really slow down) if I am not displaying the "downloads" page...

**Comment by kozlovsky** [comment] 2021-01-19 10:59
According to @xoriole experiments, it seems PR #5940 is able to fix the major memory leak, but some minor memory leak still presents. Further debugging is necessary to discover other reasons for memory leaks.

**Comment by kozlovsky** [comment] 2021-01-19 11:42
The issue was auto-closed by commit message, but I'm reopening it, as the memory leak was not completely fixed yet

**Comment by qstokkink** [comment] 2021-01-19 12:31
Perhaps it would be a good idea to focus some effort on implementing #3603 into the debug screen so we can see what objects are actually leaking.

**Closed** 2021-01-19 19:04 UTC
Labels: type: blocker, type: bug
