### ISSUE TITLE
Tribler won't work well on macOS after having been shut down once

### ISSUE THREAD

**Issue by dertuxmalwieder** [Tribler/tribler#6052] opened 2021-04-13 11:04 UTC
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

7.8.0 as well as 7.9.0 dev., both from tribler.org.

##### Operating system and version: #####

macOS 11 Big Sur

##### Steps to reproduce the behavior: #####

* Start Tribler.
* Download a few things.
* Keep a few downloads unfinished when shutting down Tribler.
* Start Tribler again.

##### Expected behavior: #####

No problems should occur.

##### Actual behavior: #####

* The GUI is broken: The Settings screen is empty and the download window won't refresh anymore (it is stuck on "Building circuits" in 7.8.0 and "Downloading" in 7.9.0).
* Shutting down Tribler won't work anymore - I'll have to wait for the "Force" button and use that.

##### Relevant log file output: #####

Not sure why, but nothing's in the error log.

**Comment by xoriole** [comment] 2021-04-13 12:44
@dertuxmalwieder Thank you for reporting. It is difficult to reproduce the exact behavior. I tried on macOS 11.2.3 with a few unfinished Linux torrents.

> The GUI is broken: The Settings screen is empty and the download window won't refresh anymore (it is stuck on "Building circuits" in 7.8.0 and "Downloading" in 7.9.0).
Shutting down Tribler won't work anymore - I'll have to wait for the "Force" button and use that.

1. Is it repeatable across restarts?
2. Does the settings window appear empty when started afresh? If not, I suggest enabling Settings -> DEBUG -> Developer mode. When it is enabled, a debug menu appears in the sidebar below `Trust Graph`. Debug window provides more information that can help us potentially find out the issue.
3. When the downloads window appears to be frozen, could you click on Debug menu (left sidebar) and then System tab -> CPU & Memory Tabs to see the resource usage? If it is unusual, please report us here.

**Comment by dertuxmalwieder** [comment] 2021-04-13 12:48
1. Yes.
2. The Settings window appears empty only when Tribler has been used before. There is no way to "reset" Tribler to a working state as far as I can see, except maybe to `rm -rf .tribler` which would also kill my downloads, right?
3. macOS's Activity Monitor does not show unusual behavior. "Frozen" was probably the wrong term - old downloads are stuck in "Downloading" and new ones are stuck in "Building circuits".

**Comment by xoriole** [comment] 2021-04-13 13:19
That is interesting to know. It is unusual to see an empty settings screen.

Yes, a definite way to reset Tribler is to delete `~/.Tribler` directory which deletes all config data including your download config data. But there is a way to recover your downloads. If you look closely inside `.Tribler` directory, there are separate directories for different versions. Further inside, you can see a directory called `dlcheckpoints`. Your downloads configs are stored there. Copy/paste of the .conf files inside will recover your downloads later. 

Since it is not sure if starting from a new `.Tribler` directory solves the issues, I suggest keeping a backup of the full `.Tribler`   before deleting it and running Tribler again.  Could you try that and let us know?

**Comment by dertuxmalwieder** [comment] 2021-04-13 13:42
I have just renamed it:

    % mv .Tribler .Tribler-backup

I enabled the Developer Mode, then I copied back the downloads:

    % cp -R .Tribler-backup/7.9/dlcheckpoints/* .Tribler/7.9/dlcheckpoints

I restarted Tribler, waited a bit and - all downloads are stuck in "Building circuits" mode and I have no Settings (and the Debug window also seems to have issues now). It does not seem to matter whether I had changed any settings in the process (which I also tried). There does not seem to be a difference between the latest two versions of Tribler.

<img width="985" alt="Bildschirmfoto 2021-04-13 um 15 40 36" src="https://user-images.githubusercontent.com/125629/114562335-b6138400-9c6e-11eb-9eaf-7b00c4e15f3b.png">

<img width="1276" alt="Bildschirmfoto 2021-04-13 um 15 41 12" src="https://user-images.githubusercontent.com/125629/114562344-b875de00-9c6e-11eb-98bb-b19f4b716b15.png">

<img width="985" alt="Bildschirmfoto 2021-04-13 um 15 40 44" src="https://user-images.githubusercontent.com/125629/114562350-b9a70b00-9c6e-11eb-86ab-364d444f7a02.png">

I also run Tribler 7.8.0 with (almost) the same downloads on a Windows 10 machine and everything is just fine there.

**Comment by xoriole** [comment] 2021-04-13 14:33
@dertuxmalwieder Thank you for the screenshots, it makes it clear the effect of the issue.
1. Can you confirm that the issue only happens when you copy the downloads conf files? Running multiple times without downloads copied and checking if the settings page works should confirm it.
2. Since the Debug window is also empty, it seems to me the issue might not be related to download.
3. Since logs are not present in the file, I suggest running Tribler on terminal:
```
/Applications/Tribler.app/Contents/MacOS/tribler
```
It should show the logs and errors if any.

**Comment by dertuxmalwieder** [comment] 2021-04-13 14:42
1. The first time it happened with *new* downloads, so that's highly doubtful in my opinion. I cannot even add new downloads now (the menu exists, but no Add Download dialog appears), so I guess Tribler kills them somewhere on the way.
2. I never claimed it would. I would actually assume that the GUI is broken, not the core. (But the GUI logs are empty as well.)
3. Logs are there, but no obvious errors except this one:

```
[PID:50395] 2021-04-13 16:37:38,766 - INFO - TriblerGUI(147) - Will connect to events endpoint
[PID:50395] 2021-04-13 16:37:38,780 - INFO - TriblerGUI(83) - Got Tribler core error: 1
```

That happens repeatedly.

Opening the Settings window: The settings are visible. Closing it and opening it again: The settings are gone. Nothing happens in the terminal during that time.

All torrents are stuck in "Building circuits" after the latest restart. Maybe this is relevant?

```
INFO:__main__:Enabling a workaround for macOS Big Sur
```

Shutting down Tribler logs an error:

```
CoreSVG has logged an error. Set environment variabe "CORESVG_VERBOSE" to learn more.
```

I would imagine that this is a follow-up error from the other errors and not an isolated error which should be investigated on its own.

**Comment by xoriole** [comment] 2021-04-14 10:41
Since the settings page is empty as shown in your screenshot above, it could be that GUI settings are corrupted for some reason. They are stored in the following file. 
```
/Users/<your username>/Library/Preferences/com.nl-tudelft-tribler.plist
```
Could you try removing this file and running Tribler again? Tribler will regenerate this file on startup.

**Comment by dertuxmalwieder** [comment] 2021-04-14 17:50
That does indeed restore the GUI for a while - but opening the Settings, closing the Settings, opening the Debug window, closing the Debug window and opening the Settings again keeps emptying the Settings screen. (I am not sure whether the steps are relevant at all.) At least Debug is still unaffected.

<img width="1270" alt="Bildschirmfoto 2021-04-14 um 19 49 50" src="https://user-images.githubusercontent.com/125629/114756049-9eb1c500-9d5a-11eb-89f6-268a81158846.png">

**Comment by xoriole** [comment] 2021-04-23 13:44
@dertuxmalwieder Could you share the contents of `/Users/<username>/Library/Preferences/com.nl-tudelft-tribler.plist` file? 

For reference, here is how it looks on my mac:
`cat /Users/<username>/Library/Preferences/com.nl-tudelft-tribler.plist`

```
bplist00        






Udebug_autocommit_enabled^first_discoverXapi_portTsize_use_monochrome_icon]family_filter_recent_download_locations_ask_download_settingsWapi_keySpos                    ??_@Size(1164 847       _P2f55736572732f73697265746f2f446f776e6c6f6164732f547269626c6572446f776e6c6f616473      OV@Variant(PyQt_PyObject/$C acae103049e9df9be70efc89563874f6.)^@Point(190 25%:IRWm{???????????()??%
```

In the latest development version, the content of this file is shown in the Debug Pane. It might be easier to see the settings from there if something is corrupted while saving settings.

Here is a link to the latest development version if you'd like to try:
https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build/223/

**Comment by dertuxmalwieder** [comment] 2021-04-23 17:33
> '/Users/tux0r/Library/Preferences/com.nl-tudelft-tribler.plist': No such file or directory (os error 2)

**Comment by xoriole** [comment] 2021-07-14 14:00
@dertuxmalwieder We still don't have much progress on this issue and cannot reproduce either. Maybe you could try the latest version 7.10.0 where we have updated some of the underlying dependencies?

**Comment by dertuxmalwieder** [comment] 2021-07-14 14:12
I did a few days ago. It seemed to work less badly, but a long-term test still needs to be done.

**Comment by dertuxmalwieder** [comment] 2021-07-28 00:38
I'm afraid I'll have to keep this open for a while. I restarted my MacBook shortly after and now Tribler is back to its faulty behavior.

**Comment by xoriole** [comment] 2023-06-16 11:45
@dertuxmalwieder do you still face this issue on the latest release?

**Comment by xoriole** [comment] 2023-06-16 13:44
I'll close the issue for now. If the issue re-appears, feel free to reopen the issue.

**Closed by xoriole** 2023-06-16 13:44 UTC
Labels: type: bug, needs feedback, component: GUI, status: can't reproduce
