### ISSUE TITLE
UI problem with connection settings

### ISSUE THREAD

**Issue by stevavoliajvar** [Tribler/tribler#5537] opened 2020-08-14 17:27 UTC
*Version*: Tribler version from this commit 8f1ab43f2d1049bb0e4db0a0b683c74f0474adb5 
*OS*: Debian 10

When you go Settings (gear iconj) --> Connection and try to change the type options cannot be seen due to low contrast. So user has to move mouse and highlight items to see them.

**Comment by ichorid** [comment] 2021-03-30 10:26
duplicate of #5624

**Closed by ichorid** 2021-03-30 10:26 UTC
Labels: component: GUI, type: bug
