### ISSUE TITLE
[feature request] Sorting mode and column order is not preserved across Tribler GUI restarts

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2898] opened 2017-04-06 14:28 UTC
##### Tribler version/branch+revision: #####

devel 4803abba128e2f70cffc3c3892d10817015ea20b

##### Operating system and version: #####

Linux

##### Expected behavior: #####

Closing Tribler GUI and re-opening it restores approximately the same visual state (including scroll positions in lists and column widths)

##### Actual behavior: #####

I need to rearrange columns and sort by "added date" anew.

@devos50

**Comment by ichorid** [comment] 2021-03-30 10:23
duplicate of #1261

**Closed by ichorid** 2021-03-30 10:23 UTC
Labels: component: GUI, component: UX, type: enhancement
