### ISSUE TITLE
Clicking at "Trust Graph" in GUI shows exception

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4482] opened 2019-05-05 16:01 UTC
##### Tribler version/branch+revision: #####

b6b52333908773bd303d64bcad48fbcdc897374e release-7.3.0-beta2

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Start Tribler
2. Wait for initialisation
3. Click at "Trust Graph"

##### Expected behavior: #####

Some graph being displayed

##### Actual behavior: #####

Pop-up message with exception

##### Relevant log file output: #####

```
ERROR   1557071925.31              rest_manager:80   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.TypeError'>: unhashable type: 'dict'
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1752:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1845:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:766:requestReceived
/home/tribler/tribler/Tribler/Core/Modules/restapi/rest_manager.py:114:process
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:190:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:241:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/home/tribler/tribler/Tribler/Core/Modules/restapi/trustview_endpoint.py:68:render_GET
/home/tribler/tribler/Tribler/Core/Modules/restapi/trustview_endpoint.py:35:initialize_graph
/home/tribler/tribler/Tribler/Core/Modules/TrustCalculation/local_view.py:29:__init__
/home/tribler/tribler/Tribler/Core/Modules/TrustCalculation/local_view.py:78:lay_down_nodes
/usr/lib/python2.7/dist-packages/networkx/classes/function.py:333:set_node_attributes
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 190, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 241, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/trustview_endpoint.py", line 68, in render_GET
    self.initialize_graph()
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/trustview_endpoint.py", line 35, in initialize_graph
    self.local_view = NodeVision(self.node_id)
  File "/home/tribler/tribler/Tribler/Core/Modules/TrustCalculation/local_view.py", line 29, in __init__
    self.pos = self.lay_down_nodes()
  File "/home/tribler/tribler/Tribler/Core/Modules/TrustCalculation/local_view.py", line 78, in lay_down_nodes
    nx.set_node_attributes(self.graph, new_pos, 'pos')
  File "/usr/lib/python2.7/dist-packages/networkx/classes/function.py", line 333, in set_node_attributes
    G.node[node][name] = value
TypeError: unhashable type: 'dict'
```

**Comment by qstokkink** [comment] 2019-05-05 16:29
Duplicate of #4479

**Comment by vi** [comment] 2019-05-06 12:40
Applies the `pip install` workaround, now it displays some unreadable graph with a lot of edges. The graph cannot be zoomed in, edges or nodes are not inspectable. Everything intersects heavily and clogs together.

How am I expected to use this graph? Is it just a toy or it should help diagnose some problems. For example, can the graph tell if my instance is a part of an isolated clique? Or that all neighbouring nodes are from suspiciously same IP subnet?

**Comment by qstokkink** [comment] 2019-05-06 13:59
@vi right now it's just a toy.

**Closed** 2019-05-10 11:35 UTC
Labels: bug, duplicate
