### ISSUE TITLE
Endless spinning wheels again.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#3012] opened 2017-06-23 07:04 UTC
##### Tribler version/branch+revision: #####

devel 6a9058e32d7ecdc766d73982f465c185c65d8aae

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Start Tribler Core: `twistd -n tribler`
2. Wait until `[-] Tribler started`
3. Start `./tribler.sh`

##### Expected behavior: #####

GUI window appears with Tribler UI, like it was in cf60d11468b5d8e80c84780fe632d7cc5ada8e19

##### Actual behavior: #####

GUI window appears, showing spinning cogwheels seemingly endessly. No interesting log messages appears. The window doesn't even react to closing attempts, nor SIGINT exits from the script.

**Comment by vi** [comment] 2017-06-23 07:17
Note: after trying to `git bisect`, it started working.

**Comment by vandenheuvel** [comment] 2017-06-23 08:53
@qstokkink When debugging the core seems to block at https://github.com/Tribler/tribler/blob/devel/Tribler/Core/leveldbstore.py#L145. I've had problems with that line before. Note that this bug only presents itself on my setup when there is no state directory present prior to starting Tribler.

**Comment by qstokkink** [comment] 2017-06-23 10:56
@vandenheuvel is this also an issue on `next`?

**Comment by vandenheuvel** [comment] 2017-06-23 12:54
Yes, it is.

**Comment by devos50** [comment] 2017-06-28 13:05
I'm unable to reproduce this issue, on next/devel, with and without a state directory. I will close this issue but please reopen it if you are able to reproduce it 👍

**Comment by vandenheuvel** [comment] 2017-06-28 13:58
@devos50 I can reproduce this on 9985e2dc1, at the moment I can't run any newer version due to newly introduced dependencies.

**Comment by devos50** [comment] 2017-06-28 14:51
@vandenheuvel I'm working on the dependencies. Did you have a state directory?

**Comment by vandenheuvel** [comment] 2017-06-28 18:47
@devos50 For me, this bug triggers only and always when there is no state directory. As commented above, debugging doesn't seem to get past [this line](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/leveldbstore.py#L145).

**Comment by devos50** [comment] 2018-03-22 14:19
Due to lack of information, we cannot reproduce this. Therefore I will close this issue.

**Closed by devos50** 2018-03-22 14:19 UTC
Labels: bug
