### ISSUE TITLE
[devel] Downloading while 100%?

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2530] opened 2016-08-29 17:25 UTC
##### Tribler version/branch+revision:

9f1d4d94d1a2df32b42a57017d1246d568821876 devel
##### Expected behavior:

100%-downloaded, "Seeding" downloads are only uploaded, not downloaded
##### Actual behavior:

![q](https://cloud.githubusercontent.com/assets/173219/18060341/6594712c-6e26-11e6-9f52-bbf78b9bc0c2.png)

Note: anonymity contribution is on and the balance is slowly, unsteadily growing.

Maybe it's not 100% actually? All downloads are shown as 100% in GUI, but I observe percentage reporting degrading and not being fixed as devel branch goes on...

**Comment by devos50** [comment] 2016-08-31 08:30
That's weird, I'm unable to tell at this moment whether this is an issue of the GUI or an issue located inside the core of Tribler. Anyway, we will take a look.

**Comment by devos50** [comment] 2017-01-04 10:45
@vi have you experienced this recently? I haven't seen it the latest versions.

**Comment by vi** [comment] 2017-01-04 11:38
No. It may be caused by other inconsistencies (which are already fixed or not).

**Comment by devos50** [comment] 2017-01-04 11:41
Yeah, I'm suspecting it is something in the old GUI but I'm not sure about that. I will keep this in mind but for now, I close this issue since I cannot reproduce it.

**Closed by devos50** 2017-01-04 11:41 UTC
Labels: bug
