### ISSUE TITLE
Wrong character encoding on download properties screen

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#3892] opened 2018-09-20 11:11 UTC
Steps to reproduce:
try to download any torrent which includes filenames with non-ASCII characters.
Tribler version: next, devel.

[bug](https://user-images.githubusercontent.com/2509103/45814580-5206ca00-bcd6-11e8-851f-0ca431a38f20.png)

**Comment by devos50** [comment] 2018-09-20 11:36
Duplicate of #3816 ;)

**Closed by devos50** 2018-09-20 11:36 UTC
Labels: bug
