### ISSUE TITLE
Generally need catch encoding exceptions

### ISSUE THREAD

**Issue by EinNarr** [Tribler/tribler#3365] opened 2018-01-18 12:05 UTC
GUI and loggers in Tribler seem not to catching encoding problems. (logger seems only support ASCII and GUI supports Unicode?)
![screenshot from 2018-01-18 12-59-14](https://user-images.githubusercontent.com/15276621/35097195-727c6454-fc4f-11e7-8bbd-6f52521a6255.png)

**Comment by devos50** [comment] 2018-01-18 17:58
As far as I know, we fixed most unicode errors when adding downloads. Please rebase after merging #3364  on the latest `devel` branch and try again.

**Comment by devos50** [comment] 2018-03-22 15:04
Since we cannot reproduce it, we close this issue.

**Closed by devos50** 2018-03-22 15:04 UTC
Labels: bug
