### ISSUE TITLE
RuntimeError: 'utf8' codec can't decode byte 0x7b in position 10: could not dump

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4781] opened 2019-08-29 08:41 UTC
Version: 7.3.0
Platform: Windows-10-10.0.18362-SP0
Uptime:13.0620000362
Report: [26544](http://reporter.tribler.org/stacktrace/26544)

```python
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 531, in received_settings
RuntimeError: 'utf8' codec can't decode byte 0x7b in position 10: could not dump:
dict[settings]->ConfigObj[general]->Section[state_dir]->str::'C:\\Users\\D\xe1vid\\AppData\\Roaming\\.Tribler'
dict[settings]->ConfigObj[general]->Section[ec_keypair_filename]->str::'C:\\Users\\D\xe1vid\\AppData\\Roaming\\.Tribler\\ec.pem'
dict[settings]->ConfigObj[trustchain]->Section[ec_keypair_filename]->str::'C:\\Users\\D\xe1vid\\AppData\\Roaming\\.Tribler\\ec_multichain.pem
```

Update: comment from the user:
> It is due my pc has a non-utf á character.

**Comment by ichorid** [comment] 2019-08-29 12:06
The problem is that the user home dir includes unicode characters. Some time ago I've tried to run Tribler in this configuration. I had fixed all the bug I could, but I found some to be nearly unfixable on Python3. The only real fix here is to move to Python3 and/or use `pathlib` everywhere.

**Comment by xoriole** [comment] 2019-09-18 13:38
Additional stacktrace from the reporter. This time the path is for the watch folder.
```python
Traceback (most recent call last):
File "TriblerGUI\tribler_window.py", line 531, in received_settings
RuntimeError: 'utf8' codec can't decode byte 0x38 in position 33: could not dump:
dict[settings]->ConfigObj[watch_folder]->Section[directory]->str::'C:/Users/User/Downloads/Torrent\xb4s'
```

**Comment by ichorid** [comment] 2020-01-04 20:53
Closed by Pathlib and Python3 PR.

**Closed by ichorid** 2020-01-04 20:53 UTC
Labels: bug, unicode
