### ISSUE TITLE
Could not unpack item 5: QQHHBH

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#3563] opened 2018-04-05 17:33 UTC
Got this error while trying to connect to swarm to download Ubuntu torrent anonymously:

```
ERROR:DiscoveryCommunity:Exception occurred while handling packet!
Traceback (most recent call last):
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/deprecated/community.py", line 283, in on_packet
    self.decode_map[data[22]](source_address, data)
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/deprecated/community.py", line 232, in on_introduction_request
    auth, dist, payload = self._ez_unpack_auth(IntroductionRequestPayload, data)
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/deprecated/community.py", line 63, in _ez_unpack_auth
    dist, payload, unknown_data = self.serializer.unpack_to_serializables(format, remainder[23:])
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 295, in unpack_to_serializables
    serializable.optional_format_list, offset)
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 234, in unpack_multiple
    out.append(self.unpack(format, data, current_offset))
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 208, in unpack
    return self._packers[format].unpack_from(data, offset)
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 106, in unpack_from
    out = super(DefaultStruct, self).unpack_from(buffer, offset)
PackError: Failed to unserialize IntroductionRequestPayload
PackError: Could not unpack item 5: QQHHBH
error: unpack_from requires a buffer of at least 23 bytes
```

This message repeats periodically, always in pairs. Anonymous downloading doesn't work.
This only happens when I try to connect to the real swarm with my [download script](https://github.com/ichorid/libtorrent-latency-benchmark/tree/bytes). Local LXC leecher->router->seeder tests work OK.
@qstokkink, could you provide some comment on this?

**Comment by qstokkink** [comment] 2018-04-06 07:29
Duplicate of https://github.com/Tribler/py-ipv8/issues/80

**Closed by qstokkink** 2018-04-06 07:29 UTC
Labels: bug
