### ISSUE TITLE
7.3.0-beta4: Crash when just rinning in background

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4546] opened 2019-06-09 02:09 UTC
##### Tribler version/branch+revision: #####

d6cb10efd60fc995f0db1ac07406715e96f422e6 v7.3.0-beta4

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Start Tribler
2. Wait for a while

##### Expected behavior: #####

No errors

##### Actual behavior: #####

Exception, Tribler shuts down

##### Relevant log file output: #####

```
Traceback (most recent call last):
  File "/home/tribler/tribler/TriblerGUI/event_request_manager.py", line 114, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'ipv8.messaging.anonymization.tunnelcrypto.CryptoException'>: Error encrypting message for unknown circuit 2949800338
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1355:gotResult
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1342:_inlineCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:457:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:565:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:651:_runCallbacks
/home/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/hidden_services.py:305:dht_callback
/home/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/hidden_services.py:319:send_peers_response
/home/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py:492:send_cell
/home/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/payload.py:110:encrypt
]
```

**Comment by egbertbouman** [comment] 2019-06-09 10:44
Duplicate of https://github.com/Tribler/tribler/issues/4522. This was fixed weeks ago, but apparently, beta4 is still running the old IPv8 pointer because of compatibility issues.

**Closed by egbertbouman** 2019-06-09 10:44 UTC
Labels: bug

**Comment by vi** [comment] 2019-06-09 10:49
Shall I pin Tribler to beta2 until #4503 is merged?

**Comment by vi** [comment] 2019-06-09 10:57
Maybe Tribler should backport a pyipv8 fix to version it is compatible with and temporarily switch submodule pointer to that backported fix?

**Comment by egbertbouman** [comment] 2019-06-09 12:19
@vi Yes, you could just keep using beta2, or if you're feeling lucky you could try to run beta4 and cherry-pick IPv8 commit 23f45d742f7912a8bbaf9e377d65a272fd88d189.

We'll have to discuss internally how best to handle this and if we can provide some kind of temporary solution for our beta users.

**Comment by vi** [comment] 2019-06-09 12:54
23f45d742f7912a8bbaf9e377d65a272fd88d189 gets applies to beta4-pointed pyipv8 commit successfully.

Tribler seems to run without that problem after that.

Maybe just create a temporary branch in pyipv8 from 4beb0369d66336a250478af2180c102cf0d6f310 and apply easy-backportable fixes there?

**Comment by synctext** [comment] 2019-06-09 20:40
OK, next Beta time?

**Comment by qstokkink** [comment] 2019-06-10 05:49
> OK, next Beta time?

That is exactly why this problem persists. We didn't wait for either #4503 or #4535 to be merged to release beta 4. We should make sure either one of those PRs is merged before we do any new beta release.

**Comment by devos50** [comment] 2019-06-10 08:05
I should have finished #4503 earlier (at least before beta 4 was released), sorry for that.

Anyway, I opened #4547 which should make the required changes and update the IPv8 pointer to the latest commit. Replacing the market implementation with a submodule seemed way more work than I initially thought since moving the wallet logic to another location is non-trivial.

**Comment by xoriole** [comment] 2019-06-10 10:28
Latest IPv8 includes the fix for this issue but as of Friday, the latest IPv8 was not compatible with Tribler devel so pointer was not updated for the release (pending market PR). This release included some breaking changes on channel schema(again) to be tested by the users in the holidays. 

We'll do another beta this week after the issues with compatibilities are fixed.
