### ISSUE TITLE
assert self._cursor is not None, "Database.close() has been called or Database.open() has not been called"

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2313] opened 2016-06-19 05:36 UTC
Multichain produced this error while Tribler was closing.

Error while running with a special libtribler.conf: allchannel, search, channels, preview_channels all = "False".
```
INFO    1466314271.21       community:132   MULTICHAIN: Schedule Block called. Candidate: {95.211.155.142:34721} UP: 290 DOWN: 2528755
ERROR   1466314271.21             log:443   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 377, in on_tunnel_remove
    self.schedule_block(candidate, tunnel.bytes_up, tunnel.bytes_down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 140, in schedule_block
    self.publish_signature_request_message(candidate, total_amount_sent_mb, total_amount_received_mb)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 154, in publish_signature_request_message
    message = self.create_signature_request_message(candidate, up, down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 168, in create_signature_request_message
    total_up_requester, total_down_requester = self._get_next_total(up, down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 343, in _get_next_total
    total_up, total_down = self.persistence.get_total(self._public_key)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/database.py", line 265, in get_total
    db_result = self.execute(db_query, (public_key, public_key)).fetchone()
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/database.py", line 277, in execute
    assert self._cursor is not None, "Database.close() has been called or Database.open() has not been called"
exceptions.AssertionError: Database.close() has been called or Database.open() has not been called

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 377, in on_tunnel_remove
    self.schedule_block(candidate, tunnel.bytes_up, tunnel.bytes_down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 140, in schedule_block
    self.publish_signature_request_message(candidate, total_amount_sent_mb, total_amount_received_mb)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 154, in publish_signature_request_message
    message = self.create_signature_request_message(candidate, up, down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 168, in create_signature_request_message
    total_up_requester, total_down_requester = self._get_next_total(up, down)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/community.py", line 343, in _get_next_total
    total_up, total_down = self.persistence.get_total(self._public_key)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/community/multichain/database.py", line 265, in get_total
    db_result = self.execute(db_query, (public_key, public_key)).fetchone()
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/pouwelse/GIT-pulls/tribler/Tribler/dispersy/database.py", line 277, in execute
    assert self._cursor is not None, "Database.close() has been called or Database.open() has not been called"
exceptions.AssertionError: Database.close() has been called or Database.open() has not been called
```

**Comment by Captain-Coder** [comment] 2016-07-04 15:09
This issue should be fixed by PR [2380](https://github.com/Tribler/tribler/pull/2380) Though it is hard to test since I could not reproduce this error.

**Comment by synctext** [comment] 2016-07-21 19:06
OK, thnx.. Closing..

**Closed** 2016-07-21 19:06 UTC
Labels: bug
