### ISSUE TITLE
Log file - rc7-2-g5a5d2d8

### ISSUE THREAD

**Issue by colin1497** [Tribler/tribler#1932] opened 2016-02-09 15:03 UTC
Wanted to share a log dump.  Do with it as you will.

```
ERROR   1454826799.70       community:716   already seen this indentifier in this batch, previous candidate {192.168.19.249:6882 67.165.90.51:6882} this one {192.168.19.249:6882 67.165.90.51:6882}
ERROR   1454887105.47             log:443   Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 797, in runUntilCurrent
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1064, in on_data
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 722, in relay_packet
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1255, in crypto_relay
    
  File "Tribler\community\tunnel\crypto\tunnelcrypto.pyo", line 81, in decrypt_str
    
  File "cryptography\hazmat\primitives\ciphers\base.pyo", line 174, in finalize
    
  File "cryptography\hazmat\backends\openssl\ciphers.pyo", line 137, in finalize
    
cryptography.exceptions.InvalidTag: 

Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 797, in runUntilCurrent
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1064, in on_data
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 722, in relay_packet
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1255, in crypto_relay
    
  File "Tribler\community\tunnel\crypto\tunnelcrypto.pyo", line 81, in decrypt_str
    
  File "cryptography\hazmat\primitives\ciphers\base.pyo", line 174, in finalize
    
  File "cryptography\hazmat\backends\openssl\ciphers.pyo", line 137, in finalize
    
cryptography.exceptions.InvalidTag: 
ERROR   1454959111.09             log:443   Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 797, in runUntilCurrent
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1064, in on_data
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 722, in relay_packet
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1255, in crypto_relay
    
  File "Tribler\community\tunnel\crypto\tunnelcrypto.pyo", line 81, in decrypt_str
    
  File "cryptography\hazmat\primitives\ciphers\base.pyo", line 174, in finalize
    
  File "cryptography\hazmat\backends\openssl\ciphers.pyo", line 137, in finalize
    
cryptography.exceptions.InvalidTag: 

Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 797, in runUntilCurrent
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1064, in on_data
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 722, in relay_packet
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1255, in crypto_relay
    
  File "Tribler\community\tunnel\crypto\tunnelcrypto.pyo", line 81, in decrypt_str
    
  File "cryptography\hazmat\primitives\ciphers\base.pyo", line 174, in finalize
    
  File "cryptography\hazmat\backends\openssl\ciphers.pyo", line 137, in finalize
    
cryptography.exceptions.InvalidTag: 
ERROR   1454990468.16             log:443   Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 797, in runUntilCurrent
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1064, in on_data
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 722, in relay_packet
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1255, in crypto_relay
    
  File "Tribler\community\tunnel\crypto\tunnelcrypto.pyo", line 81, in decrypt_str
    
  File "cryptography\hazmat\primitives\ciphers\base.pyo", line 174, in finalize
    
  File "cryptography\hazmat\backends\openssl\ciphers.pyo", line 137, in finalize
    
cryptography.exceptions.InvalidTag: 

Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 797, in runUntilCurrent
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1064, in on_data
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 722, in relay_packet
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1255, in crypto_relay
    
  File "Tribler\community\tunnel\crypto\tunnelcrypto.pyo", line 81, in decrypt_str
    
  File "cryptography\hazmat\primitives\ciphers\base.pyo", line 174, in finalize
    
  File "cryptography\hazmat\backends\openssl\ciphers.pyo", line 137, in finalize
    
cryptography.exceptions.InvalidTag: 
ERROR   1455013757.70             log:443   Unhandled error in Deferred:
Unhandled error in Deferred:
ERROR   1455013757.70             log:443   Unhandled Error
Traceback (most recent call last):
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
  File "twisted\internet\base.pyo", line 824, in runUntilCurrent
    
  File "twisted\internet\task.pyo", line 218, in __call__
    
--- <exception caught here> ---
  File "twisted\internet\defer.pyo", line 139, in maybeDeferred
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 412, in do_circuits
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 474, in create_circuit
    
exceptions.KeyError: 'LibNaCLPK:\x06a\x05\x1a\xe8J\x9b#d\xb8Y\xf6_o\xc3\xe1i\xb2s\xe4\xc5\xee\xc4S\xd0UB\x10\x0f\x00=\x13\x95\x02\xae\x97b\x1eE\xf9\x0eD]R\x10#R\xdd\xd7Y\xeb\x1b\xc7\x00\xd8\x9c\xc5\xb8\xedtzzw\xa3'

Unhandled Error
Traceback (most recent call last):
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
  File "twisted\internet\base.pyo", line 824, in runUntilCurrent
    
  File "twisted\internet\task.pyo", line 218, in __call__
    
--- <exception caught here> ---
  File "twisted\internet\defer.pyo", line 139, in maybeDeferred
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 412, in do_circuits
    
  File "Tribler\community\tunnel\tunnel_community.pyo", line 474, in create_circuit
    
exceptions.KeyError: 'LibNaCLPK:\x06a\x05\x1a\xe8J\x9b#d\xb8Y\xf6_o\xc3\xe1i\xb2s\xe4\xc5\xee\xc4S\xd0UB\x10\x0f\x00=\x13\x95\x02\xae\x97b\x1eE\xf9\x0eD]R\x10#R\xdd\xd7Y\xeb\x1b\xc7\x00\xd8\x9c\xc5\xb8\xedtzzw\xa3'
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 669, in sesscb_states_callback
  File "Tribler\dispersy\util.pyo", line 35, in helper
  File "Tribler\community\tunnel\hidden_community.pyo", line 250, in monitor_downloads
  File "Tribler\community\tunnel\hidden_community.pyo", line 639, in create_introduction_point
  File "Tribler\community\tunnel\tunnel_community.pyo", line 500, in create_circuit
KeyError: 'LibNaCLPK:\x06a\x05\x1a\xe8J\x9b#d\xb8Y\xf6_o\xc3\xe1i\xb2s\xe4\xc5\xee\xc4S\xd0UB\x10\x0f\x00=\x13\x95\x02\xae\x97b\x1eE\xf9\x0eD]R\x10#R\xdd\xd7Y\xeb\x1b\xc7\x00\xd8\x9c\xc5\xb8\xedtzzw\xa3'
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 669, in sesscb_states_callback
  File "Tribler\dispersy\util.pyo", line 35, in helper
  File "Tribler\community\tunnel\hidden_community.pyo", line 250, in monitor_downloads
  File "Tribler\community\tunnel\hidden_community.pyo", line 639, in create_introduction_point
  File "Tribler\community\tunnel\tunnel_community.pyo", line 500, in create_circuit
KeyError: 'LibNaCLPK:~\x1c9\xa7\xfb\x10\xe8\x97\x1cp\xf5P\xf3Z\xd0\x0c\x9e\x9aJ\xc9\x80\x8b\xa5\x94\n\xab\xd60g\x10\xcb\x00\xcc\xb1`\x08g"\xd3\xb0\'\xe1\xe1$]\x00\xa4\x83r\x06/\xdb\xe6\x1dt`o\xc2\xd4T\xa8\x04\x8a\x85'
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 669, in sesscb_states_callback
  File "Tribler\dispersy\util.pyo", line 35, in helper
  File "Tribler\community\tunnel\hidden_community.pyo", line 250, in monitor_downloads
  File "Tribler\community\tunnel\hidden_community.pyo", line 639, in create_introduction_point
  File "Tribler\community\tunnel\tunnel_community.pyo", line 474, in create_circuit
KeyError: 'LibNaCLPK:~\x1c9\xa7\xfb\x10\xe8\x97\x1cp\xf5P\xf3Z\xd0\x0c\x9e\x9aJ\xc9\x80\x8b\xa5\x94\n\xab\xd60g\x10\xcb\x00\xcc\xb1`\x08g"\xd3\xb0\'\xe1\xe1$]\x00\xa4\x83r\x06/\xdb\xe6\x1dt`o\xc2\xd4T\xa8\x04\x8a\x85'
Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 669, in sesscb_states_callback
  File "Tribler\dispersy\util.pyo", line 35, in helper
  File "Tribler\community\tunnel\hidden_community.pyo", line 250, in monitor_downloads
  File "Tribler\community\tunnel\hidden_community.pyo", line 639, in create_introduction_point
  File "Tribler\community\tunnel\tunnel_community.pyo", line 500, in create_circuit
KeyError: 'LibNaCLPK:~\x1c9\xa7\xfb\x10\xe8\x97\x1cp\xf5P\xf3Z\xd0\x0c\x9e\x9aJ\xc9\x80\x8b\xa5\x94\n\xab\xd60g\x10\xcb\x00\xcc\xb1`\x08g"\xd3\xb0\'\xe1\xe1$]\x00\xa4\x83r\x06/\xdb\xe6\x1dt`o\xc2\xd4T\xa8\x04\x8a\x85'
ERROR   1455020024.18 tunnel_community:918   TunnelCommunity: ignoring create for circuit 1830057781 from ('115.248.248.13', 59553) (too many relays 100)
ERROR   1455020056.48 tunnel_community:918   TunnelCommunity: ignoring create for circuit 1026923581 from ('115.248.248.13', 59553) (too many relays 100)
ERROR   1455020088.52 tunnel_community:918   TunnelCommunity: ignoring create for circuit 430824431 from ('115.248.248.13', 59553) (too many relays 100)
ERROR   1455020092.95 tunnel_community:918   TunnelCommunity: ignoring create for circuit 3785424324 from ('176.14.3.197', 7764) (too many relays 100)
ERROR   1455020125.53 tunnel_community:918   TunnelCommunity: ignoring create for circuit 811801757 from ('176.14.3.197', 7764) (too many relays 100)
ERROR   1455020130.27 tunnel_community:918   TunnelCommunity: ignoring create for circuit 4184077312 from ('76.170.83.99', 7759) (too many relays 100)
ERROR   1455020174.45 tunnel_community:918   TunnelCommunity: ignoring create for circuit 
```

**Comment by whirm** [comment] 2016-02-09 15:28
Care to give any more info about it? 
Which version are you running? 
many active downloads? 
Do you now how to reproduce it?

Thanks!

**Comment by whirm** [comment] 2016-02-09 15:52
Oh, just saw the version on the title

**Comment by whirm** [comment] 2016-02-09 16:14
Ok, that's a duplicate of #1617.

Which Debian/Ubuntu version are you running?

**Comment by rjruigrok** [comment] 2016-02-09 19:57
I remember this error from the time I was working on anonimity. It's just decrypting with the wrong key. Why it got the wrong key may be caused by:
* the introductionpoint circuit is extended with a candidate that is already part of the circuit, causing a crypto error. Should not happen anyway, thorough analysis of the debug log may reveal why and how this candidate is discovered.
* the pubkey of the introduction point changed (e.g. due to a restart), while other peers in the network are still exchanging the old key information. 
* A hostile peer may have forged the key of a candidate while pexing information about candidates, thus polluting the network with wrong information. I doubt this is the case but it's possible. :)

Except when it happens in case 1 (that indicates a bug in the circuit creating logic), ignoring (just log to debug) the exception is the best solution for case 2 and 3.

**Comment by whirm** [comment] 2016-02-10 11:01
@rjruigrok there's no integrity check for the message either right? so if a bit flips on transit, we will get the same result.

**Comment by whirm** [comment] 2016-02-10 11:53
I'll add your comments to the code for future reference. Thanks!

**Closed** 2016-02-10 13:48 UTC
Labels: bug, duplicate, needs feedback
