### ISSUE TITLE
Message is too long to send: message too long (GUI disconnected with this backtrace)

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2782] opened 2017-02-05 12:59 UTC
##### Tribler version/branch+revision: #####

67f495c194b4286b3c82a07676ea228430ac8957

##### Operating system and version: #####

Linux, twisted version `16.2.0-1~bpo8+1`

##### Relevant log file output: #####

Core's console output:

```
2017-02-05T15:55:00+0300 [-] UDPScraper starting on 40382
2017-02-05T15:55:00+0300 [-] Starting protocol <Tribler.Core.TorrentChecker.session.UDPScraper instance at 0x7f06ed2568c0>
2017-02-05T15:55:01+0300 [UDPScraper (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 248, in doRead
	    self.protocol.datagramReceived(data, addr)
	  File "/home/tribler/tribler/Tribler/Core/TorrentChecker/session.py", line 406, in datagramReceived
	    self.udpsession.handle_connection_response(data)
	  File "/home/tribler/tribler/Tribler/Core/TorrentChecker/session.py", line 619, in handle_connection_response
	    self.scraper.write_data(message)
	  File "/home/tribler/tribler/Tribler/Core/TorrentChecker/session.py", line 389, in write_data
	    self.transport.write(data)  # no need to pass the ip and port
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 274, in write
	    raise error.MessageLengthError("message too long")
	twisted.internet.error.MessageLengthError: Message is too long to send: message too long.
```

**Comment by Thomasedv** [comment] 2017-02-05 19:12
Believe this is the same as issue #2779, 

Also having it, stated there that large torrents could reach the limit. Probably not the best day to download a 376 GB torrent with 700 ish files in. If that's the one causing the issue.

**Comment by vi** [comment] 2017-02-05 20:12
Note: there is a terabyte torrent with a lot of files for testing: https://sites.google.com/site/tlmcfiles/Touhou%20lossless%20music%20collection%20v.18.torrent. It also contains a lot of unicodey or otherwise tricky filenames.

If Tribler can operate with this torrent then it is probably ready for big and tricky torrents.

It actually worked with old Tribler (with most files excluded, yet slowing down entire Tribler).

**Comment by devos50** [comment] 2017-02-12 13:20
@vi this is not related to large torrent files. The problem is located in the torrent checker module. I recently removed a limiter but it turns out that this was necessary. I will restore the relevant code next week and fix this issue.

**Comment by devos50** [comment] 2017-02-13 11:20
This is actually a duplicate of #2779, closing this issue in favour of that one.

**Closed by devos50** 2017-02-13 11:20 UTC
Labels: bug
