### ISSUE TITLE
[7.7.0] OSError [WinError 127] Procedure not found: 'RtlIpv6AddressToStringA'

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5922] opened 2021-01-11 05:12 UTC
The error was on importing `psutil` module in `check_for_missing_dependencies`. [This explanation on StackOverflow](https://stackoverflow.com/questions/14627047/windowserror-error-127-the-specified-procedure-could-not-be-found) suggests that the error may arise when multiple DLLs have the same name and incorrect DLL become loaded.

A number of affected users: low

**Comment by qstokkink** [comment] 2023-11-27 10:03
Supposedly, this is solved in newer versions of `psutil`. This is unconfirmed but we also haven't seen this error on Sentry anymore since 2021. I'll close this.

**Closed by qstokkink** 2023-11-27 10:03 UTC
Labels: type: bug
