### ISSUE TITLE
API

### ISSUE THREAD

**Issue by jkaberg** [Tribler/tribler#1107] opened 2014-12-31 12:46 UTC
Tribler seriously needs an API (featuring **ALL** features/settings seen in the UI) with proper authentication (api key and/or username/password)

API based on the following would be cool and "in-time" with other web technologys;
http://jsonapi.org/
http://en.wikipedia.org/wiki/Representational_state_transfer

The above suggestion along with https://github.com/Tribler/tribler/issues/1041 and the anoynmous features present in current (and upcomeing) Tribler version will make Tribler a torrent strong suit and should allow Tribler to expand exponentialy on NAS devices and other none UI machines (witch in my opinion are the ones who will end up "carrying" the anonymous Tribler network in the end)

PS: And no, the existing WebUI (utorrent rip-off) is not what I'm asking for.

**Comment by lfdversluis** [comment] 2015-12-10 14:46
Duplicate of https://github.com/Tribler/tribler/issues/267

**Comment by devos50** [comment] 2015-12-10 14:47
@whirm can you assign me on this one?

**Comment by jkaberg** [comment] 2015-12-10 14:52
@lfdversluis Not really a dupe since #267 is about running the client without an UI and this is about an possible API which is an different matter

@devos50 I take it you'r gonna take a stab at this, would you mind elaborating on how you plan to design the API? I'm very curious =)

**Comment by devos50** [comment] 2015-12-10 14:59
@jkaberg I'm currently playing around with the Tribler core files and trying to classify parts into the GUI and core API. I try this by creating a very basic CLI so I can see how various methods are invoked. I will have to discuss the design of the API in more detail with @whirm. If you have any input or ideas about this, please let us know and we'll keep in touch :+1: .

**Comment by synctext** [comment] 2015-12-10 15:15
@jkaberg  ettermiddag,
This is finally getting some developers attention, in the form of "LibTribler" as we call it internally.
This is part of the refactoring and code quality improvement step.
A json-based REST approach seems logical. Don't know the alternatives sufficiently.
JSON-RPC, etc. https://wiki.python.org/moin/WebServices

**Comment by jkaberg** [comment] 2015-12-10 19:49
@devos50 Well, I only have a wish list but I'll throw in here so you can see


search the Tribler network. when returning search results I'd love to see stuff like
* torrent name
* torrent hash / id
* leechers / seeders
.. and other stuff related to the torrent.
- sort search results based on criterias such as seeders, size etc

manage torrents
* initiate download from .torrent or magnet
* start torrent(s)
* remove torrent(s) (optional with data)
* pause torrent(s)

manage the client
* set download location
* set upload / download speed
... and more

as @synctext mentioned an [JSON-RPC](http://json-rpc.org/) would be very nice

**Comment by devos50** [comment] 2016-03-05 14:53
@jkaberg thanks for your suggestions. I'm currently working on creating an API. An essential part of this is splitting the current GUI from the core logic in Tribler. You can follow my work in #1961.

Moreover, I'm working on a complete new GUI, written in Qt, which is powered by the API I'm creating. I'm working on them both.

I currently do not have a lot of endpoints. Searching for torrents is possible but currently it only searches the local database and results coming in from Dispersy are not written on the event socket yet. The goal is to have a minimal API that supports searching for channels, displaying torrents in a channel and streaming of a torrent (which is most probably the hardest part).

**Comment by jkaberg** [comment] 2016-03-05 16:29
@devos50 Very nice to see. If the entire GUI is powered by the API (meaing all GUI functions depend on the API) then my feature request should be 100% complete once your done :-)

Looking forward to it!

**Comment by jkaberg** [comment] 2016-06-22 13:51
@devos50 Few things come to my mind now, just wanted to make sure you are aware

Alot of people uses reverseproxy to hide stuff behind an frontend server, so it would be good if you take into account **base url** and [headers](https://en.wikipedia.org/wiki/X-Forwarded-For)

Aswell as the possibility of TLS encryption with self signed and signed certificates. 

It's alot easier to implement these things initialy then later on (thats why I mention them here :-)

**Comment by devos50** [comment] 2016-09-11 17:23
@jkaberg thanks for the suggestion. We currently have an extensive API (see the documentation) that is ready for some beta testing. Also, the new GUI will utilize this API.

Can you create separate issues for suggestions regarding enhancements of the API? I'm closing this issue.

**Closed by devos50** 2016-09-11 17:23 UTC
Labels: enhancement, needs discussion
