### ISSUE TITLE
New downloads do not appear in the list as downloads immediately.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#3033] opened 2017-07-01 15:24 UTC
##### Tribler version/branch+revision: #####

devel 9985e2dc167d25139eedece09faa60b9e7e66f6c (can't run newer version)

##### Steps to reproduce the behavior: #####

1. Start Tribler Core
2. Start Tribler GUI
3. Add download from magnet link
4. Go to download list

##### Expected behavior: #####

The download is immediately visible and cancellable in "Downloading" under respective name. Information is at least as filled in as when displaying the download destination, anonymity and file selection window.

##### Actual behavior: #####

The download is named like "No data" (or something) with status "Waiting for metadata". Files are not displayed (although when doing the addition there was the name and file list). After a while (or after stop/restart) it gets displayed as a normal download.

**Comment by devos50** [comment] 2018-03-22 14:24
This is intended behavior: when adding a magnet link, you have limited information (sometimes as limited as only the infohash). It needs to fetch the data like files and torrent name from the DHT. This is why you temporarily see 'No data'.

Since this is expected, I will close this issue. Please let me know if you have any other questions.

**Closed by devos50** 2018-03-22 14:24 UTC
Labels: enhancement
