### ISSUE TITLE
test_torrentchecking.py contains a sleep

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2129] opened 2016-04-25 10:28 UTC
`test_torrent_checking` contains a hardcoded `sleep` to wait for torrent health results. We should refactor it to make it asynchronous and remove the `sleep`.

**Comment by lfdversluis** [comment] 2016-04-26 16:57
Duplicate of #2130 implicit

**Comment by whirm** [comment] 2016-04-26 17:08
I'm closing this even if it's the older one. As the other supersedes it.

**Closed by whirm** 2016-04-26 17:08 UTC
Labels: bug
