### ISSUE TITLE
[7.5.0-RC5] TypeError: a bytes-like object is required, not 'str' (in debug window)

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5371] opened 2020-06-13 11:47 UTC
From the error reporter:

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\debug_window.py", line 750, in <lambda>
File "src\tribler-gui\tribler_gui\debug_window.py", line 763, in on_libtorrent_session_received
File "src\tribler-gui\tribler_gui\debug_window.py", line 771, in save_to_file
TypeError: a bytes-like object is required, not 'str'
```

**Comment by ichorid** [comment] 2020-06-13 11:57
duplicate of closed #5334

**Closed by ichorid** 2020-06-13 11:57 UTC
Labels: bug
