### ISSUE TITLE
Tribler stopping some seeding torrents on start up.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2768] opened 2017-01-29 22:22 UTC
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler_7.0.0-alpha2-34-g67f495c_x64.exe

##### Operating system and version: #####
Windows 10 Home,
Version 1607
OS-Build: 14393.693

##### Expected behavior: #####
Starting Tribler normally, torrents that still haven't met their upload/download ratio, will still keep state seeding.

##### Actual behavior: #####
Starting tribler, many torrents are stopped, despite not being manually stopped, and having a upload ratio which is far below 1(at least according to the GUI), when the target in the settings is 2.0 and has been like that since installation. State file said "user_stopped = True", despite not being manually stopped by me. 

It's unclear if the stop happens on shutdown or startup, to be clear. And it didn't apply to all seeding torrents, the first time, it happened to a few, the next time the majority. Seems like a recent change, with my installation, as it didn't do earlier on the same build. Torrents with other states, are unaffected/unchanged as far as i know.

Quick post-issue creation addition: Only recent change, is that i added a watch folder, and changed my torrent downloader to not start/open torrents by itself, but rather only download the torrents to the download folder. So, there's a decent chance many of those stopped torrents where added from that folder by running them, and tribler encounters a conflict or something when those completed torrents are in the watch folder. Or torrents that have state seeding in the watch folder in general encounter some issue. 

##### Steps to reproduce the behavior: #####
Unclear exactly, but it happens to some torrents when tribler is started. As far as i know, tribler was closed normally too. 

##### Relevant log file output: #####
No log output.

**Comment by devos50** [comment] 2017-02-23 13:22
I'm unable to reproduce this issue. The only way that the downloads are stopped is that that the ratio uploaded/downloaded data is at least two. I will add the total amount of data downloaded/uploaded to the download details pane so you can verify manually whether this is the case for these downloads.

**Comment by Thomasedv** [comment] 2017-02-25 11:51
Well, i myself have been unable to replicate this. It's kinda odd, since you can't multi select torrents and stop them at once, there's no way i could have accidentally stopped so many of them. So far, it only happened that one time.

**Comment by themusicgod1** [comment] 2018-02-22 15:25
i had this happen to me more than once, but haven't seen it since 7.1

**Comment by devos50** [comment] 2018-03-22 13:51
We assume this to be fixed, therefore closing this issue.

**Closed by devos50** 2018-03-22 13:51 UTC
Labels: bug
