### ISSUE TITLE
[7.7.0] TypeError: on_reload_torrent_info() takes 1 positional argument but 2 were given - Plz fix asap

### ISSUE THREAD

**Issue by Shidouuu** [Tribler/tribler#5908] opened 2021-01-06 21:06 UTC
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.7.0
##### Operating system and version: #####
Win 10
##### Steps to reproduce the behavior: #####
1. Open torrent
2. Crash
##### Expected behavior: #####
Tribler opens the torrent
##### Actual behavior: #####
Crash
##### Relevant log file output: #####
```
Traceback (most recent call last):
  File "src\tribler-gui\tribler_gui\utilities.py", line 385, in trackback_wrapper
  File "src\tribler-gui\tribler_gui\utilities.py", line 382, in trackback_wrapper
TypeError: on_reload_torrent_info() takes 1 positional argument but 2 were given
```

I'd fix it myself but I'm not very familiar with the Tribler code. Should be an easy fix, but it's a pretty major bug so please do so asap

**Comment by kozlovsky** [comment] 2021-01-07 05:55
Thank you for reporting! This bug is a duplicate of #5903, and it is already fixed. The bugfix release will be made in a few days.

**Closed by kozlovsky** 2021-01-07 05:55 UTC

**Comment by Shidouuu** [comment] 2021-01-07 12:23
oops
