### ISSUE TITLE
[7.5.4] error in tablecontentmodel.RemoteTableModel.on_query_results

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5755] opened 2020-11-27 06:25 UTC
It seems that in certain situations, the response may not contain `uuid` field. Right now this case is not handled:
```python
        if not remote or (uuid.UUID(response.get('uuid')) in self.remote_queries):
            self.add_items(response['results'], on_top=remote or on_top)
            if "total" in response:
                self.channel_info["total"] = response["total"]
                update_labels = True
            elif remote and uuid.UUID(response.get('uuid')) == CHANNELS_VIEW_UUID:
```

```
Traceback (most recent call last):, 
  File "tribler_gui/widgets/tablecontentmodel.py", line 197, in on_query_results, 
  File "uuid.py", line 163, in __init__, 
TypeError: one of the hex, bytes, bytes_le, fields, or int arguments must be given
```

**Comment by synctext** [comment] 2020-11-27 06:57
morning! Any ideas how to reproduce this?

**Comment by kozlovsky** [comment] 2020-11-27 07:40
I don't fully understand all the details of the frontend-backend communication mechanics yet, but from my current understanding, it may happen if the frontend sends several concurrent requests to the backend and the `on_query_results` signal handler receives a response from another request which does not contain the expected `uuid` field.

Probably @ichorid could explain it better.

I think that the fix should be in ignoring the response if it does not contain `uuid` field.
```python
if response.get('uuid') is None:
    return False
```
@ichorid am I correct that in this case the response will be successfully processed by another signal handler?

**Comment by ichorid** [comment] 2020-11-28 10:28
The UUID argument is only used on remote queries. 
However, I refactored the mechanism for 7.6. Let's see how it fares.

**Comment by kozlovsky** [comment] 2020-11-28 21:38
Probably the reason for the error is not in the UUID argument per se but in concurrent processing of two different events. Current `devel` branch code still expects that non-empty response should contain `uuid` field, and that is probably an incorrect expectation if concurrent responses are possible (but maybe concurrent responses aren't possible, it is just my hypotheses at this moment)

**Comment by ichorid** [comment] 2020-11-29 10:00
Well, the problem is, the same mechanism is used to show the results of both remote and local queries. The local ones don't use UUIDs, why remote ones still do. So, there is a possibility for wrong interpretation. The latest refactor simplified the thins a bit, but there is still space for improvement. I'll look at the problem as soon as I finish the more important stuff for 7.6 (e.g. the DB upgrader)

**Comment by ichorid** [comment] 2020-12-03 16:10
After the refactoring, UUID should *always* be on remote entries. If it is not there, that's a bug. So, closing this one until we see this on 7.6

**Closed by ichorid** 2020-12-03 16:10 UTC
Labels: bug
