### ISSUE TITLE
V7.3.0-rc1  Could not connect with the Tribler Core within 60 seconds

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#4709] opened 2019-07-23 15:26 UTC
```
Traceback (most recent call last):
  File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 136, in <lambda>
    self.reply.error.connect(lambda error: self.on_error(error, reschedule_on_err=reschedule_on_err))
  File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 81, in on_error
    raise RuntimeError("Could not connect with the Tribler Core within 60 seconds")
RuntimeError: Could not connect with the Tribler Core within 60 seconds
```

reverting to 7.3.0-beta6 corrects the issue.

**Comment by devos50** [comment] 2019-07-23 15:37
Thank you for your report! We have received more similar issues related to this so I'm closing this one, and continue the discussion in #4695.

Duplicate of #4695

**Closed by devos50** 2019-07-23 15:37 UTC

**Comment by Dmole** [comment] 2019-07-23 15:50
@devos50 :smirk: you should have mentioned V7.3.0-rc1 in your bug report so I could find it
"##### Tribler version/branch+revision: #####"
