### ISSUE TITLE
Seeding and stil download taken?

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3760] opened 2018-07-24 09:19 UTC
##### Tribler version/branch+revision: #####
Juli 23th Edition
##### Operating system and version: #####
WIndows 10 Insider 17713
##### Steps to reproduce the behavior: #####
Only seeding, NO download
##### Expected behavior: #####
Expect Karma point not to decrese because of download/taken amount, while NOT downloaden
##### Actual behavior: #####
Karma point are going dosn, while not atually downloading
##### Relevant log file output: #####
Please explain on the websiote why with 7.1 we see these small amounts of down- and up-loads in bytes.
These small amount add up to a large amount and make yoyr total of karma point go down.
While testing I had about 2600 points and now a days I have -30. 
Please explain why we now see these download and uploads statistics in bytes while we are ONLY seeding!

**Comment by qstokkink** [comment] 2018-07-24 10:33
Semi-duplicate of #3718

**Comment by devos50** [comment] 2019-02-28 09:26
Fixed in #4254

**Closed by devos50** 2019-02-28 09:26 UTC
Labels: duplicate, enhancement

**Comment by Nubro01** [comment] 2019-03-16 11:01
Beste Martijn,

Wat is de huidige download locatie voor Tribler 7.3. Is het https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Custom/ ?? Want daar staan alleen maar 7.2.0 bestanden.

Bedankt

Ron Nuberg

**Comment by devos50** [comment] 2019-03-16 11:13
@Nubro01 see https://jenkins-ci.tribler.org/job/Build_Tribler_Devel/152/ (the tag is off indeed but it is the bleeding edge code from our development branch).
