### ISSUE TITLE
Looped error message when trying to download a magnet link before it resolved into a torrent

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2686] opened 2016-12-21 23:52 UTC
##### Tribler version/branch+revision: #####

e744e2ca7090b9f3258694125e52f7fe66194e96 devel

##### Steps to reproduce the behavior: #####

Add unpopular magnet link and press download button immediately, without waiting for file list to load up.

##### Actual behavior: #####

`invalid torrent handle used` messages is shown in a loop, even if I restart GUI reusing core.

##### Expected behavior: #####

Download gets added to the queue. When the loading files finally completes (maybe someday, in further Tribler runs), it automatically begins downloading (all files gets selected).

##### Relevant log file output: #####

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tribler/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py", line 196, in render_GET
    "total_pieces": download.get_num_pieces(), "vod_mode": download.get_mode() == DLMODE_VOD,
  File "/home/tribler/tribler/Tribler/Core/Libtorrent/__init__.py", line 17, in invoke_func
    return f(*args, **kwargs)
  File "/home/tribler/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py", line 451, in get_num_pieces
    if get_info_from_handle(self.handle):
  File "/home/tribler/tribler/Tribler/Core/Utilities/torrent_utils.py", line 102, in get_info_from_handle
    return handle.get_torrent_info()
RuntimeError: invalid torrent handle used
```

**Comment by devos50** [comment] 2016-12-29 08:44
@vi thanks for the report. This shouldn't be caused by the fact that you clicked the download button before the items were loaded. It seems that something in libtorrent goes wrong.

Are you willing to share the magnet link that you used?

**Comment by devos50** [comment] 2017-01-02 11:10
@vi no it works for me and I get no error. It waits for metadata to be downloaded. What's your libtorrent version?

I will make sure that this exception is captured.

**Comment by vi** [comment] 2017-01-02 11:37
Is libtorrent a submodule or it uses system library?

```
# apt-cache policy python-libtorrent libtorrent-rasterbar7
python-libtorrent:
  Installed: 0.16.18-1
libtorrent-rasterbar7:
  Installed: 0.16.18-1
```

If Triber uses system libtorrent then it should check for version and show warning (at least in console)

**Comment by devos50** [comment] 2017-01-02 13:00
@vi it uses the libtorrent of the system. 0.16.18 is rather old but should be supported (in fact, it's the minimum supported version).

**Comment by vi** [comment] 2017-01-02 17:32
I think in any case those error messages should not be looped.

If error happens duing the displaying of some information, pop up message may be not very appropriate. There can be banner with "send report" button somewhere instead.

Now this (and some other) error message pops up again and again until I go do other tab or close GUI. The number of time I need to press Esc (mouse click does not work for many buttons) is number of seconds the error message has been displayed.

**Comment by vi** [comment] 2017-01-02 23:13
After upgrading libtorrent-rasterbar to version 1.1.1 the problem has vanished.

**Comment by devos50** [comment] 2017-01-03 08:54
@vi great! I will close the issue when we handle the message appropriately (I already have a commit for that).

**Closed** 2017-01-10 09:46 UTC
Labels: bug
