### ISSUE TITLE
GUI Test Failed; TimeoutException: The list was not populated within 10 seconds

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3127] opened 2017-10-02 14:29 UTC
While running GUI tests [test_gui.py](https://github.com/Tribler/tribler/blob/next/Tribler/Test/GUI/test_gui.py), occasionally we encounter timeout exception as shown below. This exception is not limited to a single test case but occurs at different test cases at different times and is difficult to reproduce.

```
ERROR: test_search (Tribler.Test.GUI.test_gui.TriblerGUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sandip/personal/tribler/Tribler/Test/GUI/test_gui.py", line 323, in test_search
    self.wait_for_list_populated(window.search_results_list, num_items=20)
  File "/home/sandip/personal/tribler/Tribler/Test/GUI/test_gui.py", line 115, in wait_for_list_populated
    raise TimeoutException("The list was not populated within 10 seconds")
TimeoutException: The list was not populated within 10 seconds
```

**Comment by qstokkink** [comment] 2017-10-03 09:32
We should probably start debugging this from this line:
https://github.com/Tribler/tribler/blob/df0b3829350e0af8321207c86479357bf3f89cf7/TriblerGUI/event_request_manager.py#L83
We can then see if the core is sending the right/enough info to the GUI.

**Comment by devos50** [comment] 2018-05-29 12:43
We haven't experienced this issue in a very long time. Therefore I close this issue.

**Comment by qstokkink** [comment] 2018-08-15 13:59
It's still here: #3789

**Comment by devos50** [comment] 2018-08-15 14:04
Hmm we should really look into this one soon.

**Comment by qstokkink** [comment] 2018-08-15 14:08
Yes, this one is very nasty as it affects (seemingly) all GUI unit tests waiting for a list to be populated. For example the most recent one was for `test_manage_playlist` and OP was for `test_search`:

```python
Traceback (most recent call last):
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_tests_GUI_win64\tribler\Tribler\Test\GUI\test_gui.py", line 615, in test_manage_playlist
    self.wait_for_list_populated(window.playlist_manage_in_playlist_list)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_tests_GUI_win64\tribler\Tribler\Test\GUI\test_gui.py", line 146, in wait_for_list_populated
    raise TimeoutException("The list was not populated within 10 seconds")
TimeoutException: The list was not populated within 10 seconds
```

**Comment by qstokkink** [comment] 2018-08-15 14:17
@devos50 could it be that `QTreeWidget`s need `>` instead of `>=`, or is this intended?

https://github.com/Tribler/tribler/blob/19d20f5196edcdfd937fcce8b114bfa841fb0960/Tribler/Test/GUI/test_gui.py#L138-L141

**Comment by qstokkink** [comment] 2018-08-15 14:53
I reproduced this (on Ubuntu 16.10) and printed the length of the generated data from the [`TriblerData`](https://github.com/Tribler/fake-tribler-api/blob/next/FakeTriblerAPI/tribler_data.py#L19) class:

```
======================================================================
ERROR: test_manage_playlist (Tribler.Test.GUI.test_gui.TriblerGUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/quinten/tribler/tribler/Tribler/Test/GUI/test_gui.py", line 615, in test_manage_playlist
    self.wait_for_list_populated(window.playlist_manage_in_playlist_list)
  File "/home/quinten/tribler/tribler/Tribler/Test/GUI/test_gui.py", line 146, in wait_for_list_populated
    raise TimeoutException("The list was not populated within 10 seconds")
TimeoutException: The list was not populated within 10 seconds
-------------------- >> begin captured stdout << ---------------------
channels: 139
torrents: 23
torrent_files: 23
subscribed_channels: 25
downloads: 21
rss_feeds: 14
trustchain_blocks: 101
order_book: 2
transactions: 45
orders: 43
```

There seem to be enough of every generated resource.

**Comment by qstokkink** [comment] 2018-08-15 15:01
Reproduced again, this time printed the amount of items in the tracked list:

```python
    def wait_for_list_populated(self, llist, num_items=1, timeout=10):
        for _ in range(0, timeout * 1000, 100):
            QTest.qWait(100)
            if isinstance(llist, QListWidget) and llist.count() >= num_items:
                print "QListWidget has", llist.count()
                if not isinstance(llist.itemWidget(llist.item(0)), LoadingListItem):
                    return
            elif isinstance(llist, QTreeWidget) and llist.topLevelItemCount() > num_items:
                print "QTreeWidget has", llist.topLevelItemCount()
                if not isinstance(llist.topLevelItem(0), LoadingListItem):
                    return
```

```python
======================================================================
ERROR: test_manage_playlist (Tribler.Test.GUI.test_gui.TriblerGUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/quinten/tribler/tribler/Tribler/Test/GUI/test_gui.py", line 617, in test_manage_playlist
    self.wait_for_list_populated(window.playlist_manage_in_playlist_list)
  File "/home/quinten/tribler/tribler/Tribler/Test/GUI/test_gui.py", line 148, in wait_for_list_populated
    raise TimeoutException("The list was not populated within 10 seconds")
TimeoutException: The list was not populated within 10 seconds
-------------------- >> begin captured stdout << ---------------------
QListWidget has 4

--------------------- >> end captured stdout << ----------------------
```

I find it odd that the print statement only triggers once, with enough elements in the list (4 >= 1).

**Comment by devos50** [comment] 2019-02-25 11:56
I have not seen this issue in a very long time. I consider it fixed (we still have the metainfo signal issue however).

**Closed by devos50** 2019-02-25 11:56 UTC
Labels: bug
