### ISSUE TITLE
Play included video file moves to .unwanted

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2650] opened 2016-11-23 15:46 UTC
Play a video file removes the original download dir (incl. contents) and moves/renames the video file to the .unwanted dir with the name of what looks like the infohash and without the original video file extension. Renaming it back it still plays outside Tribler.

**Comment by devos50** [comment] 2016-11-23 15:48
I should add that the torrent only contains one file, created with the `createtorrent` endpoint.

**Comment by brussee** [comment] 2016-11-23 16:34
I have copied the files back again and now:
 - playback works with the videoserver on the phone that recorded and created the video torrent.
- playback also works on the pc connected to the phone's api and adb port forwarding!

**Comment by devos50** [comment] 2016-11-26 13:52
This one was also caused by the incorrect creation of a single-file torrent, causing the path to be wrong and a confused libtorrent. Should be fixed by #2649.

**Closed** 2016-11-29 20:11 UTC
Labels: bug
