### ISSUE TITLE
Download progress bar does not get removed in search results when deleting an existing download

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6303] opened 2021-09-05 07:50 UTC
Steps to reproduce:
- Start download something from the search results - the download starts and the download progress bar appears.
- Remove the just-added download.
- Go back to the search results.

The download progress bar remains in the search results list, giving a false impression that the download has not correctly been stopped.

**Comment by drew2a** [comment] 2021-09-16 09:56
This issue probably related to #5886

**Comment by ichorid** [comment] 2021-09-24 16:01
duplicate of #5886

**Closed by ichorid** 2021-09-24 16:01 UTC
Labels: type: bug, type: enhancement, component: GUI, estimation: 1 day, status: reproduced
