### ISSUE TITLE
Settings are lost on upgrade to 7.4.0

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5084] opened 2020-02-01 17:05 UTC
1. On first run of 7.4.0 (after earning tokens with 7.3.2) Tribler acts like it's a fresh install (0 tokens).
2. On the 2nd run Tribler remembers the token balance but not the download/watch folders.
3. `/tmp/*tribler*` should be cleaned up on exit
4. If the distributed ledger is for preventing information hiding and double-spending of token minting, it's not working; Restoring a backup of ~/.Tribler restores spent tokens.

**Comment by devos50** [comment] 2020-02-03 08:45
Thank you for your report! This is actually a duplicate of #5006, which I will upgrade to a high priority issue. Please continue the discussion in that issue. 👍

**Closed by devos50** 2020-02-03 08:45 UTC
Labels: bug
