### ISSUE TITLE
Tribler won't run with wxPython-3.0.2 (Fedora 23)

### ISSUE THREAD

**Issue by sergiomb2** [Tribler/tribler#1790] opened 2015-12-14 03:00 UTC
Tribler version: 6.5.0-rc6
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/tribler_main.py", line 232, in __init__
    self.splash.tick)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/MainFrame.py", line 203, in __init__
    self.channeldetailspanel = ChannelDetails(self.splitter_bottom_window)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_details.py", line 1464, in __init__
    self.createAllTabs()
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_details.py", line 1493, in createAllTabs
    self.detailsTab.Layout()
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 11496, in Layout
    return _core_.Window_Layout(*args, **kwargs)
type: C++ assertion "m_growableRows[n] < nrows" failed at ./src/common/sizer.cpp(1874) in AdjustForGrowables(): invalid growable row index

Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 1131, in CreateItems
    list_expanded=self.list_expanded)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1129, in __init__
    ListItem.__init__(self, *args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 54, in __init__
    self.AddComponents(leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1132, in AddComponents
    ListItem.AddComponents(self, leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 92, in AddComponents
    style=self.columns[i].get('style', 0) | wx.ST_NO_AUTORESIZE | wx.ST_DOTS_END,
AttributeError: 'module' object has no attribute 'ST_DOTS_END'
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 1131, in CreateItems
    list_expanded=self.list_expanded)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1129, in __init__
    ListItem.__init__(self, *args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 54, in __init__
    self.AddComponents(leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1132, in AddComponents
    ListItem.AddComponents(self, leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 92, in AddComponents
    style=self.columns[i].get('style', 0) | wx.ST_NO_AUTORESIZE | wx.ST_DOTS_END,
AttributeError: 'module' object has no attribute 'ST_DOTS_END'
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 1131, in CreateItems
    list_expanded=self.list_expanded)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1129, in __init__
    ListItem.__init__(self, *args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 54, in __init__
    self.AddComponents(leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1132, in AddComponents
    ListItem.AddComponents(self, leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 92, in AddComponents
    style=self.columns[i].get('style', 0) | wx.ST_NO_AUTORESIZE | wx.ST_DOTS_END,
AttributeError: 'module' object has no attribute 'ST_DOTS_END'
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 1131, in CreateItems
    list_expanded=self.list_expanded)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1129, in __init__
    ListItem.__init__(self, *args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 54, in __init__
    self.AddComponents(leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1132, in AddComponents
    ListItem.AddComponents(self, leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 92, in AddComponents
    style=self.columns[i].get('style', 0) | wx.ST_NO_AUTORESIZE | wx.ST_DOTS_END,
AttributeError: 'module' object has no attribute 'ST_DOTS_END'
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 1131, in CreateItems
    list_expanded=self.list_expanded)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1129, in __init__
    ListItem.__init__(self, *args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 54, in __init__
    self.AddComponents(leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_item.py", line 1132, in AddComponents
    ListItem.AddComponents(self, leftSpacer, rightSpacer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 119, in invoke_func
    return func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list_body.py", line 92, in AddComponents
    style=self.columns[i].get('style', 0) | wx.ST_NO_AUTORESIZE | wx.ST_DOTS_END,
AttributeError: 'module' object has no attribute 'ST_DOTS_END'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 16762, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list.py", line 2181, in __SetData
    self.ResizeListItems()
  File "/usr/share/tribler/Tribler/Main/vwxGUI/list.py", line 2252, in ResizeListItems
    item.vSizer.Detach(item.hSizer)
AttributeError: 'NoneType' object has no attribute 'vSizer'

**Comment by whirm** [comment] 2015-12-14 12:43
Tribler 6.5.* will not be compatible with 2.8. There's a PR that will be soon merged into `devel` that adds support for WX3.0. But it's not stable enough yet.

**Comment by devos50** [comment] 2015-12-14 12:52
Wx 3.0 support is still under development. We can use some testers for the Wx3 support branch. Could you please check out https://github.com/Tribler/tribler/pull/1786 and test whether this works for your environment?

**Comment by sergiomb2** [comment] 2015-12-15 03:47
I tested your pull request (1) also added the last commits (2) tribler started ! but can't enter in settings (3) , the rest seems that is working .
(1)
https://patch-diff.githubusercontent.com/raw/Tribler/tribler/pull/1786.diff
(2)
https://github.com/Tribler/tribler/compare/v6.5.0-rc6...next.diff
(3)
Traceback (most recent call last):
  File "/usr/share/tribler/Tribler/Main/vwxGUI/TopSearchPanel.py", line 158, in OnSettings
    self.guiutility.ShowPage('settings')
  File "/usr/share/tribler/Tribler/Main/vwxGUI/__init__.py", line 128, in invoke_func
    func(*args, **kwargs)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/GuiUtility.py", line 114, in ShowPage
    dialog = SettingsDialog()
  File "/usr/share/tribler/Tribler/Main/vwxGUI/settingsDialog.py", line 91, in __init__
    self._seeding_panel, self._seeding_id = self.__create_s4(tree_root, hsizer)
  File "/usr/share/tribler/Tribler/Main/vwxGUI/settingsDialog.py", line 653, in __create_s4
    radios[seeding_mode].SetValue(True)
KeyError: None

**Comment by devos50** [comment] 2015-12-15 09:39
Great that it is starting up. I've been looking for the cause of your `keyError` and apparently, a config parameter has been renamed recently (https://github.com/Tribler/tribler/commit/cd6a6279239a03d4aeced5825de963f21cbdce9e). Could you please backup your `.Tribler` directory and try with a fresh one instead? @whirm do you have ideas about how we can fix this?

**Comment by whirm** [comment] 2015-12-15 10:02
@devos50 I'll have a look.

@sergiomb2 could you create a separate issue for that stacktrace?

**Comment by sergiomb2** [comment] 2015-12-16 03:32
in reply to devos50, yes, clean ~/.Tribler , the key error is gone.
@whirm  I will do that in next stacktrace ok ?

**Comment by nicoechaniz** [comment] 2015-12-23 09:00
@devos50 I've tested your wx3_fixes branch and it is working, except for the Channels, which make Trible crash when clicked. This is the error:

python2.7: ../../../../src/cairo-arc.c:189: _cairo_arc_in_direction: Assertion `angle_max >= angle_min' failed.
Aborted


I also get a lot of these lines on startup:
(tribler.py:2191): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

**Comment by synctext** [comment] 2015-12-24 08:11
semi dupe of #875

Great to see people helping us out and testing. Appricated.

**Comment by devos50** [comment] 2015-12-24 16:23
@nicoechaniz thanks for testing! Really helpful to have some people helping to debug.

I'm not sure what exactly went wrong but I will take a look at it as soon as I'm able to. I know about the assertions regarding the width and they seem to be non-critical in a sense that it does not hinder the execution of Tribler. Nevertheless, I will attempt to get rid of them since they may become a problem in the future.

**Comment by whirm** [comment] 2016-03-18 09:38
There's ben a bunch of fixes merged to `devel` since this issue was opened including a fix for the assertion error @nicoechaniz reported.  I'm closing this one now. If you find more issues or any of the ones reported here are still present, please check if there's an existing issue already open or create a new one otherwise.

Thanks again for your help!

**Closed by whirm** 2016-03-18 09:38 UTC
Labels: bug
