### ISSUE TITLE
credit mining - ImportError: No module named lib

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3395] opened 2018-01-25 13:11 UTC
in latest snapshot of credit mining on Ubuntu LTS 16.04
it wants Electrum...
```
INFO    1516885633.74         backend:155   Loading Windows (alt)
INFO    1516885633.75         backend:155   Loading pyfs
INFO    1516885633.75         backend:155   Loading multi
INFO    1516885633.75         backend:155   Loading Google
INFO    1516885633.75         backend:155   Loading Gnome
INFO    1516885633.75         backend:155   Loading keyczar
INFO    1516885633.75         backend:155   Loading file
INFO    1516885633.75         backend:155   Loading kwallet
ERROR   1516885633.79     run_tribler:43    No module named lib
Traceback (most recent call last):
  File "run_tribler.py", line 25, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/usr/share/tribler/TriblerGUI/tribler_window.py", line 24, in <module>
    from TriblerGUI.core_manager import CoreManager
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 10, in <module>
    from Tribler.community.market.wallet.btc_wallet import BitcoinWallet
  File "/usr/share/tribler/Tribler/community/market/wallet/btc_wallet.py", line 16, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
ImportError: No module named lib
```

**Comment by devos50** [comment] 2018-01-25 13:12
@synctext try the following commands in your terminal:

```
git submodule init
git submodule sync
git submodule update
```

**Comment by qstokkink** [comment] 2018-01-25 13:13
Duplicate of #3114 .

**Comment by synctext** [comment] 2018-01-25 13:15
This is from: https://github.com/Tribler/tribler/releases/tag/v7.1-mining-preview
How can our users fix this import error easily (e.g. no git)?

**Comment by qstokkink** [comment] 2018-01-25 13:16
@synctext was this installed into a new/clean directory?

**Comment by synctext** [comment] 2018-01-25 13:18
Yes indeed, using the Ubuntu .deb package. So we [need this](https://github.com/epsitec-sa/electrum-dev) or something?

**Comment by qstokkink** [comment] 2018-01-25 13:20
Then this is an issue with the `.deb` packing: we need to update the Debian script(s).

**Comment by qstokkink** [comment] 2018-01-25 13:29
@devos50 could this be because the token mining branch is based on `next`?

**Comment by synctext** [comment] 2018-01-25 13:54
> catch this error, print a log message and continue loading Tribler

Sounds good.

**Comment by devos50** [comment] 2018-01-25 13:57
@synctext I might have fixed it for Debian (the Electrum loading), could you try https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/lastSuccessfulBuild/artifact/tribler_7.1-mining-preview-2-g701a473_all.deb ?

**Comment by synctext** [comment] 2018-01-25 14:19
fixed! see next crash in crashreporter...

**Closed** 2018-01-29 11:26 UTC
Labels: bug
