### ISSUE TITLE
 Allow being an exit node disappear

### ISSUE THREAD

**Issue by github44-1** [Tribler/tribler#6981] opened 2022-07-24 16:43 UTC
![trible](https://user-images.githubusercontent.com/109915604/180657432-590dfdc8-a743-44da-8918-9d4970a2e120.PNG)

There was option  Allow being an exit node, but it disappeared after update

**Comment by lidarbtc** [comment] 2022-07-24 17:43
duplicate #6926

**Comment by devos50** [comment] 2022-07-25 06:58
Indeed duplicate of #6926. Given the possible ramifications of enabling this option, we removed it from the user interface. Enabling the exit node functionality is still possible by toggling the appropriate option in the Tribler configuration file.

**Closed by devos50** 2022-07-25 06:58 UTC
Labels: type: enhancement

**Comment by vi** [comment] 2023-10-11 16:54
1. What happens to profiles migrated from older Triber versions with the option enabled? Does it stay enabled or gets silently and automatically disabled?
2. Is it a good idea to still display value of exit node status in config window, even without actual checkbox?

> Tribler configuration file

3. Is it documented somewhere? `.Tribler/7.13/triblerd.conf` is short and does not seem to have this option, whether enabled or disabled.
