### ISSUE TITLE
Jenkins test fail on Windows-64

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#3634] opened 2018-05-18 16:07 UTC
Probably a race condition, or faulty test setup, or something else interferes with the test:

```python

======================================================================
ERROR: test_torrent_store_delete (Tribler.Test.Core.test_session.TestSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\test_as_server.py", line 58, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\Core\test_session.py", line 36, in test_torrent_store_delete
    session.lm.torrent_store = LevelDbStore(session.config.get_torrent_store_dir())
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\leveldbstore.py", line 71, in __init__
    rmtree(self._store_dir)
  File "c:\python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Users\\heteoma\\AppData\\Roaming\\.Tribler\\collected_torrents\\000008.ldb'
-------------------- >> begin captured logging << --------------------
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 43776
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 43776 for [libtorrent~port]
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 59562
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 59562 for [mainline_dht~port]
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 57639
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 57639 for [video_server~port]
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 51294
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 51294 for [libtorrent~anon_listen_port]
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 29120
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 29120 for [tunnel_community~socks5_listen_ports~0]
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 20707
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 20707 for [tunnel_community~socks5_listen_ports~1]
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 34217
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 34217 for [tunnel_community~socks5_listen_ports~2]
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 6605
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 6605 for [tunnel_community~socks5_listen_ports~3]
DEBUG   1526656147   network_utils:Tribler.Core.Utilities.network_utils:38   Got a working random port 55756
DEBUG   1526656147  tribler_config:TriblerConfig:123  Get random port 55756 for [tunnel_community~socks5_listen_ports~4]
ERROR   1526656147    leveldbstore:LevelDbStore:70   Corrupt LevelDB store detected; recreating database
--------------------- >> end captured logging << ---------------------
```

**Comment by ichorid** [comment] 2018-05-18 16:08
@xoriole, could you tell what is happening here?

**Comment by xoriole** [comment] 2018-05-18 16:28
This is related to https://github.com/Tribler/tribler/issues/3608
There might be an existing Tribler process running the test machine.

**Comment by qstokkink** [comment] 2018-05-19 06:47
Duplicate of #3608

**Closed by qstokkink** 2018-05-19 06:47 UTC
Labels: bug, infrastructure
