### ISSUE TITLE
Error propping up at the start every time tribler 7.13.rc1

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#7361] opened 2023-04-13 18:39 UTC
**Describe the bug**

This error props up every time I start tribler 7.13.rc1

**To Reproduce**

1. Click on 'tribler'

**Expected behavior**

Tribler should start instead of this error propping up.

> tribler.gui.utilities.CreationTraceback: 
>   File "run_tribler.py", line 103, in <module>
>   File "tribler\gui\start_gui.py", line 79, in run_gui
>   File "tribler\gui\tribler_window.py", line 203, in __init__
>   File "tribler\gui\core_manager.py", line 47, in __init__
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "tribler\gui\utilities.py", line 416, in trackback_wrapper
>   File "tribler\gui\utilities.py", line 413, in trackback_wrapper
>   File "tribler\gui\core_manager.py", line 168, in check_core_api_port
> tribler.gui.exceptions.CoreConnectTimeoutError: Can't get Core API port value within 30 seconds
> 
> --LONG TEXT--
> 
> --CONTEXT--

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Tribler's version [e.g. 7.13.rc1]

**Comment by absolutep** [comment] 2023-05-03 13:37
any update on this?

**Comment by kozlovsky** [comment] 2023-08-14 14:59
It is a duplicate of #7351. I hope it is fixed now, so now I'm closing it until it reappears in Tribler >= 7.13.0

**Closed by kozlovsky** 2023-08-14 14:59 UTC
Labels: type: bug
