### ISSUE TITLE
Crashing every 30 minutes on Windows (suspected to be OpenSSL)

### ISSUE THREAD

**Issue by LipuFei** [Tribler/tribler#1671] opened 2015-09-24 19:48 UTC
A problem found in #1588 

According to @BmetaMax, Tribler crashes every 30 minutes on his Windows. However, with a broken Windows build whose Tunnel doesn't work (and python-cryptography's openssl backend doesn't work), it doesn't crash. So I suspect that the problem could be caused by OpenSSL or python-cryptography or both.

The OpenSSL in the Windows builder is 1.0.1l (from https://slproweb.com/products/Win32OpenSSL.html).

**Comment by LipuFei** [comment] 2015-09-24 19:54
@whirm I tried to compile python-cryptography using newer versions such as 1.0.2d, but it didn't work. It will show this "no OPENSSL_Applink" error message every time I start Tribler.

When using OpenSSL on Windows, we must to include `<openssl/applink.c>` which provides this `OPENSSL_Applink()`. Otherwise, the "no OPENSSL_Applink" error message will show up. (see https://www.openssl.org/docs/faq.html)

@whirm Tried adding `<openssl/applink.c>` in python-cryptography source code. No luck in solving this problem so far. Perhaps it's M2Crypto, but then it will be very tricky because compiling M2Crypto on Windows is a nightmare... I installed M2Crypto through an installer on our Windows builder.

**Comment by whirm** [comment] 2015-10-14 11:25
@BmetaMax, I can't reproduce this crash for the life of me. I've rebuilt updated versions of all cryptography related dependencies on the builder, could you try and see if this build crashes?

https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/4/

If it still crashes, could you try overwriting the openssl DLL with this one? (the one used on the latest stable Tribler release, which I assume it didn't crash for you?)

http://www.mediafire.com/download/oc7ayrbp274zea4/SSLEAY32.dll

**Comment by whirm** [comment] 2015-10-14 15:33
@BmetaMax Ready for you to test.

**Comment by BmetaMax** [comment] 2015-11-02 17:14
@whirm Sorry guys, life overwhelmed me and I've not been around. Anyways for the past two-three weeks rc5-31-g67ea0e3 has been running inexplicably stably 95% of the time. 
The other 5% of the time the issues I have are at startup; sometimes it still crashes with the same last errors reported in the log (example pasted below), I still get an error when closing tribler, and I have this recently occurring error where a few downloads fail to reinitialize at the same state they left off at previous shutdown- I can't figure that one out yet, am open to suggestions.
The only things that I have changed is that circa 3 weeks ago I performed a clean install of windows then tribler, and manually re-added files (took forEVER!) by magnet link then pointed tribler to the right directory for partials and forced recheck, which eventually caught me back up without too much downloading of duplicate information.
So to summarize- mostly working, sometimes have to start tribler a few times before it stops crashing, I have 264 anon seeding files, and 1 download which is probably just dead and I haven't given up on yet.

Should I try the build pasted above or rc6 which is out now? Again sorry for the delay, thanks for updating the case.

A few example Log entries;
ERROR   1446478468.03 tunnel_community:1197  Dropping data packets while EXITing
ERROR   1446478699.58 tunnel_community:136   Can't resolve ip address for hostname tracker.istole.it
ERROR   1446478699.58 tunnel_community:1197  Dropping data packets while EXITing
ERROR   1446482035.73             log:443   Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 824, in runUntilCurrent
    
  File "Tribler\Main\vwxGUI\list_item.pyo", line 692, in <lambda>
    
  File "Tribler\Main\vwxGUI\list_item.pyo", line 652, in rename_or_merge
    
exceptions.WindowsError: [Error 267] The directory name is invalid: u'D:\\TriblerDownloads\\Movies\\acafddkgpj.mp4\\*.*'

Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 824, in runUntilCurrent
    
  File "Tribler\Main\vwxGUI\list_item.pyo", line 692, in <lambda>
    
  File "Tribler\Main\vwxGUI\list_item.pyo", line 652, in rename_or_merge
    
exceptions.WindowsError: [Error 267] The directory name is invalid: u'D:\\TriblerDownloads\\Movies\\acafddkgpj.mp4\\*.*'
ERROR   1446482837.51 tunnel_community:176   too many packets to a destination without a reply, removing exit socket with circuit_id 1614028477
ERROR   1446483841.39 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446483911.33 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446483919.88 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446483946.35 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446483946.44        dispersy:1728  exception during handle_callback for cell
Traceback (most recent call last):
  File "Tribler\dispersy\dispersy.pyo", line 1723, in _update
  File "Tribler\community\tunnel\tunnel_community.pyo", line 894, in on_cell
  File "Tribler\community\tunnel\tunnel_community.pyo", line 1229, in crypto_in
TypeError: %d format: a number is required, not tuple
ERROR   1446483968.62 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446483971.84 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0

**Comment by whirm** [comment] 2015-11-04 13:44
Yes, There's been a bit of stuff coming in, so maybe you want to test rc6 (no need to go further as the fixes that came afterward where just for OSX.

About this error msg:
`exceptions.WindowsError: [Error 267] The directory name is invalid: u'D:\TriblerDownloads\Movies\acafddkgpj.mp4\.'` 
Does that torrent contain a single file without a dir? Maybe an incorrect file name with a `\.` at the end?

**Comment by BmetaMax** [comment] 2015-11-04 21:56
@ whirm ok I'll install rc6 tonight. correct no dir, I don't know how that \ got there, it was a previously downloaded file that was already complete, but at the time that log was pulled it had oddly gone back to initializing and was no longer in the directory I move completed dl's to. Could it's path have been corrupted between restarts of tribler somehow?

**Comment by LipuFei** [comment] 2015-11-06 07:42
@whirm It used to create folders for single-file torrents as well. I think I had made a fix for this single file issue, and perhaps this somewhere else in Tribler is trying to use the path as a folder or so.

Take a look at the  "MyPreference" table in the sqlite database. It can also be some tunnel-related code, when it tries to restart a torrent in anon seeding mode.

**Comment by whirm** [comment] 2015-11-20 15:07
@BmetaMax About the 30 minute crash, could you give a shot at this buid?

http://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_next/73/

It contains some crypto related workarounds for the upcoming 64bit Tribler build that may fix this issue too.

**Comment by BmetaMax** [comment] 2015-11-26 18:16
@whirm Since I updated to rc6 about 3 weeks ago, everything has run fine on win8.1 though I haven't used tribler in a week. However I went to try using it today and it has crashed consistently within a few minutes of starting it up. I just downloaded that build you suggested last week and will try shortly.

I also cannot find any sort of logging; nothing under appdata\.tribler, and other programs\tribler\logging there's only 3 .pyo files which I cannot attach here.

**Comment by BmetaMax** [comment] 2015-11-27 19:42
@whirm Since last night when I uninstalled rc6 and then installed rc6-31-g9d705c5, it now opens without error, but I can no longer access settings (I click but nothing happens) otherwise seems to function fine though I've only test adding a torrent through + dialog, and right-click context management of downloads.

**Comment by whirm** [comment] 2015-12-04 17:40
@BmetaMax could you test this build?
https://jenkins.tribler.org/job/Publish_tribler_next/161/
I has a fix that should solve the settings issue.

Thanks!

**Comment by BmetaMax** [comment] 2015-12-07 23:05
@whirm Sorry it took me so long but just tried it but no, rc6-45-g95b9186 hasn't fixed the settings problem it acts the exact same.

**Comment by BmetaMax** [comment] 2015-12-07 23:10
@whirm and oddly enough now all the completed torrents I was seeding are stuck at building circuits. I'm definitely connecting and have DL & UL, ~250k & ~15k currently. I left it running a good 10 minutes at least before saying that- I noticed on earlier rc6 versions it may take a few minutes for files to change from that to seeding, but based off previous experience I've waited plenty long enough.

**Comment by whirm** [comment] 2015-12-08 10:58
Do you get anything on the log file if you start Tribler, click on settings (nothing happens), and then quit Tribler?

re building circuits: It's normal there's veeery few people acting as proxies and the big servers from the university that where helping while the network is still small are temporarily out of service.

**Comment by BmetaMax** [comment] 2015-12-26 22:56
@whirm Sorry I thought I responded already, I redid it and here's the latest log:
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\TopSearchPanel.pyo", line 158, in OnSettings
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 114, in ShowPage
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 91, in __init__
  File "Tribler\Main\vwxGUI\settingsDialog.pyo", line 653, in __create_s4
KeyError: None

**Comment by whirm** [comment] 2016-01-06 16:35
That got fixed some days ago, but I forgot to close the issue.

**Closed by whirm** 2016-01-06 16:35 UTC
Labels: bug
