### ISSUE TITLE
Missing feature, download torrent in sequential order for instant playback

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2557] opened 2016-09-30 10:14 UTC
Hello,

some torrent clients like qbittorent has option to download torrent contents in sequential order

This is very useful as one can immediately start watching downloaded movie. It would be nice to have this feature in the Tribler. So user can choose to download torrent in sequential order either before download or in the middle of downloading.

Thank You for considering

**Comment by devos50** [comment] 2016-09-30 10:17
Thank you for your comment. Our built-in video player (that is currently disabled on OS X due to incompatibility issues) uses linear download mode by default. We could enhance this feature so it is also possible to select linear download mode when not playing a video in Tribler.

**Comment by ichorid** [comment] 2020-06-12 08:24
duplicate of #1718

**Closed by ichorid** 2020-06-12 08:24 UTC
Labels: enhancement
