### ISSUE TITLE
Issues creating new torrents

### ISSUE THREAD

**Issue by tukkek** [Tribler/tribler#2897] opened 2017-04-06 00:36 UTC
I noticed two issues when creating a new torrent. They are small enough that I thought I should report them together.

1. **The "name" field you enter isn't utilized in the final .torrent** produced. This is a major problem because for any number of reasons (including filesystem encoding) I could have a filename like `replay.mp4` but actually provide a more descriptive name like *My son's soccer training, 2017-04-05*. The fact that somehow the full filename, with extension and all ends up in the .torrent file instead of the text given in the creation dialog makes me think this is, most likely a bug or oversight. Looking at the torrent file with a text editor seems to show the description gets in but the name doesn't show up anywhere. When choosing a single file, the name seems to be overwritten by the filename; when adding a directory or multiple files, the given name seems to be overridden by the parent/selected directory name.
2. When adding individual files or directories, **the default selection directory is `/usr/share/tribler`** or `/usr/share`. This is obviously unhelpful to anyone as it's just (probably) the current working directory for Python. I don't think many people are intent on sharing Tribler's binary files on the network (despite it sounding like a super meta thing to do), so it should probably default to something useful instead like a user's `$HOME` folder (Linux) or *My documents* (Windows). Remembering the last used directory is a good choice too, but as long as it defaults to something helpful instead of unhelpful, it's good enough for me.

Obviously, the second is sort of a nitpick but hopefully something that can be solved very easily too. The first though is a major usability concern. I was just coming back to Tribler after a while and intending to share some of my original content on the network but I don't think anyone is going to download something like `output.avi` if they don't even know what's inside. Sure, I could start renaming all my files too but Tribler literally asks for a torrent name and then goes on to ignore that value, so I'm writing this instead.

Tribler version: 7.0.0
Operating system: Linux

**Comment by tukkek** [comment] 2017-04-06 00:45
Forgot to add: Tribler is looking awesome! With a few rough edges like these taken care of I can totally see this becoming a major content platform! Thanks for all the work so far and congratulations to everyone involved that might be reading this :)

**Comment by devos50** [comment] 2017-04-06 08:43
Thanks for your feedback and I'm glad you like Tribler :) 👍

**Comment by devos50** [comment] 2018-03-23 13:26
Unfortunately, it seems that we don't have an influence on the name of the torrent. The name of a torrent (inside the .torrent file) is automatically generated, based on the filename(s). Therefore,  I will postpone this issue.

Regarding your second point, I changed the logic when opening a file dialog so it always opens in the home directory of the user. This should already improve the user experience. It will be available in my next pull request.

**Comment by ichorid** [comment] 2021-09-28 14:15
duplicate of #4674

**Closed by ichorid** 2021-09-28 14:15 UTC
Labels: type: enhancement, status: broken
