### ISSUE TITLE
exceptions.AssertionError: twisted_rawserver and register_task

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#1425] opened 2015-05-20 12:36 UTC
Latest devel error, with the latest tunnels enabled.

```
WARNING 1432064637.08       community:1889  drop a 155 byte packet invalid puncture identifier [dispersy-puncture] from {192.168.1.1:6421 130.161.211.245:6421}
WARNING 1432064672.71       community:1889  drop a 210 byte packet invalid response identifier [dispersy-introduction-response] from {172.31.16.69:7759 52.25.165.20:7759}
WARNING 1432064706.96       community:1889  drop a 210 byte packet invalid response identifier [dispersy-introduction-response] from {52.25.165.20:7759}
WARNING 1432064818.80       community:1889  drop a 210 byte packet invalid response identifier [dispersy-introduction-response] from {172.31.16.69:7759 52.25.165.20:7759}
WARNING 1432064818.80       community:1889  drop a 155 byte packet invalid puncture identifier [dispersy-puncture] from {192.168.1.1:6421 130.161.211.245:6421}
WARNING 1432064940.71       community:1889  drop a 210 byte packet invalid response identifier [dispersy-introduction-response] from {172.31.16.69:7759 52.25.165.20:7759}
WARNING 1432068030.63       community:1889  drop a 174 byte packet invalid response identifier [dispersy-introduction-response] from {192.168.1.1:6422 130.161.211.245:6422}
WARNING 1432068033.03       community:1889  drop a 174 byte packet invalid response identifier [dispersy-introduction-response] from {192.168.1.1:6422 130.161.211.245:6422}
ERROR   1432070677.51             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/APIImplementation/TwistedRawServer.py", line 18, in <lambda>
    reactor.callFromThread(lambda: self.register_task(task_name, reactor.callLater(delay, wrapper)))
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/taskmanager.py", line 36, in register_task
    assert not self.is_pending_task_active(name), name
exceptions.AssertionError: twisted_rawserver 174303

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/APIImplementation/TwistedRawServer.py", line 18, in <lambda>
    reactor.callFromThread(lambda: self.register_task(task_name, reactor.callLater(delay, wrapper)))
  File "/home/pouwelse/GITHUB/tribler/Tribler/dispersy/taskmanager.py", line 36, in register_task
    assert not self.is_pending_task_active(name), name
exceptions.AssertionError: twisted_rawserver 174303
ERROR   1432071939.07         session:260   Tracker[HTTP, http://tracker.pomf.se:80/announce] Failed to send HTTP SCRAPE message: [Errno 111] Connection refused
ERROR   1432072111.47         session:260   Tracker[HTTP, http://bt2.rutracker.org:80/ann?uk=01quWTyKBR] Failed to send HTTP SCRAPE message: [Errno 110] Connection timed out
ERROR   1432072166.58         session:260   Tracker[HTTP, http://tracker.pomf.se:80/announce] Failed to send HTTP SCRAPE message: [Errno 111] Connection refused
ERROR   1432072701.93         handler:460   TFTP[49597 C 104.230.64.115:7759][f81cc281c26a813c3f31fdd7e42c7a707d8b567b.torrent] Got ACK with block# 15 while expecting 16
ERROR   1432073169.78         session:260   Tracker[HTTP, http://bt2.rutracker.org:80/ann?uk=01quWTyKBR] Failed to send HTTP SCRAPE message: [Errno 110] Connection timed out
```

**Comment by whirm** [comment] 2015-06-29 13:45
duplicate of #1512

**Closed** 2015-06-29 13:46 UTC
Labels: bug, duplicate
