### ISSUE TITLE
Tribler crashes while downloading test torrent

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#2653] opened 2016-11-23 20:19 UTC
On latest devel, https://github.com/Tribler/tribler/commit/374ef8d2010c7beafd223bdb7cfad7e2afafedf1, while downloading a torrent called 'Automatic test of Tribler Anonymous downloading and seeding'. After restarting Tribler the torrent is no longer on the download page, while it was shortly listed before the crash.
```
WARNING:TunnelLogger:Received message for unknown circuit ID: 659750054
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/git/tribler/TriblerGUI/core_manager.py", line 65, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1195, in run
    self.mainLoop()
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 415, in on_tunnel_remove
    self.schedule_block(candidate, tunnel.bytes_up, tunnel.bytes_down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 144, in schedule_block
    self.publish_signature_request_message(candidate, total_amount_sent_mb, total_amount_received_mb)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 158, in publish_signature_request_message
    message = self.create_signature_request_message(candidate, up, down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 172, in create_signature_request_message
    total_up_requester, total_down_requester = self._get_next_total(up, down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 378, in _get_next_total
    total_up, total_down = self.persistence.get_total(self._public_key)
  File "/home/user/git/tribler/Tribler/community/multichain/database.py", line 273, in get_total
    db_result = self.execute(db_query, (public_key, public_key)).fetchone()
  File "/home/user/git/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/user/git/tribler/Tribler/dispersy/database.py", line 277, in execute
    assert self._cursor is not None, "Database.close() has been called or Database.open() has not been called"
exceptions.AssertionError: Database.close() has been called or Database.open() has not been called

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/git/tribler/TriblerGUI/core_manager.py", line 65, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1195, in run
    self.mainLoop()
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 415, in on_tunnel_remove
    self.schedule_block(candidate, tunnel.bytes_up, tunnel.bytes_down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 144, in schedule_block
    self.publish_signature_request_message(candidate, total_amount_sent_mb, total_amount_received_mb)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 158, in publish_signature_request_message
    message = self.create_signature_request_message(candidate, up, down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 172, in create_signature_request_message
    total_up_requester, total_down_requester = self._get_next_total(up, down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 378, in _get_next_total
    total_up, total_down = self.persistence.get_total(self._public_key)
  File "/home/user/git/tribler/Tribler/community/multichain/database.py", line 273, in get_total
    db_result = self.execute(db_query, (public_key, public_key)).fetchone()
  File "/home/user/git/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/user/git/tribler/Tribler/dispersy/database.py", line 277, in execute
    assert self._cursor is not None, "Database.close() has been called or Database.open() has not been called"
exceptions.AssertionError: Database.close() has been called or Database.open() has not been called

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/git/tribler/TriblerGUI/core_manager.py", line 65, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1195, in run
    self.mainLoop()
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 415, in on_tunnel_remove
    self.schedule_block(candidate, tunnel.bytes_up, tunnel.bytes_down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 144, in schedule_block
    self.publish_signature_request_message(candidate, total_amount_sent_mb, total_amount_received_mb)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 158, in publish_signature_request_message
    message = self.create_signature_request_message(candidate, up, down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 172, in create_signature_request_message
    total_up_requester, total_down_requester = self._get_next_total(up, down)
  File "/home/user/git/tribler/Tribler/community/multichain/community.py", line 378, in _get_next_total
    total_up, total_down = self.persistence.get_total(self._public_key)
  File "/home/user/git/tribler/Tribler/community/multichain/database.py", line 273, in get_total
    db_result = self.execute(db_query, (public_key, public_key)).fetchone()
  File "/home/user/git/tribler/Tribler/dispersy/util.py", line 150, in wrapper
    return_value = func(*args, **kargs)
  File "/home/user/git/tribler/Tribler/dispersy/database.py", line 277, in execute
    assert self._cursor is not None, "Database.close() has been called or Database.open() has not been called"
exceptions.AssertionError: Database.close() has been called or Database.open() has not been called

Unhandled error in Deferred:


Traceback (most recent call last):
Failure: Tribler.Core.exceptions.SaveResumeDataError: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
Unhandled error in Deferred:


Traceback (most recent call last):
Failure: Tribler.Core.exceptions.SaveResumeDataError: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
ERROR:TriblerGUI:Got Tribler core error: 2
ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/user/git/tribler/TriblerGUI/tribler_request_manager.py", line 84, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded```

When restarting tribler and adding the same torrent again,
```...
Unhandled error in Deferred:


Traceback (most recent call last):
Failure: Tribler.Core.exceptions.SaveResumeDataError: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
Unhandled error in Deferred:


Traceback (most recent call last):
Failure: Tribler.Core.exceptions.SaveResumeDataError: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
ERROR:TriblerGUI:Got Tribler core error: 2
ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/user/git/tribler/TriblerGUI/tribler_request_manager.py", line 84, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/user/git/tribler/TriblerGUI/tribler_request_manager.py", line 84, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
./tribler.sh: line 48:  3699 Segmentation fault      (core dumped) python2.7 $TRIBLER_SCRIPT "$@"
```
After adding the torrent again, another crash:
```
Unhandled error in Deferred:


Traceback (most recent call last):
Failure: Tribler.Core.exceptions.SaveResumeDataError: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
Unhandled error in Deferred:


Traceback (most recent call last):
Failure: Tribler.Core.exceptions.SaveResumeDataError: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
ERROR:TriblerGUI:Got Tribler core error: 2
ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/user/git/tribler/TriblerGUI/tribler_request_manager.py", line 84, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/user/git/tribler/TriblerGUI/tribler_request_manager.py", line 84, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
./tribler.sh: line 48:  3699 Segmentation fault      (core dumped) python2.7 $TRIBLER_SCRIPT "$@"
```

When I restart tribler again without adding the torrent, it crashes once more, within seconds:
```
QIODevice::read (QDisabledNetworkReply): device not open
ERROR:root:Traceback (most recent call last):
  File "/home/user/git/tribler/TriblerGUI/widgets/downloadspage.py", line 80, in on_received_downloads
    for download in downloads["downloads"]:
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR:TriblerGUI:Got Tribler core error: 2
ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/user/git/tribler/TriblerGUI/tribler_request_manager.py", line 84, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
./tribler.sh: line 48:  3945 Segmentation fault      (core dumped) python2.7 $TRIBLER_SCRIPT "$@"
```

Lastly, Tribler also crashed when I clicked around on the download page, seems unrelated but included to be sure:
```
ERROR:TriblerGUI:Got Tribler core error: 2
ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/user/git/tribler/TriblerGUI/tribler_request_manager.py", line 84, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
./tribler.sh: line 48:  2796 Segmentation fault      (core dumped) python2.7 $TRIBLER_SCRIPT "$@"
```

**Comment by devos50** [comment] 2016-11-24 13:56
@vandenheuvel 

`exceptions.AssertionError: Database.close() has been called or Database.open() has not been called` did this happen when shutting down Tribler? If so, this is a known error.

**Comment by vandenheuvel** [comment] 2016-11-29 12:36
No, I wasn't opening or closing Tribler.

**Comment by devos50** [comment] 2016-11-30 08:59
@vandenheuvel can you easily reproduce the error?

**Comment by devos50** [comment] 2017-01-11 14:25
It seems that the connection to the multichain database is not opened correctly or that the database is not created. @vandenheuvel is the `multichain.db` file available in your Tribler state directory (`.Tribler/sqlite/multichain.db`)?

**Comment by vandenheuvel** [comment] 2017-01-20 14:20
@devos50 I am no longer able to reproduce the error. Removing the `multichain.db` file doesn't cause any error when adding torrents.

**Comment by devos50** [comment] 2017-01-20 14:33
It should regenerate the multichain database when it's removed. I will close this issue since I haven't seen it in the crash reporter anymore.

**Closed by devos50** 2017-01-20 14:33 UTC
Labels: bug
