### ISSUE TITLE
TunnelCommunity: failed to decrypt message

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5711] opened 2020-10-31 19:14 UTC
Latest `devel`, traceback on console:

```python
[PID:34076] 2020-10-31 20:08:42,494 - ERROR <community:352> TriblerTunnelCommunity.on_packet(): Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/tribler/src/pyipv8/ipv8/community.py", line 348, in on_packet
    result = handler(source_address, data)
  File "/home/tribler/src/pyipv8/ipv8/messaging/anonymization/community.py", line 611, in on_cell
    cell.decrypt(self.crypto, circuit=circuit, relay_session_keys=self.relay_session_keys.get(circuit_id))
  File "/home/tribler/src/pyipv8/ipv8/messaging/anonymization/payload.py", line 265, in decrypt
    self.message = crypto.decrypt_str(self.message,
  File "/home/tribler/src/pyipv8/ipv8/messaging/anonymization/tunnelcrypto.py", line 87, in decrypt_str
    return aesgcm.decrypt(salt + content, 0)
  File "/home/tribler/.pyenv/versions/tribler382/lib/python3.8/site-packages/libnacl/aead.py", line 59, in decrypt
    return libnacl.crypto_aead_chacha20poly1305_ietf_decrypt(ctxt, aad, nonce, self.sk)
  File "/home/tribler/.pyenv/versions/tribler382/lib/python3.8/site-packages/libnacl/__init__.py", line 829, in crypto_aead_chacha20poly1305_ietf_decrypt
    raise ValueError('Failed to decrypt message')
ValueError: Failed to decrypt message
```

**Comment by egbertbouman** [comment] 2020-10-31 20:42
Do you remember if this happened directly after a re-start? Did the `TunnelCommunity` continue to work normally?

**Comment by ichorid** [comment] 2020-10-31 21:22
Yes, it happened just after a restart. I don't know if TunnelCommunity was able to work normally, I did not checked it.

**Comment by egbertbouman** [comment] 2020-10-31 22:14
OK, thanks! In that case, it's probably an old packet.  I'll fix this in IPv8.

**Comment by kozlovsky** [comment] 2021-08-30 06:56
Reappeared in 7.10:

[ipv8/messaging/anonymization/tunnelcrypto.py:79](https://github.com/Tribler/py-ipv8/blob/e0688ec862460f4dd4dc8b6595186711b7ff6ebb/ipv8/messaging/anonymization/tunnelcrypto.py#L79)

```python
    def decrypt_str(self, content, key, salt):
        # content contains the tag and salt_explicit in plaintext
        if len(content) < 24:
            raise CryptoException("truncated content")

        aead = AEAD(key)
        return aead.decrypt(salt + content, 0)  # ValueError: Failed to decrypt message
```

**Comment by egbertbouman** [comment] 2021-09-01 00:50
When using `TunnelCrypto.encrypt_str/decrypt_str` manually (i.e., without going through `CellPayload`), the `ValueError` should be caught.

Also, in `_ours_on_created_extended`, the `CryptoException` should be a `ValueError`.

**Comment by qstokkink** [comment] 2022-03-07 11:49
For the most recent traceback, the `tunnel_community` traceback is a false positive for the core error. The printed tracebacks are not from the Python interpreter, but from a logging statement. This is [an excerpt from line 647](https://github.com/Tribler/py-ipv8/blob/7a94e31c1036b7d13491dc63a8e8d55ed34f0c7d/ipv8/messaging/anonymization/community.py#L647):

```python
try:
    handler = self.decode_map_private[msg_id]
    result = handler(source_address, data, circuit_id)  # line 647, in on_packet_from_circuit, 
    if iscoroutine(result):
        self.register_anonymous_task('on_packet_from_circuit', ensure_future(result), ignore=(Exception,))
except Exception:
    self.logger.error("Exception occurred while handling packet!\n"
                      + ''.join(format_exception(*sys.exc_info())))
```

Looking at the timing of events in the Sentry issue, I'd suspect the `subprocess  |  file -b /Applications/Tribler.app/Contents/MacOS/tribler` call to have caused this particular crash.

**Comment by qstokkink** [comment] 2023-07-19 09:18
@Tribler/dev It seems this original issue has long-since been fixed in https://github.com/Tribler/tribler/pull/5717, neither of the linked Sentry issues still exist, and the cause for reopening this issue was a false positive. Can we close this issue?

**Comment by drew2a** [comment] 2023-07-19 10:03
As I'm the current Tribler master this week, I've taken the responsibility to close this issue :)

**Closed by drew2a** 2023-07-19 10:03 UTC
Labels: type: bug
