### ISSUE TITLE
system tray dialog empty

### ISSUE THREAD

**Issue by themusicgod1** [Tribler/tribler#2953] opened 2017-05-16 17:22 UTC
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.0 next 94a67a3
7.0 next a85bf006

##### Operating system and version: #####
Ubuntu 17.04 + xfce4 4.12.3
Ubuntu 17.04 + unity 7.5.0+17.04.20170407.1-0ubuntu1
(both with and without moving ~/.tribler out of the way)

##### Expected behavior: #####
Right or left clicking on system tray brings menu to click on...something.  Maybe bring tribler to the foreground if it's currently in the background?

##### Actual behavior: #####
unity: menu comes up, but it is blank.  Looks like there's space for about 8 menu items, but they are all empty.  Or no menu comes up at all.
xfce4: no menu comes up at all

##### Steps to reproduce the behavior: #####
right click on tribler system tray icon

##### Relevant log file output: #####
right and left clicking doesn't seem to put anything into the logs.

**Comment by devos50** [comment] 2017-05-17 07:43
Duplicate of #2922, please use this issue to discuss the empty tray menu 👍

**Closed** 2017-05-17 13:30 UTC
Labels: duplicate
