### ISSUE TITLE
Seeing myself?

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#6766] opened 2022-02-11 15:48 UTC
With version 7.11 and previous on my Asus Z170 Premium MB with two Nic"s I see my own two network cards.
This never happened before, so?
![image](https://user-images.githubusercontent.com/1146496/153623110-318fc98f-b2b3-43ae-994e-094e891dd15b.png)

**Comment by qstokkink** [comment] 2022-02-11 15:55
This seems to be the same as #5528. You should be able to safely ignore this. However, it is not aesthetically pleasing.

**Comment by devos50** [comment] 2022-02-13 12:31
Since this issue is a duplicate of #5528 and an answer has been provided in that issue, I will close this one.

**Closed by devos50** 2022-02-13 12:31 UTC
