### ISSUE TITLE
New Triber GUI (or core?) crashes spuriously.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2664] opened 2016-11-29 11:57 UTC
##### Tribler version/branch+revision: #####

v7.0.0-alpha1 6bda08fab632a38fbb3fc4e9f4073e23b2d8df7a

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Start Tribler core with `twistd -n tribler`
2. Start GUI with `./tribler.sh`
3. Ensure Tribler is active, i.e. connected, there are downloads or seedings, etc.
4. Wait

##### Expected behavior: #####

Nothing special happens

##### Actual behavior: #####

GUI crashes.

Note that I feel I saw this backtraces before in Core's log, but it wasn't visible in GUI (just in Core's console log).

Also note that many downloads were added in Tribler 6.5 or in various intermedite versions from devel branch.

##### Relevant log file output: #####

```
Traceback (most recent call last):
  File "/home/tribler/tribler/TriblerGUI/event_request_manager.py", line 85, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 390, in startReactor
    self.config, oldstdout, oldstderr, self.profiler, reactor)
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 311, in runReactorWithLogging
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/tribler/tribler/Tribler/community/multichain/community.py", line 410, in on_tunnel_remove
    if self._public_key > candidate.get_member().public_key:
exceptions.AttributeError: 'NoneType' object has no attribute 'public_key'
```

**Comment by vi** [comment] 2016-12-21 11:47
When this happens (with core running separately using twistd so I can observe continuation) I see my download not downloading anymore (no more per cents, speed falling down to 0 until averaging window expires) until I restart Tribler core.

**Comment by vi** [comment] 2016-12-21 11:59
I also get repeated

```
ERROR   1482321487.98 tunnel_community:752   Don't know how to encrypt outgoing message for circuit_id 2148178934
ERROR   1482321488.08 tunnel_community:752   Don't know how to encrypt outgoing message for circuit_id 2148178934
ERROR   1482321488.88 tunnel_community:752   Don't know how to encrypt outgoing message for circuit_id 2148178934
```

**Comment by devos50** [comment] 2017-01-03 09:50
Duplicate of #2655 but thanks for the report!

**Closed by devos50** 2017-01-03 09:50 UTC
Labels: duplicate
