### ISSUE TITLE
Can we have a light mode please?

### ISSUE THREAD

**Issue by dertuxmalwieder** [Tribler/tribler#6038] opened 2021-03-30 09:00 UTC
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

7.8.0

##### Operating system and version: #####

macOS 11

I deliberately removed the other headers because they’re not relevant... :-)

I know it’s unpopular, but with Tribler being the only application with a black background on my computer (MacBook with macOS 11), I wish it had an option to use a light background color as well.

**Comment by ichorid** [comment] 2021-03-30 10:16
Basically, a duplicate of #4467 . Thanks for the report, though. Recently, I started to delete duplicate CSS from our `.ui` files.

You can experiment with the CSS stuff yourself, BTW. It's all in `.ui` files :wink:

**Closed by ichorid** 2021-03-30 10:16 UTC
