### ISSUE TITLE
assert all(len(packet[1]) > 22  tripped a couple times while using Tribler to download an Ubuntu ISO

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1387] opened 2015-04-23 16:36 UTC
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/data/projects/delft/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
    f(*a, **kw)
  File "/var/data/projects/delft/tribler/Tribler/dispersy/endpoint.py", line 185, in dispersythread_data_came_in
    u"rawserver")
  File "/var/data/projects/delft/tribler/Tribler/dispersy/dispersy.py", line 1441, in on_incoming_packets
    assert all(len(packet[1]) > 22 for packet in packets), packets
exceptions.AssertionError: [(<Tribler.dispersy.candidate.Candidate object at 0x7f1ae0058fd0>, '\xff\xff\xff\xfd\x00\x04w\xa3\x00\x91')]
```

**Comment by NielsZeilemaker** [comment] 2015-05-07 09:45
Seems tftp related, as the prefix of the packet is is fffffffd. Why is this packet passed on to dispersy?

**Comment by whirm** [comment] 2015-05-07 09:46
@LipuFei ^

**Comment by NielsZeilemaker** [comment] 2015-05-07 09:48
Probably caused by sending a tftp request to a peer which does not have the newer tftp version enabled.
Why did the prefix change?

**Comment by whirm** [comment] 2015-05-07 09:52
Ah, I see, @LipuFei is implementing the retry stuff and it's backwards incompatible, he was probably testing some stuff at that time.

**Comment by NielsZeilemaker** [comment] 2015-05-07 09:54
That's ready now right? If so, lets close this issue

**Closed** 2015-05-07 10:00 UTC
Labels: bug

**Comment by LipuFei** [comment] 2015-05-07 11:49
@NielsZeilemaker @whirm Yes, I changed the prefix for the new TFTP with retries. If we merge it now, it will cause old triblers to have the same issue.
