### ISSUE TITLE
Error upon close, cleaning up databases

### ISSUE THREAD

**Issue by BmetaMax** [Tribler/tribler#1574] opened 2015-08-08 22:07 UTC
Apologies if there's already an entry for this, I don't see it.
I just upgraded to tribler 6.5RC2; note not a clean install but the upgrade installation went error free even though it took almost an hour to "ingest" everything.
I went in and enabled being an exit, (as I'm broke and not a programmer but at least I can contribute bandwidth), which caused tribler to prompt that the application needed to restart. I selected ok, and after about 30 minutes of a message which I believe said "cleaning up databases" it finally gave me an error window and closed. I manually restarted Tribler and it opened very slow and was basically unresponsive until it loaded my torrents (that is normal for me, it happened on 643 as well).
Now its loaded but of my 152 torrents, about 25% were seeding (DL complete, I have it set to unlimited seeding), and now none of them show as 100% or seeding.
I can't attach the log, I get an error the body is too long. If someone tells me what is needed I can copy it over.
Edit: I'm on Win10 x64, nothing special that I know of! Installed from Windows executable dl'd from Github for 6.5Rc2.

Edit2: I was able to duplicate by just closing the application down. The little spash screen showed "Cleaning databases" then I got the error message.

**Comment by LipuFei** [comment] 2015-08-10 09:51
Hi @BmetaMax, thank you for the report!

What does the error message say? Does it say something like "Please see ...\tribler.log"?

**Comment by BmetaMax** [comment] 2015-08-10 23:20
Yes it says see ...\Programs\Tribler\tribler.exe.log. Which I opened, but there are a ton of errors listed. So that's why I tried to paste the whole log as I mentioned before but it didn't work. Want me to email it to you or something?

**Comment by LipuFei** [comment] 2015-08-11 08:12
@BmetaMax Thanks! You can email it to me. Probably some threading issue caused the problem during the shutdown.

Another thing I would like to mention is that, this error message is produced by `py2exe`, which is the package we use to make Windows .exe application. If there is any log entry >=ERROR level, a log file will be generated, and after the application shuts down it will show this error message dialog, asking you to check the log file. So, if there is an log entry with an inappropriate level, even if there is no actual error, this dialog will still pop up after shutdown.

**Comment by BmetaMax** [comment] 2015-08-11 15:54
Lipu, thank you for your feedback. The log file is too big now (69MB!) to attach to the email normal so I've zipped it (7z, ultra, no encryption or password) and hope it makes it to you through either github or direct email.  


     On Tuesday, August 11, 2015 4:13 AM, Lipu Fei <notifications@github.com> wrote:
   

 @BmetaMax Thanks! You can email it to me. Probably some threading issue caused the problem during the shutdown.Another thing I would like to mention is that, this error message is produced by py2exe, which is the package we use to make Windows .exe application. If there is any log entry >=ERROR level, a log file will be generated, and after the application shuts down it will show this error message dialog, asking you to check the log file. So, if there is an log entry with an inappropriate level, even if there is no actual error, this dialog will still pop up after shutdown.—

**Comment by LipuFei** [comment] 2015-08-11 17:44
Hi @BmetaMax, I checked your log file. Some of the problems should already been fixed, so I am not sure what exactly happened on your machine. Perhaps, could you try to reinstall (don't keep the old stuff, if you installed it in "C:\Tribler" for example, uninstall and remove "C:\Tribler" completely before you install again) and see if you still get the same backtraces? Thanks!

**Comment by BmetaMax** [comment] 2015-08-11 20:03
Will that lose all my downloads in progress or no? If I won't lose things then I don't mind.

-------- Original message --------

**Comment by LipuFei** [comment] 2015-08-11 20:14
@BmetaMax No, you won't lose them. :) All data is saved in "$HOME\.Tribler".

**Comment by BmetaMax** [comment] 2015-08-13 18:46
Lipu, I did it; uninstalled, made sure the program directory was gone, then reinstalled. It started up much faster but after letting it run a couple hours I tried closing it and got the error again. This time I managed to get a screenshot though you probably don't need it, attached.
I'll email you the log in a minute.
![Uploading triblererror081315.png…]()

**Comment by BmetaMax** [comment] 2015-08-13 18:47
Wrong button sorry!

**Comment by BmetaMax** [comment] 2015-08-13 19:04
Hi Lipu, here's the new log. It's certainly faster than before reinstall but still getting that error on close. 


     On Tuesday, August 11, 2015 4:14 PM, Lipu Fei <notifications@github.com> wrote:
   

 @BmetaMax No, you won't lose them. :) All data is saved in "$HOME.Tribler".—

**Comment by BmetaMax** [comment] 2015-08-13 20:07
Oh also I don't know if it matters for this, but I've also been seeing that all my finished downloads which should be seeding are stuck at building circuits, including ones that were seeding before upgrading to rc2 and finished since reinstalling rc2 today.

**Comment by LipuFei** [comment] 2015-08-13 20:08
@BmetaMax I cannot see the screenshot... Could you upload it again? And could you also upload the log file if it is not big? Thanks!

**Comment by LipuFei** [comment] 2015-08-13 20:13
@BmetaMax The "building circuits" thing is not related to this. It's basically saying that it's trying to seed anonymously. Because the Tunnel is still experimental at the moment, it never finishes the "building circuits" phase.

**Comment by LipuFei** [comment] 2015-08-13 20:50
Hi @BmetaMax, I've checked the logs. There are three issues:
1. Missing wxPython version (fixed and will be in the next RC release)
2. A lib-not-found error (also fixed and will be in the next RC release)
3. A cryptography-missing-sha256 problem. This is a wired one and I cannot reproduce on my Windows machine. I will investigate this later and will let you know when it is fixed.

**Comment by BmetaMax** [comment] 2015-08-13 20:58
Trying to upload the log directly to the forum gives me this error: "Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG.", FYI.

**Comment by BmetaMax** [comment] 2015-08-13 20:59
Thanks Lipu. 


     On Thursday, August 13, 2015 4:50 PM, Lipu Fei <notifications@github.com> wrote:
   

 Hi @BmetaMax, I've checked the logs. There are three issues:
1. Missing wxPython version (fixed and will be in the next RC release)
2. A lib-not-found error (also fixed and will be in the next RC release)
3. A cryptography-missing-sha256 problem. This is a wired one and I cannot reproduce on my Windows machine. I will investigate this later and will let you know when it is fixed.—

**Comment by LipuFei** [comment] 2015-08-17 15:40
Hi @BmetaMax, I've finally fixed the cryptography problem. So, all the errors in the log files that you gave me should be gone in the next release.

**Comment by BmetaMax** [comment] 2015-08-17 22:22
Thanks @LipuFei that's great!

**Closed** 2015-08-18 13:15 UTC
Labels: bug, feedback
