### ISSUE TITLE
Install Process Stopped at "Upgrading from v22 to v23"

### ISSUE THREAD

**Issue by mattpanther** [Tribler/tribler#2539] opened 2016-09-11 14:05 UTC
#### Please, fill all relevant items:
- [ x] I have read CONTRIBUTING.md
- [ x] I have tried with the latest pre-release version and I still can reproduce the issue.
##### Tribler version/branch+revision:

6.5.2
##### Operating system and version:

Windows 10 latest version
##### Expected behavior:

For new version of Tribler to install completely.
##### Actual behavior:

Stops at "Upgrading database from v22 to v23..."

![image](https://cloud.githubusercontent.com/assets/22131722/18417776/41074830-7807-11e6-8aa9-58a432c876ac.png)
##### Steps to reproduce the behavior:

Double click the Tribler shortcut on desktop.
##### Relevant log file output:

Tribler.exe.log

ERROR   1473601563.42         upgrade:127   failed to upgrade: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "Tribler\Core\Upgrade\upgrade.pyo", line 112, in upgrade_database_to_current_version
  File "Tribler\Core\Upgrade\db_upgrader.pyo", line 62, in start_migrate
  File "Tribler\Core\Upgrade\db_upgrader.pyo", line 287, in _upgrade_22_to_23
  File "ntpath.pyo", line 65, in join
  File "ntpath.pyo", line 115, in splitdrive
TypeError: object of type 'NoneType' has no len()

**Comment by mattpanther** [comment] 2016-09-11 15:11
Followed the instructions here and deleted the sqlite directory, appears to be working now, https://github.com/Tribler/tribler/issues/2136

**Comment by lfdversluis** [comment] 2016-09-11 15:17
The issue is still valid, apparently something went wrong in the upgrade process. Deleting your databases will delete your discovered peers/channels i.e. knowledge about the network. Therefor, it would be better if we look at the root of this issue.

**Comment by devos50** [comment] 2016-09-11 16:59
I agree, we should take a look at this one and try to identify the root cause of the error. I will reopen this issue.

**Comment by mattpanther** [comment] 2016-09-11 18:31
Sounds good guys, if there's anything I can do to support with testing let me know, I still have the old sqlite folder in my recycle bin. Your commitment to quality is admirable

**Comment by lfdversluis** [comment] 2016-09-11 18:37
I think the stacktrace you have provided us with already gives us a lot of information. I am not sure if the databases will be of help, but if you could hang onto the folder containing the SQLite databases just to be safe, that would be great.

**Comment by mattpanther** [comment] 2016-09-11 18:49
Will do

**Comment by devos50** [comment] 2017-01-22 18:13
I have absolutely no idea what could be the root cause of this error. I will postpone it to 7.1 unless we receive more reports of this issue.

**Comment by synctext** [comment] 2017-01-22 21:04
if we could obtain a SQLite database to reproduce the fault.. Then we might quickly resolve this. Could be a simple tracker misspelling in Unicode.

**Comment by xoriole** [comment] 2018-03-14 15:51
Closing this issue in favor of Tribler 7. No new upgrade issue has been reported for the recent versions of Tribler.

**Closed by xoriole** 2018-03-14 15:51 UTC
Labels: bug
