### ISSUE TITLE
Ehancement - Make "Checking" torrents show up under the Active sorting option. And start with the same sorting option it was closed with.

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#1660] opened 2015-09-11 22:07 UTC
When i start up Tribler it's very easy to see what's going on by simply moving to that tab, but it can be hard to know if i have a torrent that is checking or actually stopped, since neither of those show up there. Since checking torrents are technically active, and provide a clearer picture of what's going on when you start, i think it would be a nice enhancement for Tribler. 

Another Enhancement could be letting tribler start in the sorting option it was closed with, since that way you don't have to navigate to the sorting option each time. It's useful because when you start tribler you don't want to scroll through all the completed/building circuits torrents to see how things are anyways. Could be a option in the settings to keep it on the same sorting when opening after closing it on a sorted type.

**Comment by ThomasdenH** [comment] 2015-12-04 14:26
I think #1594 is very similar and has a better solution for the filter. Saving the choice still is a good improvement.

**Comment by Thomasedv** [comment] 2015-12-04 16:13
@ThomasdenH I agree, main problem is starting up and having to check the right thing manually each time. So as long as saving between sessions is there, your idea is more versatile. Each time i start up i like to have an idea for what things that are ongoing, so i just hoped to get things that are checking on the active tab, since it'll more than likely will be. But between waiting for the building connections and the checking it takes quite the amount of time, thus the need for having it all in the same spot.

**Comment by ThomasdenH** [comment] 2015-12-04 17:12
I agree. To support people seeding, I think it is essential to be able to hide only those to prevent them from being annoying.

**Comment by ichorid** [comment] 2021-03-30 10:22
duplicate of #1261

**Closed by ichorid** 2021-03-30 10:22 UTC
Labels: component: GUI, component: UX, type: enhancement
