### ISSUE TITLE
v6.5.0-rc6: OS X El Capitan

### ISSUE THREAD

**Issue by renang010** [Tribler/tribler#1706] opened 2015-10-31 15:47 UTC
Hi,
I am using OS X El Capitan.
Opened v6.5.0-rc6.dmg, copy .app to Applications. Tried to run, but it won't start.

Renan

**Comment by Dmole** [comment] 2015-11-02 17:17
Try this build:
https://github.com/Tribler/tribler/issues/1694
if that fails open Console.app search for tribler and paste results here

**Comment by whirm** [comment] 2015-11-04 13:34
@Dmole thanks :)

**Comment by whirm** [comment] 2015-12-30 12:50
Closing due to lack of feedback, feel free to reopen it if you are still interested.

**Comment by Dmole** [comment] 2015-12-30 22:44
Tribler-6.4.3.app
```
2015-12-30 5:36:20.602 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.4.3.app/Contents/Frameworks/libwx_macud-2.8.0.dylib
2015-12-30 5:36:20.603 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.4.3.app/Contents/Frameworks/libwx_macud_stc-2.8.0.dylib
2015-12-30 5:36:20.605 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.4.3.app/Contents/Frameworks/Python.framework/Python
2015-12-30 5:36:20.605 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.4.3.app/Contents/Frameworks/Python.framework/Resources
2015-12-30 5:36:20.610 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.4.3.app/Contents/Frameworks/Python.framework/Versions/Current
2015-12-30 5:36:20.629 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.4.3.app/Contents/Resources/lib/python2.7/site.pyo
2015-12-30 5:36:27.746 PM Tribler[17951]: Traceback (most recent call last):
2015-12-30 5:36:27.747 PM Tribler[17951]:   File "<string>", line 5, in <module>
2015-12-30 5:36:27.747 PM Tribler[17951]: ImportError: No module named csv
2015-12-30 5:36:28.987 PM Tribler[17951]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.2 instead of 10.11.2. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
2015-12-30 5:36:29.059 PM Tribler[17951]: 0   CarbonCore                          0x9b710913 ___Gestalt_SystemVersion_block_invoke + 135
2015-12-30 5:36:29.059 PM Tribler[17951]: 1   libdispatch.dylib                   0x98ca8763 _dispatch_client_callout + 50
2015-12-30 5:36:29.060 PM Tribler[17951]: 2   libdispatch.dylib                   0x98ca863f dispatch_once_f + 78
2015-12-30 5:36:29.060 PM Tribler[17951]: 3   libdispatch.dylib                   0x98ca9ec9 dispatch_once + 31
2015-12-30 5:36:29.060 PM Tribler[17951]: 4   CarbonCore                          0x9b68c576 _Gestalt_SystemVersion + 1047
2015-12-30 5:36:29.060 PM Tribler[17951]: 5   CarbonCore                          0x9b68b6a5 Gestalt + 154
2015-12-30 5:36:29.060 PM Tribler[17951]: 6   libwx_macud-2.8.0.8.0.dylib         0x0528714b _Z14UMAInitToolboxtb + 43
2015-12-30 5:36:32.661 PM Tribler[17951]: GetDYLDEntryPointWithImage(/System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete,CacheDeleteCopyPurgeableSpaceWithInfo) failed.
2015-12-30 5:36:32.991 PM WindowServer[285]: disable_update_timeout: UI updates were forcibly disabled by application "Tribler" for over 1.00 seconds. Server has re-enabled them.
2015-12-30 5:36:35.333 PM WindowServer[285]: common_reenable_update: UI updates were finally reenabled by application "Tribler" after 3.34 seconds [0.30fps] (server forcibly re-enabled them after 1.00 seconds [1.00fps])
2015-12-30 5:36:43.927 PM Tribler[17951]: Traceback (most recent call last):
2015-12-30 5:36:43.928 PM Tribler[17951]:   File "Tribler/Main/tribler_main.pyo", line 1112, in run
2015-12-30 5:36:43.928 PM Tribler[17951]:   File "Tribler/Main/tribler_main.pyo", line 175, in __init__
2015-12-30 5:36:43.928 PM Tribler[17951]:   File "Tribler/Main/tribler_main.pyo", line 393, in InitStage1
2015-12-30 5:36:43.928 PM Tribler[17951]:   File "Tribler/Core/DownloadConfig.pyo", line 200, in save
2015-12-30 5:36:43.928 PM Tribler[17951]:   File "Tribler/Core/Utilities/configparser.pyo", line 56, in write_file
2015-12-30 5:36:43.928 PM Tribler[17951]:   File "codecs.pyo", line 878, in open
2015-12-30 5:36:43.928 PM Tribler[17951]: IOError: [Errno 2] No such file or directory: u'/Users/Dmole/.Tribler/tribler.conf'
```

Tribler-6.5.0-rc6.app
```
2015-12-30 5:37:42.024 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Frameworks/libwx_macud-2.8.0.dylib
2015-12-30 5:37:42.025 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Frameworks/libwx_macud_stc-2.8.0.dylib
2015-12-30 5:37:42.025 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Frameworks/Python.framework/Python
2015-12-30 5:37:42.026 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Frameworks/Python.framework/Resources
2015-12-30 5:37:42.033 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Frameworks/Python.framework/Versions/Current
2015-12-30 5:37:42.052 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Resources/lib/python2.7/site.pyo
2015-12-30 5:37:45.125 PM Tribler[17957]: Unable to load logging config from ''/Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Resources/lib/python2.7/site-packages.zip/logger.conf'' file: No section: 'formatters'
2015-12-30 5:37:45.126 PM Tribler[17957]: Current working directory: u'/Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Resources'
2015-12-30 5:37:45.126 PM Tribler[17957]: File doesn't exist
2015-12-30 5:37:49.701 PM Tribler[17957]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.2 instead of 10.11.2. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
2015-12-30 5:37:49.701 PM Tribler[17957]: 0   CarbonCore                          0x9b710913 ___Gestalt_SystemVersion_block_invoke + 135
2015-12-30 5:37:49.702 PM Tribler[17957]: 1   libdispatch.dylib                   0x98ca8763 _dispatch_client_callout + 50
2015-12-30 5:37:49.702 PM Tribler[17957]: 2   libdispatch.dylib                   0x98ca863f dispatch_once_f + 78
2015-12-30 5:37:49.702 PM Tribler[17957]: 3   libdispatch.dylib                   0x98ca9ec9 dispatch_once + 31
2015-12-30 5:37:49.702 PM Tribler[17957]: 4   CarbonCore                          0x9b68c576 _Gestalt_SystemVersion + 1047
2015-12-30 5:37:49.702 PM Tribler[17957]: 5   CarbonCore                          0x9b68b6a5 Gestalt + 154
2015-12-30 5:37:49.702 PM Tribler[17957]: 6   libwx_macud-2.8.0.8.0.dylib         0x0528614b _Z14UMAInitToolboxtb + 43
2015-12-30 5:37:49.842 PM Tribler[17957]: 2015-12-30 17:37:49,841 [ERROR] (u'Default image is not a file %s', u'/Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Resources/lib/python2.7/site-packages.zip/Tribler/Main/vwxGUI/images/default/defaultThumbPeer.png')
2015-12-30 5:37:49.842 PM Tribler[17957]: Traceback (most recent call last):
2015-12-30 5:37:49.842 PM Tribler[17957]:   File "Tribler/Main/tribler_main.pyo", line 1061, in run
2015-12-30 5:37:49.842 PM Tribler[17957]:   File "Tribler/Main/tribler_main.pyo", line 143, in __init__
2015-12-30 5:37:49.842 PM Tribler[17957]:   File "Tribler/Main/tribler_main.pyo", line 315, in InitStage1
2015-12-30 5:37:49.842 PM Tribler[17957]:   File "Tribler/Main/vwxGUI/GuiImageManager.pyo", line 51, in getInstance
2015-12-30 5:37:49.842 PM Tribler[17957]:   File "Tribler/Main/vwxGUI/GuiImageManager.pyo", line 44, in __init__
2015-12-30 5:37:49.842 PM Tribler[17957]:   File "Tribler/Main/vwxGUI/__init__.pyo", line 119, in invoke_func
2015-12-30 5:37:49.843 PM Tribler[17957]:   File "Tribler/Main/vwxGUI/GuiImageManager.pyo", line 69, in _load_all_images
2015-12-30 5:37:49.843 PM Tribler[17957]:   File "Tribler/Main/vwxGUI/GuiImageManager.pyo", line 104, in _init_default_images
2015-12-30 5:37:49.843 PM Tribler[17957]: Exception: (u'Default image is not a file %s', u'/Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc6.app/Contents/Resources/lib/python2.7/site-packages.zip/Tribler/Main/vwxGUI/images/default/defaultThumbPeer.png')
```

Tribler-6.5.0-rc5.app
```
2015-12-30 5:38:40.718 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc5.app/Contents/Frameworks/libwx_macud-2.8.0.dylib
2015-12-30 5:38:40.718 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc5.app/Contents/Frameworks/libwx_macud_stc-2.8.0.dylib
2015-12-30 5:38:40.719 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc5.app/Contents/Frameworks/Python.framework/Python
2015-12-30 5:38:40.719 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc5.app/Contents/Frameworks/Python.framework/Resources
2015-12-30 5:38:40.726 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc5.app/Contents/Frameworks/Python.framework/Versions/Current
2015-12-30 5:38:40.742 PM CoreServicesUIAgent[17073]: error -1 while removing quarantine data on path /Users/Dmole/Downloads/TriblerDownloads/Tribler-6.5.0-rc5.app/Contents/Resources/lib/python2.7/site.pyo
2015-12-30 5:38:48.199 PM Tribler[17960]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.2 instead of 10.11.2. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
2015-12-30 5:38:48.200 PM Tribler[17960]: 0   CarbonCore                          0x9b710913 ___Gestalt_SystemVersion_block_invoke + 135
2015-12-30 5:38:48.200 PM Tribler[17960]: 1   libdispatch.dylib                   0x98ca8763 _dispatch_client_callout + 50
2015-12-30 5:38:48.200 PM Tribler[17960]: 2   libdispatch.dylib                   0x98ca863f dispatch_once_f + 78
2015-12-30 5:38:48.200 PM Tribler[17960]: 3   libdispatch.dylib                   0x98ca9ec9 dispatch_once + 31
2015-12-30 5:38:48.200 PM Tribler[17960]: 4   CarbonCore                          0x9b68c576 _Gestalt_SystemVersion + 1047
2015-12-30 5:38:48.200 PM Tribler[17960]: 5   CarbonCore                          0x9b68b6a5 Gestalt + 154
2015-12-30 5:38:48.200 PM Tribler[17960]: 6   libwx_macud-2.8.0.8.0.dylib         0x0528614b _Z14UMAInitToolboxtb + 43
2015-12-30 5:38:49.361 PM Tribler[17960]: ERROR   1451515129.36     mainlineDHT:21    Could not import pymdht
2015-12-30 5:38:49.361 PM Tribler[17960]: Traceback (most recent call last):
2015-12-30 5:38:49.361 PM Tribler[17960]:   File "Tribler/Core/DecentralizedTracking/mainlineDHT.pyo", line 16, in <module>
2015-12-30 5:38:49.361 PM Tribler[17960]:   File "Tribler/Core/DecentralizedTracking/pymdht/plugins/routing_nice_rtt.pyo", line 37, in <module>
2015-12-30 5:38:49.361 PM Tribler[17960]: ImportError: No module named routing_table
2015-12-30 5:38:50.739 PM Tribler[17960]: Traceback (most recent call last):
2015-12-30 5:38:50.740 PM Tribler[17960]:   File "wx/_core.pyo", line 14669, in <lambda>
2015-12-30 5:38:50.740 PM Tribler[17960]:   File "Tribler/Main/vwxGUI/list.pyo", line 2184, in __SetData
2015-12-30 5:38:50.740 PM Tribler[17960]:   File "Tribler/Main/vwxGUI/list.pyo", line 2219, in DisableItem
2015-12-30 5:38:50.740 PM Tribler[17960]: KeyError: 5
```

**Comment by whirm** [comment] 2015-12-31 10:26
@Dmole thanks!

@devos50 I guess that's your gig.

**Comment by devos50** [comment] 2016-01-08 11:07
@whirm @Dmole I just created a fresh .dmg file. I'm sure that we've already fixed the error that you get in `6.5.0-rc5`. Regarding the error in `6.5.0-rc6`: I also get it when I open `Tribler.app` but the error seems to be gone in the latest `.dmg` and I can open and use Tribler without problems.

**Comment by Dmole** [comment] 2016-01-08 17:09
Yes, this has been fixed in the source before, and yes the build you liked works to, but that's not a fix; the website was never updated so new users could never find a working version.

I understand why we never heard for renang010 again; Any brand/site that serves a broken product directly from the main page for an entire year (well a full year 20 days from now) is really not worth most peoples time. 

Please update http://www.tribler.org

**Comment by Dmole** [comment] 2016-01-08 17:21
Why did you link an rc5 instead of an rc6 build? (we already know rc5 works)
There are 60 commits and 2 month between them.

**Comment by whirm** [comment] 2016-01-11 10:05
@Dmole tribler.org links to the latest stable release (6.4.3) which doesn't work with newer OSX releases. 6.5 will, it just hasn't been released yet. 

We are understaffed so things don't go as fast as they should.

**Comment by whirm** [comment] 2016-01-11 10:08
@devos50 BTW you are linking to a `devel` build, don't advise people to use these builds as they are usually broken and this is not the code we will be delivering on 6.5 either. 

Be careful with that and make sure you reproduce the bugs with builds from the `next` branch or things will get pretty confusing for everyone.

**Comment by devos50** [comment] 2016-01-11 10:15
@whirm thanks for the comment, didn't notice I created a `devel`build. I will test again with a `next` build and report whether there are any errors.

**Comment by devos50** [comment] 2016-01-11 13:35
@Dmole I've created a new build: https://jenkins.tribler.org/job/Build-Tribler_OSX_next/174/artifact/tribler/dist/Tribler-6.5.0-rc6-90-g2420d9c.dmg. Could you please run this one and see whether the issues you encountered are still present?

**Comment by devos50** [comment] 2016-03-20 19:22
@whirm I guess this one is finished?

**Comment by Dmole** [comment] 2016-03-20 23:38
Seems to be.

**Closed** 2016-03-29 15:41 UTC
Labels: bug
