### ISSUE TITLE
Feature request: display current bandwidth in the new GUI

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2843] opened 2017-03-04 22:53 UTC
##### Tribler version/branch+revision: #####

devel

##### Expected behavior: #####

If Tribler consumes considerable network traffic then I can see some number why is it so (anonymity contribution, seeding, downloading, keeping up distributed database).

Obviously the resulting, total Tribler-related bandwidth should be limitable, but that's another issue.

##### Actual behavior: #####

1 megabyte per second consumed by Tribler and stats in GUI. I see only download and upload bandwidth, but they are low.

**Comment by synctext** [comment] 2018-03-29 13:19
Thnx @vi for reporting this. We're now also relaying encrypted traffic (not exit node stuff) for other Tribler users sometimes. This should be visible for users. Not at the main screen perhaps, but at least in the debug panel or one-click away somewhere. Possible the "credit screen" showing "ongoing help".

**Comment by ichorid** [comment] 2020-06-12 08:52
duplicate of #2187

**Closed by ichorid** 2020-06-12 08:52 UTC
Labels: enhancement
