### ISSUE TITLE
Gaierror Episode 5: Sentry Edition

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4880] opened 2019-10-02 14:33 UTC
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\site-packages\twisted\python\log.py", line 101, in callWithLogger

File "lib\site-packages\twisted\python\log.py", line 84, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 118, in callWithContext

File "lib\site-packages\twisted\python\context.py", line 81, in callWithContext

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite

File "lib\site-packages\twisted\internet\udp.py", line 227, in doRead

socket.gaierror: [Errno 10022] getaddrinfo failed
```
Report [27434](http://reporter.tribler.org/stacktrace/27434)
Difficult to reproduce.

**Comment by xoriole** [comment] 2019-11-27 14:07
Fixed by https://github.com/Tribler/tribler/pull/4971

**Comment by ichorid** [comment] 2020-07-17 11:05
[7.5.1] 
```
[PID:3236] 2020-07-17 12:43:30,424 - ERROR <taskmanager:135> UdpTrackerSession.done_cb(): Task resulted in error: [Errno 11004] getaddrinfo failed

Traceback (most recent call last):

  File "ipv8\taskmanager.py", line 131, in done_cb

  File "lib\asyncio\base_events.py", line 825, in getaddrinfo

  File "lib\concurrent\futures\thread.py", line 57, in run

  File "lib\socket.py", line 918, in getaddrinfo

socket.gaierror: [Errno 11004] getaddrinfo failed
```

**Comment by egbertbouman** [comment] 2020-07-17 11:12
@ichorid In this case, it looks like a logged exception (triggered by https://github.com/Tribler/py-ipv8/blob/master/ipv8/taskmanager.py#L135).

**Comment by qstokkink** [comment] 2020-07-17 11:22
Shouldn't this already be caught though?

https://github.com/Tribler/tribler/blob/c98871b033ac9e1ccc9cecd242734e8b9bf3e1d0/src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py#L321-L322

So it needn't be in the ignore here:

https://github.com/Tribler/tribler/blob/c98871b033ac9e1ccc9cecd242734e8b9bf3e1d0/src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py#L314-L315

**Comment by egbertbouman** [comment] 2020-07-17 12:09
@qstokkink If the `unhandled_error_observer` ensures we don't crash it doesn't need to be in the ignore, otherwise it does. Basically, the ignore is used to prevent tasks from calling `unhandled_error_observer`.

In this case, assuming that `unhandled_error_observer` doesn't crash on this error, *not* ignoring the exception will prevent it from being logged by the `TaskManager`.

BTW, even though we're catching the error when we await the task, that doesn't mean that the same error won't also end up in `done_cb`.

**Comment by qstokkink** [comment] 2020-07-17 12:36
@egbertbouman For my understanding: so the task is leaving this `try ... except` scope and crashing elsewhere (`done_cb`) causing it to be picked up by the `unhandled_error_observer`?

Assuming I understood correctly, I think our current behavior (logging the traceback) is indeed the only thing we can do. We could lower the log level to `INFO` though if the error is already specified as `ignore`.

**Comment by egbertbouman** [comment] 2020-07-17 14:10
> For my understanding: so the task is leaving this `try ... except` scope and crashing elsewhere (`done_cb`) causing it to be picked up by the `unhandled_error_observer` if not ignored?

@qstokkink Correct, although it's not really crashing in `done_cb`, it's just logging the exception. Because this is part of normal operations, the original log statement in `TaskManager` was less verbose then it is now.

> We could lower the log level to `INFO` though if the error is already specified as `ignore`.

The logging statement in the `TaskManager` well never even get executed if the exception that is thrown is not in the `ignore` tuple.

**Comment by qstokkink** [comment] 2020-07-17 14:16
@egbertbouman thanks, clear.

I guess we can close this issue then. I suppose we could open an issue on IPv8 to support different types of logging or log levels if this becomes too annoying in the log.

**Comment by egbertbouman** [comment] 2020-07-18 14:21
I just took a closer look at this, and it seems that this error is currently logged 2 times (in [`TorrentChecker`](https://github.com/Tribler/tribler/blob/release-7.5/src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py#L147) and in [`TaskManager`](https://github.com/Tribler/py-ipv8/blob/master/ipv8/taskmanager.py#L135)).

Given the fact that this particular `giaerror` is indeed ignored by the `unhandled_error_observer` (see [`Session`](https://github.com/Tribler/tribler/blob/release-7.5/src/tribler-core/tribler_core/session.py#L83)), perhaps it's best to remove the ignore. This will avoid printing the entire stack, although it would still be logged for a 2nd time in the `unhandled_error_observer`.

**Comment by devos50** [comment] 2020-07-19 18:16
Back again (on Ubuntu 20.04, caught by the application testers):

```
ERROR:Executor:********** TRIBLER CRASHED **********
ERROR:Executor:Tribler crashed after uptime of 1784.4479985237122 sec! Stack trace: Traceback (most recent call last):
  File "src/tribler-gui/tribler_gui/event_request_manager.py", line 116, in on_read_data
RuntimeError: [Errno -5] No address associated with hostname
--LONG TEXT--
Traceback (most recent call last):
  File "asyncio/events.py", line 81, in _run
  File "ipv8/taskmanager.py", line 131, in done_cb
  File "asyncio/base_events.py", line 825, in getaddrinfo
  File "concurrent/futures/thread.py", line 57, in run
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno -5] No address associated with hostname

--CONTEXT--
{'message': "Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...th hostname')>) at ipv8/taskmanager.py:128", 'exception': gaierror(-5, 'No address associated with hostname'), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...th hostname')>) at ipv8/taskmanager.py:128>}
```

**Comment by egbertbouman** [comment] 2020-07-19 19:58
Yeah, that's the risk: all `gaierror` codes need to be in the list in [`Session`](https://github.com/Tribler/tribler/blob/release-7.5/src/tribler-core/tribler_core/session.py#L83).

**Comment by ichorid** [comment] 2020-08-14 13:41
7.5.2 

```python

Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\core_manager.py", line 64, in on_core_finished
RuntimeError: The Tribler core has unexpectedly finished with exit code -1073741819 and status: 1!

[PID:10492] 2020-08-12 23:10:19,027 - ERROR <taskmanager:135> TunnelExitSocket.done_cb(): Task resulted in error: [Errno 11001] getaddrinfo failed
Traceback (most recent call last):
File "ipv8\taskmanager.py", line 131, in done_cb
File "ipv8\messaging\anonymization\tunnel.py", line 174, in resolve
File "lib\asyncio\base_events.py", line 825, in getaddrinfo
File "lib\concurrent\futures\thread.py", line 57, in run
File "lib\socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by qstokkink** [comment] 2020-08-14 13:55
🤔 The `[PID:10492] 2020-08-12 23:10:19,027 - ERROR <taskmanager:135> TunnelExitSocket.done_cb(): Task resulted in error: [Errno 11001] getaddrinfo failed` should just be a logging statement.

**Comment by qstokkink** [comment] 2020-08-14 14:02
@ichorid is that latest traceback from a Windows machine?

**Comment by ichorid** [comment] 2020-08-14 14:27
@qstokkink yes, `platform.details Windows-10-10.0.18362-SP0`

**Comment by qstokkink** [comment] 2020-08-14 14:48
From what I read, Windows randomly pops the `-1073741819` exit code (`0xC0000005` Access violation) with PyQt5. It seems nobody knows exactly what causes that.

**Comment by devos50** [comment] 2020-08-14 15:17
Hmm... That could actually explain it. The GUI is checking the standard output of the subprocess for the word 'Traceback', and stores it. As soon as the access violation error happens, it will log the latest error, even if that traceback would not have caused to a hard crash of Tribler. To capture these situations, we could log the timestamp of both the traceback and the crash itself.

**Comment by ichorid** [comment] 2020-12-02 12:02
[Sentry log for 7.6.0-exp1 depoyment tester](https://jenkins-ci.tribler.org/job/Deployment-Tests/job/Run_Tribler_Release/job/Run_Win10_64bit/1063/console):

```python 
PID:4176] 2020-12-02 11:51:49,773 - INFO - SentryReporter(212) - Capture exception: [Errno 11001] getaddrinfo failed
[PID:4176] 2020-12-02 11:51:49,785 - INFO - SentryReporter(264) - Before send event: {'level': 'error', 'exception': {'values': [{'module': 'socket', 'type': 'gaierror', 'value': '[Errno 11001] getaddrinfo failed', 'mechanism': {'type': 'generic', 'meta': {'errno': {'number': 11001}}}, 'stacktrace': {'frames': [{'filename': 'lib\\asyncio\\events.py', 'abs_path': 'C:\\jenkins
...

[PID:4176] 2020-12-02 11:51:49,786 - INFO - SentryReporter(265) - Strategy: Strategy.SEND_SUPPRESSED
[PID:4176] 2020-12-02 11:51:49,786 - ERROR <session:237> Session.unhandled_error_observer(): Unable to perform DNS lookup.
```

We're gonna be **spammed** by `gaierror`s if this stuff is sent to us silently.

**Comment by qstokkink** [comment] 2021-08-30 12:46
### Reproducing the wrong error being reported

1. Apply this patch:

```patch
diff --git a/src/tribler-core/tribler_core/components/implementation/ipv8.py b/src/tribler-core/tribler_core/components/implementation/ipv8.py
index 223149d4a..c8bfd69fb 100644
--- a/src/tribler-core/tribler_core/components/implementation/ipv8.py
+++ b/src/tribler-core/tribler_core/components/implementation/ipv8.py
@@ -102,6 +102,12 @@ class Ipv8ComponentImp(Ipv8Component):
                 if path in endpoints_to_init:
                     endpoint.initialize(ipv8)
 
+        self.task_manager.register_anonymous_task("raise gaierror", self.raise_gaierror, ignore=(OSError,))
+
+    async def raise_gaierror(self):
+        import socket
+        raise socket.gaierror(0, "test")
+
     def make_bootstrapper(self) -> DispersyBootstrapper:
         args = DISPERSY_BOOTSTRAPPER['init']
         if bootstrap_override := self.session.config.ipv8.bootstrap_override:
```

2. Send a SIGINT to the core process.

### Result

Our test error gets reported:

<details> <summary> log output </summary>

```python
[PID:4851] 2021-08-30 14:42:06,573 - ERROR <error_handler:37> ErrorHandler.gui_error(): tribler_gui.utilities.CreationTraceback: 
  File "/home/quinten/Documents/tribler/src/run_tribler.py", line 131, in <module>
    sys.exit(app.exec_())
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 97, in on_request_error
    self.start_tribler_core(core_args=core_args, core_env=core_env)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 177, in start_tribler_core
    connect(self.core_process.finished, self.on_core_finished)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 398, in trackback_wrapper
    raise exc from CreationTraceback(traceback_str)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/utilities.py", line 395, in trackback_wrapper
    callback(*args, **kwargs)
  File "/home/quinten/Documents/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 87, in on_core_finished
    raise RuntimeError(exception_msg)
RuntimeError: The Tribler core has unexpectedly finished with exit code 9 and status: 1!

/home/quinten/.local/lib/python3.8/site-packages/apispec/ext/marshmallow/common.py:139: UserWarning: Multiple schemas resolved to the name GetChannelContentsResponse. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
  warnings.warn(
/home/quinten/.local/lib/python3.8/site-packages/apispec/ext/marshmallow/common.py:139: UserWarning: Multiple schemas resolved to the name SpeedTestRequest. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
  warnings.warn(
[PID:4878] 2021-08-30 14:42:02,773 - ERROR <taskmanager:135> TaskManager.done_cb(): Task resulted in error: [Errno 0] test
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/ipv8.py", line 109, in raise_gaierror
    raise socket.gaierror(0, "test")
socket.gaierror: [Errno 0] test


(Timestamp: 1630327326573, traceback timestamp: 1630327322774)

[PID:4851] 2021-08-30 14:42:06,576 - INFO - SentryReporter(286) - Event from exception: The Tribler core has unexpectedly finished with exit code 9 and status: 1!

/home/quinten/.local/lib/python3.8/site-packages/apispec/ext/marshmallow/common.py:139: UserWarning: Multiple schemas resolved to the name GetChannelContentsResponse. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
  warnings.warn(
/home/quinten/.local/lib/python3.8/site-packages/apispec/ext/marshmallow/common.py:139: UserWarning: Multiple schemas resolved to the name SpeedTestRequest. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
  warnings.warn(
[PID:4878] 2021-08-30 14:42:02,773 - ERROR <taskmanager:135> TaskManager.done_cb(): Task resulted in error: [Errno 0] test
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/implementation/ipv8.py", line 109, in raise_gaierror
    raise socket.gaierror(0, "test")
socket.gaierror: [Errno 0] test


(Timestamp: 1630327326573, traceback timestamp: 1630327322774)
```

</details>

**Comment by drew2a** [comment] 2021-11-17 12:41
@qstokkink I can't apply the patch you described because the codebase has been changed.

I tried to reproduce the error by adding:
```python
        async def raise_gaierror():
            import socket
            raise socket.gaierror(0, "test")
        community.register_anonymous_task("raise gaierror", raise_gaierror, ignore=(OSError,), delay=2)
```

to the end of the function:

https://github.com/Tribler/tribler/blob/c0d5eadd8284325dc90e424dcd835864b52d12d1/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py#L121-L127

What I see is the error has been printed in the logs:
```
[PID:62896] 2021-11-17 13:38:15,987 - ERROR <taskmanager:135> DiscoveryCommunity.done_cb(): Task resulted in error: [Errno 0] test
Traceback (most recent call last):
  File "/Users/drew2a/Projects/github.com/Tribler/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/Users/drew2a/Projects/github.com/Tribler/tribler/src/pyipv8/ipv8/taskmanager.py", line 24, in delay_runner
    await task(*args)
  File "/Users/drew2a/Projects/github.com/Tribler/tribler/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py", line 131, in raise_gaierror
    raise socket.gaierror(0, "test")
socket.gaierror: [Errno 0] test
```

But it has not been reported.

So it seems like correct behavior.

**Comment by drew2a** [comment] 2021-11-17 12:46
@ichorid we never send anything silently from a user machine

>We're gonna be spammed by gaierrors if this stuff is sent to us silently.

**Comment by qstokkink** [comment] 2021-11-17 13:53
@drew2a I can still reproduce it with your code:

```
(Timestamp: 1637156853205, traceback timestamp: 1637156816248)

[PID:3925] 2021-11-17 14:47:33,205 - INFO - SentryReporter(287) - Event from exception: The Tribler core has unexpectedly finished with exit code 9 and status: 1!

/home/quinten/.local/lib/python3.8/site-packages/apispec/ext/marshmallow/common.py:139: UserWarning: Multiple schemas resolved to the name SpeedTestRequest. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.
  warnings.warn(
[PID:3962] 2021-11-17 14:46:56,248 - ERROR <taskmanager:135> DiscoveryCommunity.done_cb(): Task resulted in error: [Errno 0] test
Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/home/quinten/Documents/tribler/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py", line 131, in raise_gaierror
    raise socket.gaierror(0, "test")
socket.gaierror: [Errno 0] test
```

Did you perhaps not send a SIGKILL signal (or SIGINT) to the core process?

By the way: I did click "send report" on the crash reporter, but I can't find it in Sentry.

**Comment by drew2a** [comment] 2021-11-17 15:14
> Did you perhaps not send a SIGKILL signal (or SIGINT) to the core process?

Yes you are right, because in this case an error report (in my opinion) is expected. Am I wrong?

> By the way: I did click "send report" on the crash reporter, but I can't find it in Sentry.

Probably you did not specify sentry url here: https://github.com/Tribler/tribler/blob/c0d5eadd8284325dc90e424dcd835864b52d12d1/src/tribler-core/tribler_core/version.py#L4

If so, you can use the following URL 
```python
sentry_url = "https://f377352370b44a5487c0ab5f2feec5f7@sentry.tribler.org/3"
```

and see error reports here: https://sentry.tribler.org/organizations/tribler/issues/?project=3

**Comment by qstokkink** [comment] 2021-11-17 15:38
Sure, an error is expected. However, I would expect that the SIGKILL or SIGINT would be reported and not an unrelated error that happened before and did not cause Tribler to crash (the "test"). Perhaps this diff is even better to showcase the problem:

```patch
diff --git a/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py b/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py
index f8018fe85..c720d6e25 100644
--- a/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py
+++ b/src/tribler-core/tribler_core/components/ipv8/ipv8_component.py
@@ -126,6 +126,8 @@ class Ipv8Component(RestfulComponent):
         ipv8.add_strategy(community, PeriodicSimilarity(community), INFINITE)
         self._peer_discovery_community = community
 
+        print("Traceback is definitely not happening here. This is just a print statement.")
+
     def _init_dht_discovery_community(self):
         ipv8 = self.ipv8
         community = DHTDiscoveryCommunity(self.peer, ipv8.endpoint, ipv8.network, max_peers=60)
```

Sending a SIGKILL to your core process leads to this error report: https://sentry.tribler.org/organizations/tribler/issues/879/?project=3&query=is%3Aunresolved

**Comment by drew2a** [comment] 2021-11-19 11:00
Thanks, I've managed to reproduce it locally. 

The issue seems not to be related to `gaierror`, so I've created the new issue: https://github.com/Tribler/tribler/issues/6566

**Closed by drew2a** 2021-11-19 11:00 UTC
Labels: type: bug
