### ISSUE TITLE
6.52 crashed after launch

### ISSUE THREAD

**Issue by kucengemok** [Tribler/tribler#2299] opened 2016-06-15 16:19 UTC
tribler.conf
-[Tribler]
version_info = {'first_run': 1466006762, 'version_id': '6.5.2'}

[downloadconfig]
version = 15
saveas = C:\Users\admin\Downloads\TriblerDownloads
max_upload_rate = 0
max_download_rate = 0
mode = 0
hops = 0
selected_files = []
correctedfilename = None
safe_seeding = True
seeding_mode = ratio
seeding_ratio = 2.0
seeding_time = 60

windows vista.

**Comment by kucengemok** [comment] 2016-06-15 16:20
Tribler.exe.log
-Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 152, in register
  File "Tribler\dispersy\dispersy.pyo", line 49, in <module>
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

**Comment by whirm** [comment] 2016-06-16 13:31
@kucengemok apparently there was an issue loading netifaces.

@lfdversluis could you take care of guiding him through the dependency walker stuff to see what's missing?

**Comment by lfdversluis** [comment] 2016-06-16 14:26
Sure!

Hi @kucengemok to see why netifaces could not be loaded, could you please do the following steps?

1. Download [Dependency walker](http://www.dependencywalker.com/). (it's only ~500kb)
2. Open dependency walker and open/load `netifaces.pyd` in the program. `netifaces.pyd` can be found in `C:\Program Files (x86)\Tribler`, the default installation location (or where you've installed Tribler).
3. Now you should see something like [this screen](https://gyazo.com/c2699ee2a1e7430b22475a161c5b62cf).
4. Make sure everything in the top left window is collapsed except for the `netifaces.pyd`, like [this](https://gyazo.com/26cb1e09178715e1dfb2e3b2ac0666c9) - **What does this show for you?**
5. In the bottom screen click on "module" to sort them by name. Scroll down a bit until you reach the "MSVC" section, you should get something like [this](https://gyazo.com/2c65b1724d9f21ccc0dbcfe37cfd1085) - **What do you see here?**

If you can provide us with screenshots for example of your output then it would help us a lot in seeing if it can find the dependencies required on your machine. We have had issues with the MSVC libraries in the past, so I am interested if that's the case here.

**Comment by kucengemok** [comment] 2016-06-16 21:33
http://postimg.org/gallery/ijm9wse0 please check...

https://s31.postimg.org/oyw1w0i3v/How_2.jpg
https://s31.postimg.org/7mvpakomj/How.jpg

**Comment by lfdversluis** [comment] 2016-06-17 08:51
@kucengemok It looks like MSVCR90.dll cannot be found. I have checked out builder and this file was missing indeed. I will build a new version which should include this, or additionally you can install MSVCR90 from here: https://www.microsoft.com/en-us/download/details.aspx?id=29 and then run tribler.

Thanks for posting this.

**Comment by lfdversluis** [comment] 2016-06-17 08:58
@whirm Apparently the builder is offline, it's this one right? https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_next/

**Comment by kucengemok** [comment] 2016-06-17 12:29
installed..but it load..then nothing appeared...but can see it in process explorer...

**Comment by lfdversluis** [comment] 2016-06-17 12:30
@kucengemok Any crash log this time?

**Comment by kucengemok** [comment] 2016-06-17 12:36
https://s32.postimg.org/enb260zhh/Tribler_2.jpg

same thing...

"Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 152, in register
  File "Tribler\dispersy\dispersy.pyo", line 49, in <module>
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed."

**Comment by lfdversluis** [comment] 2016-06-17 12:38
@kucengemok ok, could you repeat the dependency walker step again? We should see that it can find MSVCR90 now. Make sure to click on the "module" header at the bottom page in step 5 to sort them by name.

**Comment by kucengemok** [comment] 2016-06-17 12:42
https://s31.postimg.org/bs9tnyk2j/Tribler_3.jpg

**Comment by lfdversluis** [comment] 2016-06-17 12:48
Hmmm unfortuntately no output in that screen. Can you open `netifaces.pyd` again in Dependency Walker and repeat the steps in https://github.com/Tribler/tribler/issues/2299#issuecomment-226501402 ?

**Comment by kucengemok** [comment] 2016-06-17 12:52
https://s31.postimg.org/i3p6m7fln/tribler_5.jpg

**Comment by lfdversluis** [comment] 2016-06-17 12:55
@kucengemok ok so MSVCR90.dll can be found now.

So this means there is another error. Could you load `tribler.exe` into Dependency walker this time? And show me the overview?

Thanks for helping bug  hunting by the way 👍

**Comment by kucengemok** [comment] 2016-06-17 13:02
https://s31.postimg.org/3s04d3xmj/tribler_7.jpg

**Comment by lfdversluis** [comment] 2016-06-17 13:10
@kucengemok This looks good, all dlls can be found that are needed by tribler. Is there a `tribler.exe.log` in `C:\Program Files (x86)\Tribler` ? If so, could you paste it here?

**Comment by kucengemok** [comment] 2016-06-17 13:12
none

**Comment by lfdversluis** [comment] 2016-06-17 13:15
Are there any logs in `%APPDATA%` by any chance?

**Comment by kucengemok** [comment] 2016-06-17 13:20
C:\Users\admin\AppData\Roaming

as usual..
"Traceback (most recent call last):
  File "Tribler\Main\tribler_main.pyo", line 183, in __init__
  File "Tribler\Core\Session.pyo", line 419, in start
  File "Tribler\Core\APIImplementation\LaunchManyCore.pyo", line 152, in register
  File "Tribler\dispersy\dispersy.pyo", line 49, in <module>
**ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed."**

The Tribler.exe is able to load BUT it stays at the system only..cannot see the GUI.

**Comment by lfdversluis** [comment] 2016-06-17 13:31
@kucengemok are you running windows vista? If so, we will try to run Tribler on this windows version and check if we can reproduce the issue.

**Comment by kucengemok** [comment] 2016-06-17 13:38
yup..vista business with kapersky AV,bitdefender anti-ransomware

**Comment by kucengemok** [comment] 2016-06-17 13:39
what to do..this is my office's computer..for my own use,im using win 8.1...

**Comment by lfdversluis** [comment] 2016-06-17 13:51
@kucengemok So you are running WIndows Vista and Windows 8.1. and on neither windows version Tribler works?

**Comment by kucengemok** [comment] 2016-06-17 13:57
on my office's computer - Vista...my own computer armed with 8.1..vista runs okay...

**Comment by lfdversluis** [comment] 2016-06-17 14:00
Oh so the issue is on WIndows 8.1? Ok that is good to know.

**Comment by kucengemok** [comment] 2016-06-17 14:01
at vista OS..that's the problem.

**Comment by kucengemok** [comment] 2016-06-17 14:02
the error came from the system with vista....so maybe tribler is not well optimized for vista,right?

**Comment by kucengemok** [comment] 2016-06-17 14:03
Let me clear it..

Tribler on Vista = failed to work. - Now the problem occurred right now came from the computer armed with Vista OS.

Tribler on Windows 8.1 = Okay.

**Comment by lfdversluis** [comment] 2016-06-17 14:05
Ahhh ok. We do not have automatic tests on vista, so it may be that there is indeed an issue with it. We will install a machine in vista and try to reproduce your error. I will keep you updated 👍

**Comment by kucengemok** [comment] 2016-06-17 14:27
@lfdversluis Please install these too as who knows these might be the culprit?

kapersky AV,bitdefender anti-ransomware

**Comment by lfdversluis** [comment] 2016-06-18 12:45
@kucengemok You are right, we once noticed anti virus software can block items of tribler.

@devos50 Can you test Tribler on windows vista? Preferably with the programs above?

**Comment by devos50** [comment] 2017-01-12 13:59
@kucengemok could you please try the latest alpha version of Tribler 7? Please see https://jenkins.tribler.org/job/Build_Tribler_devel/192/

**Comment by devos50** [comment] 2017-01-20 17:53
I've setup a machine running Vista and I've tested Tribler 7 on it. Seems to work ok, including the video player, searching and downloading, both plain and anonymous. Since I can't reproduce it, I will close this issue. Feel free to reopen when you or someone else encounters the bug again.

**Closed by devos50** 2017-01-20 17:53 UTC
Labels: bug
