### ISSUE TITLE
Ratio clearing when switching on/off anonymous.

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3779] opened 2018-08-11 10:36 UTC
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
August 6th 2018 version
##### Tribler version/branch+revision: ####
7.1
##### Operating system and version: #####
WIndows 10 Insider 17735
##### Steps to reproduce the behavior: #####
A torrent with a ratio > 0 make/unmake it Anonymous
##### Expected behavior: #####
Ratio to stay what is was and to increase when seeding with or without Anonymous on/off
##### Actual behavior: #####
Ratio is reset to 0

**Comment by devos50** [comment] 2018-08-12 12:32
Thank you for your report.

This issue is a near-duplicate of #3199. I decided to update #3199 to include this issue.

**Closed by devos50** 2018-08-12 12:32 UTC
