### ISSUE TITLE
Opening torrent: can not see if downloaded data have any parent folder or just files

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2738] opened 2017-01-18 13:50 UTC
##### Tribler version/branch+revision: #####
Alpha v7, Build #341 - https://jenkins.tribler.org/job/Build-Tribler_Win64/341/
##### Operating system and version: #####
Windows 10 64bit Home
##### Description: #####
When i open an torrent in Tribler i would like to see if torrent contains only files or if there are files with some parent folder which will be created during download. Tribler will not show whether torrent will create parent folder so i can not decide if i need to create folder for the files or not.

Some torrent clients shows the folder structure of the torrent and allows renaming parent folder that will be created during torrent download.

**Comment by devos50** [comment] 2017-01-18 13:52
Thank you for your suggestion. I'm not sure whether we will implement this in Tribler 7 but we will take it into consideration.

**Comment by devos50** [comment] 2018-03-22 13:47
We're unable to reproduce this specific issue, therefore I will close it.

**Closed by devos50** 2018-03-22 13:47 UTC
Labels: enhancement

**Comment by slrslr** [comment] 2018-03-22 15:52
I would be glad to help reproduce it as i see it an important feature. Just let me know if you are need my assistance.

**Comment by qstokkink** [comment] 2018-03-23 09:03
Note that the renaming issue is still open (#2602).

As for the download folder. The rule is that:

1. Single file torrents are placed in the download folder directly
2. All other torrents get a subdirectory

**Comment by slrslr** [comment] 2018-03-23 10:15
@qstokkink @devos50 thanks for the reply, the issue is when you open a torrent file, you often do not know what are contents of the torrent (payload), if it has folder, how many files inside. So you can not decide in Tribler whether to create parent directory or not - if tribler not show torrent payload (contents structure) and preferably also allow changing folder and file names as requested in #2602 So if this issue is closed, it seems OK when 2602 is open.
