### ISSUE TITLE
Mac version unstable: event_request_manager.py”, line 130, in on_read_data

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3967] opened 2018-10-16 13:13 UTC
Complete crash of Tribler 7.1; Encoutered by mutiple users and user 0.

Traceback (most recent call last):
File “TriblerGUI\event_request_manager.py”, line 130, in on_read_data
RuntimeError: [Failure instance: Traceback (failure with no frames): <type ‘exceptions.RuntimeError’>: Node Peer<108.34.182.14:7759, vkAFhJP1iz+uTBPRQSdVsCUcoEM=> timeout
]

https://forum.tribler.org/t/tribler-7-1-0-stable-release/4796/5

**Comment by devos50** [comment] 2018-10-16 13:37
Duplicate of #3957, I made that issue high priority.

**Closed by devos50** 2018-10-16 13:37 UTC
Labels: bug
