### ISSUE TITLE
Some seeds do not Increase Ratio

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3871] opened 2018-09-13 07:24 UTC
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.
Yes the 11 sept version
##### Tribler version/branch+revision: #####
7.1 11-09-2018
##### Operating system and version: #####
Windows 10 Insider 17758
##### Steps to reproduce the behavior: #####
Just seed several Torrents
##### Expected behavior: #####
When seeding RATIO should increase
##### Actual behavior: #####
Some seeds do increase ratio, most of them do not
##### Relevant log file output: #####
![afbeelding](https://user-images.githubusercontent.com/3630389/45473793-48122380-b738-11e8-99d7-007feccaaaeb.png)

**Comment by devos50** [comment] 2019-02-28 10:58
Duplicate of #4161, please continue the discussion on that issue.

**Closed by devos50** 2019-02-28 10:58 UTC
Labels: bug
